{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 39036,
          "sha512": "e839aebac297ac259b9c4e9992bb087ae736940e8d38b3cf6fb26ec823d82297358bc846ea9fdef3f3f438519617fcdc2d381630022a2e017fabe387553c272e",
          "sha256": "ffbe44f5e9f6377c3305b16dce3dbb359f1c6d37cd8d1cf5cee4548e0cfbe2a4",
          "sha1": "45c3625616dc624d247ca4a2b5c47b26851d0c35",
          "md5": "5fc7f1e41ee9cd5b57a6f67d022ce8e6"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.6"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.6"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.6"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.6"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 39036,
          "sha512": "e839aebac297ac259b9c4e9992bb087ae736940e8d38b3cf6fb26ec823d82297358bc846ea9fdef3f3f438519617fcdc2d381630022a2e017fabe387553c272e",
          "sha256": "ffbe44f5e9f6377c3305b16dce3dbb359f1c6d37cd8d1cf5cee4548e0cfbe2a4",
          "sha1": "45c3625616dc624d247ca4a2b5c47b26851d0c35",
          "md5": "5fc7f1e41ee9cd5b57a6f67d022ce8e6"
        }
      ]
    }
  ]
}
