{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.analytics",
    "module": "firebase_analytics_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.48"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_analytics_profile-1.48.aar",
          "url": "firebase_analytics_profile-1.48.aar",
          "size": 11415,
          "sha512": "02a703a3faa49fa4af27640189efb7e0093c7c0013fd069c1fbd4c01f6fbbe25bc47e6bd695492091147605892043f3b9a07486917234ac73d62b6d748105e90",
          "sha256": "84257415f2443d812b90aa41a54e47e3c6de94a52f3f02b1625bfa523605bafb",
          "sha1": "324dc3a775ce04646c2ef4153e5799f9bf1b001b",
          "md5": "ab0d1278a8bd19dcd93d7d00b95f670b"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.48"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_analytics_profile-1.48.aar",
          "url": "firebase_analytics_profile-1.48.aar",
          "size": 11415,
          "sha512": "02a703a3faa49fa4af27640189efb7e0093c7c0013fd069c1fbd4c01f6fbbe25bc47e6bd695492091147605892043f3b9a07486917234ac73d62b6d748105e90",
          "sha256": "84257415f2443d812b90aa41a54e47e3c6de94a52f3f02b1625bfa523605bafb",
          "sha1": "324dc3a775ce04646c2ef4153e5799f9bf1b001b",
          "md5": "ab0d1278a8bd19dcd93d7d00b95f670b"
        }
      ]
    }
  ]
}
