{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_release",
    "version": "1.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.52.aar",
          "url": "receive_intent_release-1.52.aar",
          "size": 12909,
          "sha512": "efa4d4c95f96b4d89bfcdc1c186722661dc526e8be1409993db3b1e7388fbc9f23cbec39d0b27ac0e7be70d57e3e87cc3da909ba474b916fe33905d761788c0e",
          "sha256": "809dd65d1cc635ec633cf0529e5f9f09563be89f6acd713ba16fec49c1dd111f",
          "sha1": "e1d2f2b8ea51d189eea73a3fe655dede437a34b5",
          "md5": "c340c57e995a94f62fddd7001d9bb468"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.52.aar",
          "url": "receive_intent_release-1.52.aar",
          "size": 12909,
          "sha512": "efa4d4c95f96b4d89bfcdc1c186722661dc526e8be1409993db3b1e7388fbc9f23cbec39d0b27ac0e7be70d57e3e87cc3da909ba474b916fe33905d761788c0e",
          "sha256": "809dd65d1cc635ec633cf0529e5f9f09563be89f6acd713ba16fec49c1dd111f",
          "sha1": "e1d2f2b8ea51d189eea73a3fe655dede437a34b5",
          "md5": "c340c57e995a94f62fddd7001d9bb468"
        }
      ]
    }
  ]
}
