{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.48.aar",
          "url": "image_picker_android_profile-1.48.aar",
          "size": 57824,
          "sha512": "033750fd0fcd0f9da8dcbf065052adf4f21a2f9b11ac12023a3b8154e9709451da1c9a9e06be8965f625c71c88bd8ad12244bc9517dc616a97dba7f5e87ae58a",
          "sha256": "99a25180668f252bed0406771ecdade27c04163b413660e75cba678219ce09d3",
          "sha1": "42eaad9a7ec0a829ce49179e98d7bdfb7eb65d25",
          "md5": "ce19ffdbf551cde30a5dac10eca55914"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.48"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.48.aar",
          "url": "image_picker_android_profile-1.48.aar",
          "size": 57824,
          "sha512": "033750fd0fcd0f9da8dcbf065052adf4f21a2f9b11ac12023a3b8154e9709451da1c9a9e06be8965f625c71c88bd8ad12244bc9517dc616a97dba7f5e87ae58a",
          "sha256": "99a25180668f252bed0406771ecdade27c04163b413660e75cba678219ce09d3",
          "sha1": "42eaad9a7ec0a829ce49179e98d7bdfb7eb65d25",
          "md5": "ce19ffdbf551cde30a5dac10eca55914"
        }
      ]
    }
  ]
}
