{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.47.aar",
          "url": "url_launcher_android_release-1.47.aar",
          "size": 15057,
          "sha512": "5eb18252ed74317187e0b6338bbdc32240e605e1f92c6364ff3d0a385494d03498af2863f35f67232e1794499fe786c61eadf9f19516922fc12c50040e37f2a3",
          "sha256": "ef5c02be743b6e5d799de24ebf82c6fd6b51ffe84824bcb079e9d3541e75a629",
          "sha1": "dc515eb0124e46ab494026b608a0451565015fd6",
          "md5": "81e0cb6f5a2536cf9fcad937a7c5f2ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.47.aar",
          "url": "url_launcher_android_release-1.47.aar",
          "size": 15057,
          "sha512": "5eb18252ed74317187e0b6338bbdc32240e605e1f92c6364ff3d0a385494d03498af2863f35f67232e1794499fe786c61eadf9f19516922fc12c50040e37f2a3",
          "sha256": "ef5c02be743b6e5d799de24ebf82c6fd6b51ffe84824bcb079e9d3541e75a629",
          "sha1": "dc515eb0124e46ab494026b608a0451565015fd6",
          "md5": "81e0cb6f5a2536cf9fcad937a7c5f2ac"
        }
      ]
    }
  ]
}
