{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.core",
    "module": "firebase_core_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_profile-1.0.aar",
          "url": "firebase_core_profile-1.0.aar",
          "size": 29898,
          "sha512": "e28dbd46df7a0540ab4960a3e0a781c4293dd5744a65116a9a5d027e189b47faa391216d0b6bda86d320e841294a6c6c5bd26274017f80a51f4b7f8ff37c6f38",
          "sha256": "40631ba87454a2e3d6346a0a9f6aa6c3d1777f4280935b4c26ab674ef18893aa",
          "sha1": "6d202c18cf6710dc414adea6cfa5367d78718420",
          "md5": "257e2df6a4dd71b3861ecd08f2525857"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_profile-1.0.aar",
          "url": "firebase_core_profile-1.0.aar",
          "size": 29898,
          "sha512": "e28dbd46df7a0540ab4960a3e0a781c4293dd5744a65116a9a5d027e189b47faa391216d0b6bda86d320e841294a6c6c5bd26274017f80a51f4b7f8ff37c6f38",
          "sha256": "40631ba87454a2e3d6346a0a9f6aa6c3d1777f4280935b4c26ab674ef18893aa",
          "sha1": "6d202c18cf6710dc414adea6cfa5367d78718420",
          "md5": "257e2df6a4dd71b3861ecd08f2525857"
        }
      ]
    }
  ]
}
