{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.core",
    "module": "firebase_core_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_profile-1.0.aar",
          "url": "firebase_core_profile-1.0.aar",
          "size": 29895,
          "sha512": "091fd1f3648af93f779aa48f90d21575b34bbfef6d7c5814bb8d9c42c5f19bc0a1c7014e14047aca2786bb7fb465acccee12dc24680589da766d35b12364b7b7",
          "sha256": "852931309b1780a4f878376c2236ddc32fad8a4be7c9dd1924f2851ce033d404",
          "sha1": "612b7390c9354b617c9ed3e62848f97fbee95852",
          "md5": "e27d7f99134f02b2da578009a756e01f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_profile-1.0.aar",
          "url": "firebase_core_profile-1.0.aar",
          "size": 29895,
          "sha512": "091fd1f3648af93f779aa48f90d21575b34bbfef6d7c5814bb8d9c42c5f19bc0a1c7014e14047aca2786bb7fb465acccee12dc24680589da766d35b12364b7b7",
          "sha256": "852931309b1780a4f878376c2236ddc32fad8a4be7c9dd1924f2851ce033d404",
          "sha1": "612b7390c9354b617c9ed3e62848f97fbee95852",
          "md5": "e27d7f99134f02b2da578009a756e01f"
        }
      ]
    }
  ]
}
