{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.46.aar",
          "url": "url_launcher_android_debug-1.46.aar",
          "size": 15692,
          "sha512": "5ead38a9b7844db38fe38b503b15d2628fdc6e65cf1330980b516d1f7bd616ecaeeba250f30dbb96449eb0739dd9cf0b4e3c1b6a9ed1021421afcde0b171f018",
          "sha256": "ad8254bf4425bb91995fa46822007aab0d608c1f021b11b3b79056b884f46d0a",
          "sha1": "e33f06db07f22dd2dee8da0bb6aebf0263c916ff",
          "md5": "37e1f79b820120b6de72b9978e39395c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.46.aar",
          "url": "url_launcher_android_debug-1.46.aar",
          "size": 15692,
          "sha512": "5ead38a9b7844db38fe38b503b15d2628fdc6e65cf1330980b516d1f7bd616ecaeeba250f30dbb96449eb0739dd9cf0b4e3c1b6a9ed1021421afcde0b171f018",
          "sha256": "ad8254bf4425bb91995fa46822007aab0d608c1f021b11b3b79056b884f46d0a",
          "sha1": "e33f06db07f22dd2dee8da0bb6aebf0263c916ff",
          "md5": "37e1f79b820120b6de72b9978e39395c"
        }
      ]
    }
  ]
}
