{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.database",
    "module": "firebase_database_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_release-1.0.aar",
          "url": "firebase_database_release-1.0.aar",
          "size": 29289,
          "sha512": "2b50aa39a7f6c948c11605966c9a4d704ae7a508c4d21649ae10d8afee1f90e0a533a862be7f5da6e9447fb8f51832c276269b7cb1ebf1673e341b8255f0748e",
          "sha256": "610e96b5d06b352361c7b7613357e58c239193977653bc01ba58fd07232cd51c",
          "sha1": "c769334371dea338bd29a7919c14430a057cb95a",
          "md5": "35bc6b8543de251c64d354cf5916955b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_release-1.0.aar",
          "url": "firebase_database_release-1.0.aar",
          "size": 29289,
          "sha512": "2b50aa39a7f6c948c11605966c9a4d704ae7a508c4d21649ae10d8afee1f90e0a533a862be7f5da6e9447fb8f51832c276269b7cb1ebf1673e341b8255f0748e",
          "sha256": "610e96b5d06b352361c7b7613357e58c239193977653bc01ba58fd07232cd51c",
          "sha1": "c769334371dea338bd29a7919c14430a057cb95a",
          "md5": "35bc6b8543de251c64d354cf5916955b"
        }
      ]
    }
  ]
}
