{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_debug",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.50.aar",
          "url": "share_plus_debug-1.50.aar",
          "size": 22227,
          "sha512": "2c3fb2f0524cfd9eff18a37a41ff8c4ee57d9b4d8822c10f0d8aab96715dd8268d94369a4277facfbbd71e0939472e3cc8b17a63824e949c3b26542f7c174501",
          "sha256": "b6356e8679d2e6e759b5c7e2218f85eb52561c72f399a0cab35bdb8dd83c4d41",
          "sha1": "42c426c61406a48f22b6d4a31ce38c6944b7de02",
          "md5": "4b6413d11127d5234e66e9aa6b2639fd"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.50.aar",
          "url": "share_plus_debug-1.50.aar",
          "size": 22227,
          "sha512": "2c3fb2f0524cfd9eff18a37a41ff8c4ee57d9b4d8822c10f0d8aab96715dd8268d94369a4277facfbbd71e0939472e3cc8b17a63824e949c3b26542f7c174501",
          "sha256": "b6356e8679d2e6e759b5c7e2218f85eb52561c72f399a0cab35bdb8dd83c4d41",
          "sha1": "42c426c61406a48f22b6d4a31ce38c6944b7de02",
          "md5": "4b6413d11127d5234e66e9aa6b2639fd"
        }
      ]
    }
  ]
}
