{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 19697,
          "sha512": "a007213a916e70d39e738b607f27b4895c048fc8bb9df4357761ca127aa473348732ebf21562c23b438e2798175e1ec1ba61ec7661b4650377a1f44bbeab23e0",
          "sha256": "858ad61923a4e746bf867067503e78d1e23c813eb68245ff3e3e7ed5ab13ffde",
          "sha1": "a3052dda633278ccda1ff97343294f4d1ac68c70",
          "md5": "4a47af15235e91a595721df56d889145"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 19697,
          "sha512": "a007213a916e70d39e738b607f27b4895c048fc8bb9df4357761ca127aa473348732ebf21562c23b438e2798175e1ec1ba61ec7661b4650377a1f44bbeab23e0",
          "sha256": "858ad61923a4e746bf867067503e78d1e23c813eb68245ff3e3e7ed5ab13ffde",
          "sha1": "a3052dda633278ccda1ff97343294f4d1ac68c70",
          "md5": "4a47af15235e91a595721df56d889145"
        }
      ]
    }
  ]
}
