{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtplugin.plugincheck",
    "module": "flutter_debug",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_debug",
          "version": {
            "requires": "1.47"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.47.aar",
          "url": "flutter_debug-1.47.aar",
          "size": 23084349,
          "sha512": "e3198df817b635c5a841bc8cbfa1929585b14d777d6a893ccf1b7d4bf53c733a29f8a35de0c86090ddbac9d1e6b0c7cd58e67e9369c571404c0324b0f245070e",
          "sha256": "f2c8db617d7f0c665f230662f869cd979830fcec2bd50d3adabd665b8ff14c20",
          "sha1": "33388e88be12895e7090e8ebb5252442888fa751",
          "md5": "030a083882cfc3f35ce43ca4ccd6885b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_debug",
          "version": {
            "requires": "1.47"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_debug",
          "version": {
            "requires": "1.47"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.47.aar",
          "url": "flutter_debug-1.47.aar",
          "size": 23084349,
          "sha512": "e3198df817b635c5a841bc8cbfa1929585b14d777d6a893ccf1b7d4bf53c733a29f8a35de0c86090ddbac9d1e6b0c7cd58e67e9369c571404c0324b0f245070e",
          "sha256": "f2c8db617d7f0c665f230662f869cd979830fcec2bd50d3adabd665b8ff14c20",
          "sha1": "33388e88be12895e7090e8ebb5252442888fa751",
          "md5": "030a083882cfc3f35ce43ca4ccd6885b"
        }
      ]
    }
  ]
}
