{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.fluttershare",
    "module": "flutter_share",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.38-debug.aar",
          "url": "flutter_share-1.38-debug.aar",
          "size": 6194,
          "sha512": "964e35115483a17cd0b99d4263f8bc47cdc23ffd6cccca80d27a714dc205f98619219f5a5928220b676825dab99f41d48bda89d897f352bf5daeeb40ac0617a1",
          "sha256": "03bc4ebdf0a2207a8aa82e74302675b4096007d21da6cde659f45401780e0a50",
          "sha1": "e72edffadc7351ec7a046e2017fbf716f88f8088",
          "md5": "326691095f5b41a5efbd46004d85780b"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.38-debug.aar",
          "url": "flutter_share-1.38-debug.aar",
          "size": 6194,
          "sha512": "964e35115483a17cd0b99d4263f8bc47cdc23ffd6cccca80d27a714dc205f98619219f5a5928220b676825dab99f41d48bda89d897f352bf5daeeb40ac0617a1",
          "sha256": "03bc4ebdf0a2207a8aa82e74302675b4096007d21da6cde659f45401780e0a50",
          "sha1": "e72edffadc7351ec7a046e2017fbf716f88f8088",
          "md5": "326691095f5b41a5efbd46004d85780b"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.38-release.aar",
          "url": "flutter_share-1.38-release.aar",
          "size": 5939,
          "sha512": "c3cdba601e989a01c2203f74724fc76625fa07b00bb56e500003dc2f4aac983f315560877bf0265aeea918f86043565ad6a37411c4e1a0caa492b300eaa7a240",
          "sha256": "f57ba22ec5740d282177a840d9c136d0410ef5f655b9508643a460c9f44c880f",
          "sha1": "90803c94de5bef272ae93b1eb9189b4602622423",
          "md5": "b96c25aa917815e72442fd3009893043"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.38-release.aar",
          "url": "flutter_share-1.38-release.aar",
          "size": 5939,
          "sha512": "c3cdba601e989a01c2203f74724fc76625fa07b00bb56e500003dc2f4aac983f315560877bf0265aeea918f86043565ad6a37411c4e1a0caa492b300eaa7a240",
          "sha256": "f57ba22ec5740d282177a840d9c136d0410ef5f655b9508643a460c9f44c880f",
          "sha1": "90803c94de5bef272ae93b1eb9189b4602622423",
          "md5": "b96c25aa917815e72442fd3009893043"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.38-profile.aar",
          "url": "flutter_share-1.38-profile.aar",
          "size": 5940,
          "sha512": "953e2b6892c913613e652c013893c68c576be13ef46bad2bd874ddb37fc07779e987d509868ec2224542472ee15998b6cbf5604a036491e8e3fb64244553cf42",
          "sha256": "2b1b029824364229a644c338759d57576171a6b545264310598255d375746329",
          "sha1": "b5214039d809b244f35b34ed2ddf309f8c64eb9c",
          "md5": "9a7121990878761f63a1233cf5d1238b"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.38-profile.aar",
          "url": "flutter_share-1.38-profile.aar",
          "size": 5940,
          "sha512": "953e2b6892c913613e652c013893c68c576be13ef46bad2bd874ddb37fc07779e987d509868ec2224542472ee15998b6cbf5604a036491e8e3fb64244553cf42",
          "sha256": "2b1b029824364229a644c338759d57576171a6b545264310598255d375746329",
          "sha1": "b5214039d809b244f35b34ed2ddf309f8c64eb9c",
          "md5": "9a7121990878761f63a1233cf5d1238b"
        }
      ]
    }
  ]
}
