{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.justsoft.video_thumbnail",
    "module": "video_thumbnail_release",
    "version": "1.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_thumbnail_release-1.49.aar",
          "url": "video_thumbnail_release-1.49.aar",
          "size": 10120,
          "sha512": "619f9379057061deda3f7463d07a0968d7e4b6c154fe391d0e125e9e3bcbf04efe54728bb5c56c351ccb7e400534c09178a7a99500edba3dc8918a5b0d0f94ec",
          "sha256": "67eead4100e2aabe0c4807ce003a5b43fe0f67224acc454358d2654b342ef41d",
          "sha1": "037bae553df4e179bc01afcdf0f74d77dafc2ea5",
          "md5": "a92427f04f2de594a4a2f68c01dbba9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_thumbnail_release-1.49.aar",
          "url": "video_thumbnail_release-1.49.aar",
          "size": 10120,
          "sha512": "619f9379057061deda3f7463d07a0968d7e4b6c154fe391d0e125e9e3bcbf04efe54728bb5c56c351ccb7e400534c09178a7a99500edba3dc8918a5b0d0f94ec",
          "sha256": "67eead4100e2aabe0c4807ce003a5b43fe0f67224acc454358d2654b342ef41d",
          "sha1": "037bae553df4e179bc01afcdf0f74d77dafc2ea5",
          "md5": "a92427f04f2de594a4a2f68c01dbba9e"
        }
      ]
    }
  ]
}
