{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.17.aar",
          "url": "share_plus_release-1.17.aar",
          "size": 23383,
          "sha512": "b7a21e37e63c9c4d0e175b241d70d7f6c5daad2f4a7ef64d06502933828feb037186f6dffd6f7a4c0fb52f0b188ef3efe7904bf2e94407e80128fb4989a2910a",
          "sha256": "78f9cf1d35a82e779c171cc404eb89c95b280b5db756999c950495be82f63688",
          "sha1": "50e30cc56fc969f8bb81b69615e265ec54ac8c55",
          "md5": "4998b584f8c9de6fdcb63b3257cac628"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.17.aar",
          "url": "share_plus_release-1.17.aar",
          "size": 23383,
          "sha512": "b7a21e37e63c9c4d0e175b241d70d7f6c5daad2f4a7ef64d06502933828feb037186f6dffd6f7a4c0fb52f0b188ef3efe7904bf2e94407e80128fb4989a2910a",
          "sha256": "78f9cf1d35a82e779c171cc404eb89c95b280b5db756999c950495be82f63688",
          "sha1": "50e30cc56fc969f8bb81b69615e265ec54ac8c55",
          "md5": "4998b584f8c9de6fdcb63b3257cac628"
        }
      ]
    }
  ]
}
