{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_profile-1.48.aar",
          "url": "native_exif_profile-1.48.aar",
          "size": 7876,
          "sha512": "9c2ca3fc3f856a0cc5565da23d1f4187f369fe03568097fa3914b434cbe89437773eb37dc48103aa2b4e1765d10383049d9c6ab199c545d927057d42c5fa4455",
          "sha256": "3368922223021a57d13bcb1358c5736824711289d42bfa4433c36f8330711189",
          "sha1": "e8a0b228dfeca83066fee7e43e20d9d6acd5ac3a",
          "md5": "f41735159133feab5233b3b0298dc06e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_profile-1.48.aar",
          "url": "native_exif_profile-1.48.aar",
          "size": 7876,
          "sha512": "9c2ca3fc3f856a0cc5565da23d1f4187f369fe03568097fa3914b434cbe89437773eb37dc48103aa2b4e1765d10383049d9c6ab199c545d927057d42c5fa4455",
          "sha256": "3368922223021a57d13bcb1358c5736824711289d42bfa4433c36f8330711189",
          "sha1": "e8a0b228dfeca83066fee7e43e20d9d6acd5ac3a",
          "md5": "f41735159133feab5233b3b0298dc06e"
        }
      ]
    }
  ]
}
