{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtplugin.plugincheck",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.fluttershare",
          "module": "flutter_share",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 13976829,
          "sha512": "b87cd11da05b42f9234a0a48920953d6ff1530a2f1c412173ce089e2cc82e9b5184d9f53991e485613e581fe9228fd12a660b57020213a0f32a39a7991d5a7e6",
          "sha256": "e8f1419407b8b43646cd9238118687566a4ac9c5686f4c2b85fe784f0295ac2a",
          "sha1": "3d65754dd4e23c92cdeff051f9d96816e1db8a14",
          "md5": "0f6ee59318369b18dfa5c17f63032083"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.fluttershare",
          "module": "flutter_share",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 13976829,
          "sha512": "b87cd11da05b42f9234a0a48920953d6ff1530a2f1c412173ce089e2cc82e9b5184d9f53991e485613e581fe9228fd12a660b57020213a0f32a39a7991d5a7e6",
          "sha256": "e8f1419407b8b43646cd9238118687566a4ac9c5686f4c2b85fe784f0295ac2a",
          "sha1": "3d65754dd4e23c92cdeff051f9d96816e1db8a14",
          "md5": "0f6ee59318369b18dfa5c17f63032083"
        }
      ]
    }
  ]
}
