{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.48.aar",
          "url": "fluttertoast_release-1.48.aar",
          "size": 10084,
          "sha512": "35e14aeb1737d7614a3d42056dbf70eb20570c12febcd20f7575ed07e8106ac8a84d19c380460ff765c72736054bb2f7121ec64689a945922c0d0d6334cb6c97",
          "sha256": "9cbe09ce864d6b2702731d8fd8b31319c9c7bc4cd409707c3068935f7febfd33",
          "sha1": "5ad0b0bbdae73015b6a34c0787075000892be19c",
          "md5": "79c970adeb118ef6cea962fa1e20ccec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.48.aar",
          "url": "fluttertoast_release-1.48.aar",
          "size": 10084,
          "sha512": "35e14aeb1737d7614a3d42056dbf70eb20570c12febcd20f7575ed07e8106ac8a84d19c380460ff765c72736054bb2f7121ec64689a945922c0d0d6334cb6c97",
          "sha256": "9cbe09ce864d6b2702731d8fd8b31319c9c7bc4cd409707c3068935f7febfd33",
          "sha1": "5ad0b0bbdae73015b6a34c0787075000892be19c",
          "md5": "79c970adeb118ef6cea962fa1e20ccec"
        }
      ]
    }
  ]
}
