{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "1.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.49.aar",
          "url": "fluttertoast_release-1.49.aar",
          "size": 10097,
          "sha512": "95349d9fd3d906b4cdc6782815f09dd1522d4b7a6a418a57765383a7e2f2d2b91fea10f81cb0de88d091e308f0182434ef10437335f11a77c1790fa4482b60e7",
          "sha256": "94894aa9476fb0ba82080790ac31cd26e52e7b9f63ee8c287a6ca494ae994967",
          "sha1": "0b4e2eb362537d5bcdd4f2981a83e40cdc09fd8e",
          "md5": "a2e80d16492ba0fde6e78770354e8d3f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.49.aar",
          "url": "fluttertoast_release-1.49.aar",
          "size": 10097,
          "sha512": "95349d9fd3d906b4cdc6782815f09dd1522d4b7a6a418a57765383a7e2f2d2b91fea10f81cb0de88d091e308f0182434ef10437335f11a77c1790fa4482b60e7",
          "sha256": "94894aa9476fb0ba82080790ac31cd26e52e7b9f63ee8c287a6ca494ae994967",
          "sha1": "0b4e2eb362537d5bcdd4f2981a83e40cdc09fd8e",
          "md5": "a2e80d16492ba0fde6e78770354e8d3f"
        }
      ]
    }
  ]
}
