{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_release",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.50.aar",
          "url": "native_exif_release-1.50.aar",
          "size": 7924,
          "sha512": "f885d59420ffae03f5bbd941b3ac32169ede68e2d54b406f28990e3b9e1fb13dc1e5c360e6a292b65f31a8812d5df061773534f880cfcd31417dfc1e33cb63c7",
          "sha256": "2f134b5a2bea3937934a631978d7936eea4b0168333e0527994495b19d832577",
          "sha1": "b9415dfaac0e0e36f15e7c96c663faa93c158555",
          "md5": "2d8a32aea43d97c2a0eb7fefd64b0b63"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.50.aar",
          "url": "native_exif_release-1.50.aar",
          "size": 7924,
          "sha512": "f885d59420ffae03f5bbd941b3ac32169ede68e2d54b406f28990e3b9e1fb13dc1e5c360e6a292b65f31a8812d5df061773534f880cfcd31417dfc1e33cb63c7",
          "sha256": "2f134b5a2bea3937934a631978d7936eea4b0168333e0527994495b19d832577",
          "sha1": "b9415dfaac0e0e36f15e7c96c663faa93c158555",
          "md5": "2d8a32aea43d97c2a0eb7fefd64b0b63"
        }
      ]
    }
  ]
}
