{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.database",
    "module": "firebase_database_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_debug-1.0.aar",
          "url": "firebase_database_debug-1.0.aar",
          "size": 30810,
          "sha512": "7e3b4eae69d38ed9437481561130045a758d9c4def9a71aad4489fee1c6301b229f70b4a0ef96b88a2d4ea0300c7743fe4b55c0e24df09e9b3dd9de039976274",
          "sha256": "85995273983f15a010649ff50a7ca20793b0ce1806e189633c47b720b8b9af41",
          "sha1": "0cdbcc2445c8c9d2e4fc2a0781e72862705366fb",
          "md5": "2e3edc2c9097c1f5c005a718f2dca681"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_debug-1.0.aar",
          "url": "firebase_database_debug-1.0.aar",
          "size": 30810,
          "sha512": "7e3b4eae69d38ed9437481561130045a758d9c4def9a71aad4489fee1c6301b229f70b4a0ef96b88a2d4ea0300c7743fe4b55c0e24df09e9b3dd9de039976274",
          "sha256": "85995273983f15a010649ff50a7ca20793b0ce1806e189633c47b720b8b9af41",
          "sha1": "0cdbcc2445c8c9d2e4fc2a0781e72862705366fb",
          "md5": "2e3edc2c9097c1f5c005a718f2dca681"
        }
      ]
    }
  ]
}
