{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_profile",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.38.aar",
          "url": "fluttertoast_profile-1.38.aar",
          "size": 10296,
          "sha512": "a16d83ae9e5e7661e920a9e21c2ab883e3b4c83d2f47ad2578db3eaaa83b583bccf000dc4102c87bf38bb66586017556e1dc72a2e98a1e4c0389214c9969893b",
          "sha256": "e0df17532682d779980bb5b7284a55c1e780f75f7ad2e1cfa6cc32268d61565a",
          "sha1": "10bc610bd9068144523be86e9e8d983fee2621c6",
          "md5": "178ac24d29becf28023415be79d43166"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.38.aar",
          "url": "fluttertoast_profile-1.38.aar",
          "size": 10296,
          "sha512": "a16d83ae9e5e7661e920a9e21c2ab883e3b4c83d2f47ad2578db3eaaa83b583bccf000dc4102c87bf38bb66586017556e1dc72a2e98a1e4c0389214c9969893b",
          "sha256": "e0df17532682d779980bb5b7284a55c1e780f75f7ad2e1cfa6cc32268d61565a",
          "sha1": "10bc610bd9068144523be86e9e8d983fee2621c6",
          "md5": "178ac24d29becf28023415be79d43166"
        }
      ]
    }
  ]
}
