{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.auth",
    "module": "firebase_auth_profile",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth_profile-1.46.aar",
          "url": "firebase_auth_profile-1.46.aar",
          "size": 60404,
          "sha512": "faa9884628b0c052c8d517ca30cd345dcab66303674b883df9643074c119347cd3f5b3df18e59a98505fe45689f99f16c0d114b7800886f4bf4f0fb8db275701",
          "sha256": "28454fcfede2c77a11d62fe91bbe3901c30d60cf61a735db4f6c80b1d2500036",
          "sha1": "04a6dccc5a86b5e8553b9ad4f08c26e94b059e1e",
          "md5": "83634188354f33d7fdc35c401ad69f06"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth_profile-1.46.aar",
          "url": "firebase_auth_profile-1.46.aar",
          "size": 60404,
          "sha512": "faa9884628b0c052c8d517ca30cd345dcab66303674b883df9643074c119347cd3f5b3df18e59a98505fe45689f99f16c0d114b7800886f4bf4f0fb8db275701",
          "sha256": "28454fcfede2c77a11d62fe91bbe3901c30d60cf61a735db4f6c80b1d2500036",
          "sha1": "04a6dccc5a86b5e8553b9ad4f08c26e94b059e1e",
          "md5": "83634188354f33d7fdc35c401ad69f06"
        }
      ]
    }
  ]
}
