{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "1.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-1.51.aar",
          "url": "sqflite_release-1.51.aar",
          "size": 42510,
          "sha512": "9e573f58dfaedef59a173b5ab44809a1e17736d4f106363001f22bcc47775c7322012d8b1768d7a4929b01a09fa554f867a44696af2a5b726d52ab20c9990ab5",
          "sha256": "507be07ccda6404914bbe6a483c3c510430c5808dc8c0aab656e2cfd50f43bf5",
          "sha1": "36f1dbac709410562d5c626c4eac2e728571921a",
          "md5": "90ecf6c5b1bdd54b02c4b53d5b078f3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-1.51.aar",
          "url": "sqflite_release-1.51.aar",
          "size": 42510,
          "sha512": "9e573f58dfaedef59a173b5ab44809a1e17736d4f106363001f22bcc47775c7322012d8b1768d7a4929b01a09fa554f867a44696af2a5b726d52ab20c9990ab5",
          "sha256": "507be07ccda6404914bbe6a483c3c510430c5808dc8c0aab656e2cfd50f43bf5",
          "sha1": "36f1dbac709410562d5c626c4eac2e728571921a",
          "md5": "90ecf6c5b1bdd54b02c4b53d5b078f3e"
        }
      ]
    }
  ]
}
