{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "1.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.51.aar",
          "url": "share_plus_release-1.51.aar",
          "size": 21348,
          "sha512": "fcb616752f563a57e817415f76d2fbbb058384f05e7e35d043cb592b5ef9712c45d349d626b34f33611119fb539104a6d3264ee9f4b58fb1ef4da80976865c3a",
          "sha256": "abef5de421ed939901787cff1037b0430909ab93a724f5229d9e634d0ff1fb30",
          "sha1": "3622542975f41102ce998215a15ce7ab4fa88e36",
          "md5": "d75c8c796dcd0546a02e1de434445ecb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.51.aar",
          "url": "share_plus_release-1.51.aar",
          "size": 21348,
          "sha512": "fcb616752f563a57e817415f76d2fbbb058384f05e7e35d043cb592b5ef9712c45d349d626b34f33611119fb539104a6d3264ee9f4b58fb1ef4da80976865c3a",
          "sha256": "abef5de421ed939901787cff1037b0430909ab93a724f5229d9e634d0ff1fb30",
          "sha1": "3622542975f41102ce998215a15ce7ab4fa88e36",
          "md5": "d75c8c796dcd0546a02e1de434445ecb"
        }
      ]
    }
  ]
}
