{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.0.aar",
          "url": "receive_intent_release-1.0.aar",
          "size": 12870,
          "sha512": "70e58f9e8ce857de9cf3fe9f556b74266cbb2d0bedb3cd8992cb2fff3e0df6a5adb161c2837d20805151f6ddc08df18dee8baf1ceb7ab3586bd53e2e6c77e78f",
          "sha256": "19b280a3e0f88b1edda63006d8ddec3fab24631d0167e7ac1d50563f7a39081f",
          "sha1": "bb53d4134bb6ab26b4ecd8c7113a1c604792ec90",
          "md5": "86a8ebb82a70f565cc4d1ad7112f3f1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.0.aar",
          "url": "receive_intent_release-1.0.aar",
          "size": 12870,
          "sha512": "70e58f9e8ce857de9cf3fe9f556b74266cbb2d0bedb3cd8992cb2fff3e0df6a5adb161c2837d20805151f6ddc08df18dee8baf1ceb7ab3586bd53e2e6c77e78f",
          "sha256": "19b280a3e0f88b1edda63006d8ddec3fab24631d0167e7ac1d50563f7a39081f",
          "sha1": "bb53d4134bb6ab26b4ecd8c7113a1c604792ec90",
          "md5": "86a8ebb82a70f565cc4d1ad7112f3f1d"
        }
      ]
    }
  ]
}
