{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.0.aar",
          "url": "receive_intent_release-1.0.aar",
          "size": 12907,
          "sha512": "7e0c69be06e0ad93eaf87beaa02e287cdbae8a9097e0c47692efa8349a2387d03d211c11e0d5021728a9e72627aaf79ab517ba14bc2134b56ad87ae4132b7bd2",
          "sha256": "4b5a1c1e1f75ea6bb49649a89c35cf95855dcf483092acc1feef4163677c4788",
          "sha1": "48d7fc36e5aa53d13c117b4f77827464d8913d03",
          "md5": "c25a51577a68a5a3ae357e9d77f95ea3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.0.aar",
          "url": "receive_intent_release-1.0.aar",
          "size": 12907,
          "sha512": "7e0c69be06e0ad93eaf87beaa02e287cdbae8a9097e0c47692efa8349a2387d03d211c11e0d5021728a9e72627aaf79ab517ba14bc2134b56ad87ae4132b7bd2",
          "sha256": "4b5a1c1e1f75ea6bb49649a89c35cf95855dcf483092acc1feef4163677c4788",
          "sha1": "48d7fc36e5aa53d13c117b4f77827464d8913d03",
          "md5": "c25a51577a68a5a3ae357e9d77f95ea3"
        }
      ]
    }
  ]
}
