{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.0.aar",
          "url": "receive_intent_release-1.0.aar",
          "size": 12864,
          "sha512": "15efe97241112a8790dddc58c312fd10f08a1524769407131cf30041b7413a8b41d9e1a174eb9b771ddc02bea0123405763c91755456e4a7b85d041b6ebca001",
          "sha256": "c220567eee72aedb927c1f9740f5ed2518661edc52258dac35ec280b3e2e61b4",
          "sha1": "41483f019178f0eb2d032b4b5d747872fd0d1545",
          "md5": "4acc8fd866daf00518988f7077f1b1d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.0.aar",
          "url": "receive_intent_release-1.0.aar",
          "size": 12864,
          "sha512": "15efe97241112a8790dddc58c312fd10f08a1524769407131cf30041b7413a8b41d9e1a174eb9b771ddc02bea0123405763c91755456e4a7b85d041b6ebca001",
          "sha256": "c220567eee72aedb927c1f9740f5ed2518661edc52258dac35ec280b3e2e61b4",
          "sha1": "41483f019178f0eb2d032b4b5d747872fd0d1545",
          "md5": "4acc8fd866daf00518988f7077f1b1d5"
        }
      ]
    }
  ]
}
