{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_debug",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.50.aar",
          "url": "receive_intent_debug-1.50.aar",
          "size": 13486,
          "sha512": "0841a7a36dca6560c97d46adc3d7cbff5e53d1d4935d3cdde27a129ee2a78f0aab4e25ae31359bf4ce0ef73cbfa6e8b0707fc116ae5ddb237cd7858d89981d19",
          "sha256": "ada54111ffcb0dacab227fe41376fb30969d586d0bea87df0708cc9d305cfc72",
          "sha1": "a2bf4cb46b89613afd71437f7f832afddbe53c0c",
          "md5": "0db6bc47b63a43ba49a6c606ce4d7c3e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.50.aar",
          "url": "receive_intent_debug-1.50.aar",
          "size": 13486,
          "sha512": "0841a7a36dca6560c97d46adc3d7cbff5e53d1d4935d3cdde27a129ee2a78f0aab4e25ae31359bf4ce0ef73cbfa6e8b0707fc116ae5ddb237cd7858d89981d19",
          "sha256": "ada54111ffcb0dacab227fe41376fb30969d586d0bea87df0708cc9d305cfc72",
          "sha1": "a2bf4cb46b89613afd71437f7f832afddbe53c0c",
          "md5": "0db6bc47b63a43ba49a6c606ce4d7c3e"
        }
      ]
    }
  ]
}
