{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.justsoft.video_thumbnail",
    "module": "video_thumbnail_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_thumbnail_profile-1.0.aar",
          "url": "video_thumbnail_profile-1.0.aar",
          "size": 10004,
          "sha512": "63240246d27216244fecae5372ac906f2c7c90baf7a17ccf2961cc7781280e204c71b131c41e3d30f769e98fd9968bac90bdb5c383913cd76ac1391ad76c15b8",
          "sha256": "ba296239adcd4690aa2a9e96d97f4f638cae55e1f09c0a70fe72bc89026c5404",
          "sha1": "84507fac10b7d4eff8744363faf97706289ef537",
          "md5": "883a44226bbdd2cb0a6d85066bd6590e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_thumbnail_profile-1.0.aar",
          "url": "video_thumbnail_profile-1.0.aar",
          "size": 10004,
          "sha512": "63240246d27216244fecae5372ac906f2c7c90baf7a17ccf2961cc7781280e204c71b131c41e3d30f769e98fd9968bac90bdb5c383913cd76ac1391ad76c15b8",
          "sha256": "ba296239adcd4690aa2a9e96d97f4f638cae55e1f09c0a70fe72bc89026c5404",
          "sha1": "84507fac10b7d4eff8744363faf97706289ef537",
          "md5": "883a44226bbdd2cb0a6d85066bd6590e"
        }
      ]
    }
  ]
}
