{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_debug",
    "version": "1.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-1.51.aar",
          "url": "fluttertoast_debug-1.51.aar",
          "size": 10386,
          "sha512": "401c153589204dd961e05886e67a1c62ab6f3e62b5c8dd377b2e27625e47c9bff634202642edcf2ad3f7a8906e6fef64b1a7849c370cd0829bd8439e1153bdf9",
          "sha256": "c282f931942b947ee4daf0b1f8d0daad53750c426afc46631ebcfd655365cd6d",
          "sha1": "1380a1891582a67a7e901fb3af60c0927979d110",
          "md5": "c421a6deba13102fd74bfb0c769484c3"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-1.51.aar",
          "url": "fluttertoast_debug-1.51.aar",
          "size": 10386,
          "sha512": "401c153589204dd961e05886e67a1c62ab6f3e62b5c8dd377b2e27625e47c9bff634202642edcf2ad3f7a8906e6fef64b1a7849c370cd0829bd8439e1153bdf9",
          "sha256": "c282f931942b947ee4daf0b1f8d0daad53750c426afc46631ebcfd655365cd6d",
          "sha1": "1380a1891582a67a7e901fb3af60c0927979d110",
          "md5": "c421a6deba13102fd74bfb0c769484c3"
        }
      ]
    }
  ]
}
