{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebasemessaging",
    "module": "firebase_messaging_debug",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_debug-1.46.aar",
          "url": "firebase_messaging_debug-1.46.aar",
          "size": 50226,
          "sha512": "08bf85f0d7d7f385ecbb9d7091d210cd59fb500866a2058562c78059418aa75dd2c743f9d868e457669e4b384c79ab6d4fc2d58a728cf8554d4f48e334931a36",
          "sha256": "c9dd290a41015bca88bb1bc1eedef723fdeea75a001a744ffaaa5f8152aea69c",
          "sha1": "6c649471a08fe4e981d8ac681ad4352ed91fd5e7",
          "md5": "7781be7425de87f3771e83e4b16bd702"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-iid",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_debug-1.46.aar",
          "url": "firebase_messaging_debug-1.46.aar",
          "size": 50226,
          "sha512": "08bf85f0d7d7f385ecbb9d7091d210cd59fb500866a2058562c78059418aa75dd2c743f9d868e457669e4b384c79ab6d4fc2d58a728cf8554d4f48e334931a36",
          "sha256": "c9dd290a41015bca88bb1bc1eedef723fdeea75a001a744ffaaa5f8152aea69c",
          "sha1": "6c649471a08fe4e981d8ac681ad4352ed91fd5e7",
          "md5": "7781be7425de87f3771e83e4b16bd702"
        }
      ]
    }
  ]
}
