{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.droibit.plugins.flutter.customtabs",
    "module": "flutter_custom_tabs_debug",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs_debug-1.48.aar",
          "url": "flutter_custom_tabs_debug-1.48.aar",
          "size": 8388,
          "sha512": "07ebe5755360853f0a23e58afb584c01b081061cd3753babeed78d9d1440f71d48d55a06838a9c5ab09629e1f339fa10036bce4ea49c27d467055eee34edc8f6",
          "sha256": "f50f8bf0d2b8fbdb42b6144557a890fa63953121f8be3d906771bd61a63ea6f8",
          "sha1": "86c55fd0d3ef7e2bcb80ff5679361ca0031e274b",
          "md5": "efbfe77cd9bafb925fbbdd8df0e95c08"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs_debug-1.48.aar",
          "url": "flutter_custom_tabs_debug-1.48.aar",
          "size": 8388,
          "sha512": "07ebe5755360853f0a23e58afb584c01b081061cd3753babeed78d9d1440f71d48d55a06838a9c5ab09629e1f339fa10036bce4ea49c27d467055eee34edc8f6",
          "sha256": "f50f8bf0d2b8fbdb42b6144557a890fa63953121f8be3d906771bd61a63ea6f8",
          "sha1": "86c55fd0d3ef7e2bcb80ff5679361ca0031e274b",
          "md5": "efbfe77cd9bafb925fbbdd8df0e95c08"
        }
      ]
    }
  ]
}
