{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtalkies.walletutilityplugin",
    "module": "walletutilityplugin_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_release-1.0.aar",
          "url": "walletutilityplugin_release-1.0.aar",
          "size": 5417,
          "sha512": "6692eb3ef1a035d5dc83b17556502eda10691407597c1b68bebf4eec28336b3c11582b14775e122e96c39714c9971e13fcbf09a671c10504036af8d2c1b5c627",
          "sha256": "723326659910473a43561c4bcdbdfcee9b3bd33faa1d8cb0aedcff2ad8e385de",
          "sha1": "a2144ce832929b81cc130b44edfcb783c4a92a08",
          "md5": "1649b2cf98b87e3dab76ff7014562b0b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_release-1.0.aar",
          "url": "walletutilityplugin_release-1.0.aar",
          "size": 5417,
          "sha512": "6692eb3ef1a035d5dc83b17556502eda10691407597c1b68bebf4eec28336b3c11582b14775e122e96c39714c9971e13fcbf09a671c10504036af8d2c1b5c627",
          "sha256": "723326659910473a43561c4bcdbdfcee9b3bd33faa1d8cb0aedcff2ad8e385de",
          "sha1": "a2144ce832929b81cc130b44edfcb783c4a92a08",
          "md5": "1649b2cf98b87e3dab76ff7014562b0b"
        }
      ]
    }
  ]
}
