{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mixpanel.mixpanel_flutter",
    "module": "mixpanel_flutter_debug",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "mixpanel_flutter_debug-1.46.aar",
          "url": "mixpanel_flutter_debug-1.46.aar",
          "size": 13199,
          "sha512": "9abfb5647ad16ef940e8843249c20527e7aabd6b745db74530dcc04e8908eb1772b1d8b3e0aabf94854632d66b82f8b67eeccc82dbd8d383a37ecf87ef4718da",
          "sha256": "175e62073e696f2b848ff9dc96fdb494e1acbc2ce70536a91945a1ec70178c0b",
          "sha1": "c9f920748d7f78696819bdb8f08135955778843c",
          "md5": "6c70fa52d8a15b32c699a2a6a656c8c9"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.mixpanel.android",
          "module": "mixpanel-android",
          "version": {
            "requires": "6.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mixpanel_flutter_debug-1.46.aar",
          "url": "mixpanel_flutter_debug-1.46.aar",
          "size": 13199,
          "sha512": "9abfb5647ad16ef940e8843249c20527e7aabd6b745db74530dcc04e8908eb1772b1d8b3e0aabf94854632d66b82f8b67eeccc82dbd8d383a37ecf87ef4718da",
          "sha256": "175e62073e696f2b848ff9dc96fdb494e1acbc2ce70536a91945a1ec70178c0b",
          "sha1": "c9f920748d7f78696819bdb8f08135955778843c",
          "md5": "6c70fa52d8a15b32c699a2a6a656c8c9"
        }
      ]
    }
  ]
}
