{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 41659,
          "sha512": "45e526ad76d0578cc5ff1974b7f4d2fc4e54d6d93ba3748f98552f1271454c7ae7cb66b58ffa8acc7489f94e011e609575c8659c27da007ea97c4d65c272f2f0",
          "sha256": "9b9859ff151807fe80c8414fb742987731f729d8bd95b5cac20091f4baa6c0bf",
          "sha1": "b201c75ae5d88d880c36247d3773ef9ee13f72b4",
          "md5": "29b94ccdbb4d8f648afeed91c7dd2938"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 41659,
          "sha512": "45e526ad76d0578cc5ff1974b7f4d2fc4e54d6d93ba3748f98552f1271454c7ae7cb66b58ffa8acc7489f94e011e609575c8659c27da007ea97c4d65c272f2f0",
          "sha256": "9b9859ff151807fe80c8414fb742987731f729d8bd95b5cac20091f4baa6c0bf",
          "sha1": "b201c75ae5d88d880c36247d3773ef9ee13f72b4",
          "md5": "29b94ccdbb4d8f648afeed91c7dd2938"
        }
      ]
    }
  ]
}
