{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 41655,
          "sha512": "03d85f2cf329ab4a5b7bbfde1cfb90255391961b925a71e0d74c01fa5603fa602c8f9e1a09b2ac6bdbf9fa3b09930f7bedcdf3617361a521bf4904ad61fec466",
          "sha256": "2eb088f49d8b3c893c52391987b0923417fe49789a9bc646d2a17f43d9431e81",
          "sha1": "b15bfb9abc4900e2105194cd57bad2eb74d8920a",
          "md5": "17efaaf67c7e00c7219b83ccf56ac303"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 41655,
          "sha512": "03d85f2cf329ab4a5b7bbfde1cfb90255391961b925a71e0d74c01fa5603fa602c8f9e1a09b2ac6bdbf9fa3b09930f7bedcdf3617361a521bf4904ad61fec466",
          "sha256": "2eb088f49d8b3c893c52391987b0923417fe49789a9bc646d2a17f43d9431e81",
          "sha1": "b15bfb9abc4900e2105194cd57bad2eb74d8920a",
          "md5": "17efaaf67c7e00c7219b83ccf56ac303"
        }
      ]
    }
  ]
}
