{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.50.aar",
          "url": "fluttertoast_release-1.50.aar",
          "size": 10118,
          "sha512": "56b312b5eaa75b84b5320b1ae253a7455b8abfcded3b4b72c939b98184e1c83029d495d6665d8dbcd7048f647cc319d8ac1bdd4955d35d53d089c067e957a514",
          "sha256": "da576fa5eef297db7fca5c2d7e5951ed05c9fbe800df637d6cb8aee7627fe976",
          "sha1": "03722f1f282e7a89c7461d1fb18a03cd41e85ad6",
          "md5": "fdc9f09fcfd54cfe8416aa0b80d5d10a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.50.aar",
          "url": "fluttertoast_release-1.50.aar",
          "size": 10118,
          "sha512": "56b312b5eaa75b84b5320b1ae253a7455b8abfcded3b4b72c939b98184e1c83029d495d6665d8dbcd7048f647cc319d8ac1bdd4955d35d53d089c067e957a514",
          "sha256": "da576fa5eef297db7fca5c2d7e5951ed05c9fbe800df637d6cb8aee7627fe976",
          "sha1": "03722f1f282e7a89c7461d1fb18a03cd41e85ad6",
          "md5": "fdc9f09fcfd54cfe8416aa0b80d5d10a"
        }
      ]
    }
  ]
}
