{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_release",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_release-1.46.aar",
          "url": "local_auth_android_release-1.46.aar",
          "size": 63637,
          "sha512": "ee65ebb2d66de49f1d700680197f9b8bfbf4783ee2675d657c9a091e91e9413907a89da7b1ff32bb581df761535a6ad228116aa772db0ec19c4fa5a41f74bfd1",
          "sha256": "2eb277dc4396c9b7e4605062436c754aa4bf724e106d4b4d46764c7fe10d7fa2",
          "sha1": "d6d246b61d1c04cbc9ec0bbefee59c1b1d36036d",
          "md5": "314779b8af05fd4b28807ea7ab6d0405"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_release-1.46.aar",
          "url": "local_auth_android_release-1.46.aar",
          "size": 63637,
          "sha512": "ee65ebb2d66de49f1d700680197f9b8bfbf4783ee2675d657c9a091e91e9413907a89da7b1ff32bb581df761535a6ad228116aa772db0ec19c4fa5a41f74bfd1",
          "sha256": "2eb277dc4396c9b7e4605062436c754aa4bf724e106d4b4d46764c7fe10d7fa2",
          "sha1": "d6d246b61d1c04cbc9ec0bbefee59c1b1d36036d",
          "md5": "314779b8af05fd4b28807ea7ab6d0405"
        }
      ]
    }
  ]
}
