{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_debug",
    "version": "1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.17.aar",
          "url": "native_exif_debug-1.17.aar",
          "size": 8148,
          "sha512": "1cec7271dbc28af631217e6698f77b7ed236b71b22f322e49b328ee2f88b99e6c0fdb0b2abbb87c3939293bfa10555c5fe87e6f64c9e4bfc48e551e6e2c35a7c",
          "sha256": "e730124757028d830eaacb057ebda3da62e7fe7c083e714a22808d5308c0f687",
          "sha1": "f9fa3a9a5f0c0393d77bc259ae233433ec910b0e",
          "md5": "96e242dbe22429b69cb17317419809f7"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.17.aar",
          "url": "native_exif_debug-1.17.aar",
          "size": 8148,
          "sha512": "1cec7271dbc28af631217e6698f77b7ed236b71b22f322e49b328ee2f88b99e6c0fdb0b2abbb87c3939293bfa10555c5fe87e6f64c9e4bfc48e551e6e2c35a7c",
          "sha256": "e730124757028d830eaacb057ebda3da62e7fe7c083e714a22808d5308c0f687",
          "sha1": "f9fa3a9a5f0c0393d77bc259ae233433ec910b0e",
          "md5": "96e242dbe22429b69cb17317419809f7"
        }
      ]
    }
  ]
}
