{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "size": 4677,
          "sha512": "81c979f838901af11af3a84dcd3a1e82e41b22a6f392c7687a67089d3e6f81b964231fbcd19185f80cb1909bb7a2e513e30d892b3a608e457de8c8e9d1071714",
          "sha256": "86e3261327c85dc096ac31b87485368aea34d3eabb7bcccfbddfe98dd2416749",
          "sha1": "b1b87fd283b5ddf534aaf4f404421c9430d37e13",
          "md5": "03e89b76dac55f2b031beb8d3afa62db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "size": 4677,
          "sha512": "81c979f838901af11af3a84dcd3a1e82e41b22a6f392c7687a67089d3e6f81b964231fbcd19185f80cb1909bb7a2e513e30d892b3a608e457de8c8e9d1071714",
          "sha256": "86e3261327c85dc096ac31b87485368aea34d3eabb7bcccfbddfe98dd2416749",
          "sha1": "b1b87fd283b5ddf534aaf4f404421c9430d37e13",
          "md5": "03e89b76dac55f2b031beb8d3afa62db"
        }
      ]
    }
  ]
}
