{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.48.aar",
          "url": "image_picker_android_release-1.48.aar",
          "size": 57826,
          "sha512": "3f0f1ab9b1e249bf25e56a0d759f7615f74c1e2e34f1a32b7d283bd3b1dec9dd4f09a0d2390f2d466e6f7dad94f199244ee16f6efe9a1775b7a878d1d32c887c",
          "sha256": "89c776ca2f3cca5c84cb4113ba0a36b42acfe86fca36c92e095a640bd7690bfa",
          "sha1": "08661a0e20bc7e7520b4aa8e9e85e6b889db5f99",
          "md5": "1c76f2a50becdd7b785b30e4855d3e37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.48"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.48.aar",
          "url": "image_picker_android_release-1.48.aar",
          "size": 57826,
          "sha512": "3f0f1ab9b1e249bf25e56a0d759f7615f74c1e2e34f1a32b7d283bd3b1dec9dd4f09a0d2390f2d466e6f7dad94f199244ee16f6efe9a1775b7a878d1d32c887c",
          "sha256": "89c776ca2f3cca5c84cb4113ba0a36b42acfe86fca36c92e095a640bd7690bfa",
          "sha1": "08661a0e20bc7e7520b4aa8e9e85e6b889db5f99",
          "md5": "1c76f2a50becdd7b785b30e4855d3e37"
        }
      ]
    }
  ]
}
