{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.0.aar",
          "url": "share_plus_release-1.0.aar",
          "size": 23487,
          "sha512": "64a35cb701cfacec45c0a1f01ac26e18c5a9490177884774f1e90294ddf05c14d81629f78a65f6404f1ba9154e9e1b38c7fc9c888c92336f543527a86d3b3b80",
          "sha256": "5ba857a5723395e73fcce45f0f39e14cf89d55210e89c5e0e2ed247216958ffe",
          "sha1": "c6da057b70e1e611f9f9918640b60a65af8bbb84",
          "md5": "884e0906d557f1f1c5e9cbac8fbda50e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.0.aar",
          "url": "share_plus_release-1.0.aar",
          "size": 23487,
          "sha512": "64a35cb701cfacec45c0a1f01ac26e18c5a9490177884774f1e90294ddf05c14d81629f78a65f6404f1ba9154e9e1b38c7fc9c888c92336f543527a86d3b3b80",
          "sha256": "5ba857a5723395e73fcce45f0f39e14cf89d55210e89c5e0e2ed247216958ffe",
          "sha1": "c6da057b70e1e611f9f9918640b60a65af8bbb84",
          "md5": "884e0906d557f1f1c5e9cbac8fbda50e"
        }
      ]
    }
  ]
}
