{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.47.aar",
          "url": "share_plus_release-1.47.aar",
          "size": 21346,
          "sha512": "7f477b3ef188eb9ac3c63d7c23770148bd031862fc2984e362122121c305958e7b0895c37783d0da685da5fe51999b8a660e35ead050a871ca1bca47ce87b105",
          "sha256": "733551c49ff5ae0a2248e0e849baddefbe1109460503e4ceafe7d3b8f1273ac4",
          "sha1": "8e38bcacd3cc30c3b08dd1767759041d0ebe2cd3",
          "md5": "d55796033a0d63f6edf0eed293e3daf3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.47.aar",
          "url": "share_plus_release-1.47.aar",
          "size": 21346,
          "sha512": "7f477b3ef188eb9ac3c63d7c23770148bd031862fc2984e362122121c305958e7b0895c37783d0da685da5fe51999b8a660e35ead050a871ca1bca47ce87b105",
          "sha256": "733551c49ff5ae0a2248e0e849baddefbe1109460503e4ceafe7d3b8f1273ac4",
          "sha1": "8e38bcacd3cc30c3b08dd1767759041d0ebe2cd3",
          "md5": "d55796033a0d63f6edf0eed293e3daf3"
        }
      ]
    }
  ]
}
