{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.0.aar",
          "url": "fluttertoast_profile-1.0.aar",
          "size": 10300,
          "sha512": "0e6fbd9574e6db3647fa3cff08faf87ccb2afc151b4d1dcc8af88d9ab05424fbfaa2c5ed2e8a3f62cdca135293ef3b216d06b740601002d16a0dbc44b7ed9adf",
          "sha256": "cb2c0f47e2750f5e738a59c76ad5a4079fa2cdd2793354a7ae4a3739ba5bcd12",
          "sha1": "2be4b792dd98aee9d7adb61513eb6bb59c9af912",
          "md5": "39f769b14ae2752a5d5e584d9a6c7b1b"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.0.aar",
          "url": "fluttertoast_profile-1.0.aar",
          "size": 10300,
          "sha512": "0e6fbd9574e6db3647fa3cff08faf87ccb2afc151b4d1dcc8af88d9ab05424fbfaa2c5ed2e8a3f62cdca135293ef3b216d06b740601002d16a0dbc44b7ed9adf",
          "sha256": "cb2c0f47e2750f5e738a59c76ad5a4079fa2cdd2793354a7ae4a3739ba5bcd12",
          "sha1": "2be4b792dd98aee9d7adb61513eb6bb59c9af912",
          "md5": "39f769b14ae2752a5d5e584d9a6c7b1b"
        }
      ]
    }
  ]
}
