{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_debug",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.16.aar",
          "url": "receive_intent_debug-1.16.aar",
          "size": 13512,
          "sha512": "c8fb119a3ba895c84a7f05803089aa24c3436a17f3ae848cd0b0e3d7f7ff718a977bb1aa6b8769891cfedb1b10071977f6093eff7ee7f44c1f3e9ede21825a3d",
          "sha256": "64b278d9f3f91442e520f2816ff5af3e25ea994860384f20fee0c9545d2cd3f3",
          "sha1": "ed600a1a141101b06aa6254e1e02dbc7cce99087",
          "md5": "0457abf83ba637e5efe80237565c7d93"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.16.aar",
          "url": "receive_intent_debug-1.16.aar",
          "size": 13512,
          "sha512": "c8fb119a3ba895c84a7f05803089aa24c3436a17f3ae848cd0b0e3d7f7ff718a977bb1aa6b8769891cfedb1b10071977f6093eff7ee7f44c1f3e9ede21825a3d",
          "sha256": "64b278d9f3f91442e520f2816ff5af3e25ea994860384f20fee0c9545d2cd3f3",
          "sha1": "ed600a1a141101b06aa6254e1e02dbc7cce99087",
          "md5": "0457abf83ba637e5efe80237565c7d93"
        }
      ]
    }
  ]
}
