{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtalkies.walletutilityplugin",
    "module": "walletutilityplugin_release",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_release-1.38.aar",
          "url": "walletutilityplugin_release-1.38.aar",
          "size": 8762,
          "sha512": "32c79c62eae3da640a8ca943045e305099f57392322558d14999a80512af06b5e823d4b438523f174a5ef373429193c171010d982f7bca1e8f72891138890bb6",
          "sha256": "1158e959dfb98ec478244697eccb6dd0cca0611ee7f51525ba31cab3427e61fa",
          "sha1": "45c78e578945edaa2169d0088594a2f826cf913a",
          "md5": "6f480efcb013cc2c71caf0784de60e83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "com.example.fluttershare",
          "module": "flutter_share",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent",
          "version": {
            "requires": "1.38"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager",
          "version": {
            "requires": "1.38"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_release-1.38.aar",
          "url": "walletutilityplugin_release-1.38.aar",
          "size": 8762,
          "sha512": "32c79c62eae3da640a8ca943045e305099f57392322558d14999a80512af06b5e823d4b438523f174a5ef373429193c171010d982f7bca1e8f72891138890bb6",
          "sha256": "1158e959dfb98ec478244697eccb6dd0cca0611ee7f51525ba31cab3427e61fa",
          "sha1": "45c78e578945edaa2169d0088594a2f826cf913a",
          "md5": "6f480efcb013cc2c71caf0784de60e83"
        }
      ]
    }
  ]
}
