{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "1.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.52.aar",
          "url": "image_picker_android_release-1.52.aar",
          "size": 66601,
          "sha512": "9a96df37ac0731c81137eab293e6dc1bf749e1d2e8d5dfb9caa5b1f187b792cccbd4f99a54921ddd17c3772f24c4309d99c2cb7a11c7875e5edf4f4ae89b950d",
          "sha256": "3287ad0acbd57543b03f6688c383bda382f6eee57e1c2bcdbcbe5f2497b5009c",
          "sha1": "7cf9adab384ebc9b588b4cc6087c422832ee0df3",
          "md5": "d4dbf864c89306324051563b5b558abc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.52"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.52.aar",
          "url": "image_picker_android_release-1.52.aar",
          "size": 66601,
          "sha512": "9a96df37ac0731c81137eab293e6dc1bf749e1d2e8d5dfb9caa5b1f187b792cccbd4f99a54921ddd17c3772f24c4309d99c2cb7a11c7875e5edf4f4ae89b950d",
          "sha256": "3287ad0acbd57543b03f6688c383bda382f6eee57e1c2bcdbcbe5f2497b5009c",
          "sha1": "7cf9adab384ebc9b588b4cc6087c422832ee0df3",
          "md5": "d4dbf864c89306324051563b5b558abc"
        }
      ]
    }
  ]
}
