{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.16.aar",
          "url": "fluttertoast_release-1.16.aar",
          "size": 10226,
          "sha512": "9cdbf65e257ae30ee1fb71256368ad6a15d862174a9c3af262e9ab648d204173b1ce9d6bbec0459bea17431eb7b34572f3d27476db80c7f63b81c7dd9f967a97",
          "sha256": "00db336a294d9c2d3b895a094c743b11b889febb09e9716555550b76ad22f2ab",
          "sha1": "b7ac911c0f13f42afd531d4e563b12d70101e9d1",
          "md5": "4fee6e906e261cef4160f18cbd4c1b97"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.16.aar",
          "url": "fluttertoast_release-1.16.aar",
          "size": 10226,
          "sha512": "9cdbf65e257ae30ee1fb71256368ad6a15d862174a9c3af262e9ab648d204173b1ce9d6bbec0459bea17431eb7b34572f3d27476db80c7f63b81c7dd9f967a97",
          "sha256": "00db336a294d9c2d3b895a094c743b11b889febb09e9716555550b76ad22f2ab",
          "sha1": "b7ac911c0f13f42afd531d4e563b12d70101e9d1",
          "md5": "4fee6e906e261cef4160f18cbd4c1b97"
        }
      ]
    }
  ]
}
