{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_debug",
    "version": "1.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.49.aar",
          "url": "share_plus_debug-1.49.aar",
          "size": 22131,
          "sha512": "325b6a33cfc7e638b24251cb4f97195aff7b82ffb3910adbb8a70efb6eed9bf3580e1872efb90a3e2601de76cc9bb46d8bed0784b2859405a898b76cac382c43",
          "sha256": "a575f5e6305e1ed94a8d1d60fe211dce7cc5cd84339dc7f3fbace1bdcf46358a",
          "sha1": "e40e9bdeb526205d3248808cbc8ba7c0e423b664",
          "md5": "a3df5d4a5f5f5744fc6d635466725991"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.49.aar",
          "url": "share_plus_debug-1.49.aar",
          "size": 22131,
          "sha512": "325b6a33cfc7e638b24251cb4f97195aff7b82ffb3910adbb8a70efb6eed9bf3580e1872efb90a3e2601de76cc9bb46d8bed0784b2859405a898b76cac382c43",
          "sha256": "a575f5e6305e1ed94a8d1d60fe211dce7cc5cd84339dc7f3fbace1bdcf46358a",
          "sha1": "e40e9bdeb526205d3248808cbc8ba7c0e423b664",
          "md5": "a3df5d4a5f5f5744fc6d635466725991"
        }
      ]
    }
  ]
}
