{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_debug",
    "version": "1.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.51.aar",
          "url": "image_picker_android_debug-1.51.aar",
          "size": 70035,
          "sha512": "52e50c371653b9a763a5ae54a1479ec3e5242f1dbe77236dd608084a6f0d94f4a2b7f744579776c292914805199446b3038c937324bee674737274dae84e1f5d",
          "sha256": "83d27e472dd8c0b8d68d53f2848af77ea7e727312008e5bda3b7935530a335b8",
          "sha1": "55bc6d9d770ed9311d7a60e20f8476469767c4ce",
          "md5": "b8579acd352adb44de76b4c4867a7e7a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.51"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.51.aar",
          "url": "image_picker_android_debug-1.51.aar",
          "size": 70035,
          "sha512": "52e50c371653b9a763a5ae54a1479ec3e5242f1dbe77236dd608084a6f0d94f4a2b7f744579776c292914805199446b3038c937324bee674737274dae84e1f5d",
          "sha256": "83d27e472dd8c0b8d68d53f2848af77ea7e727312008e5bda3b7935530a335b8",
          "sha1": "55bc6d9d770ed9311d7a60e20f8476469767c4ce",
          "md5": "b8579acd352adb44de76b4c4867a7e7a"
        }
      ]
    }
  ]
}
