{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.38.aar",
          "url": "fluttertoast_release-1.38.aar",
          "size": 10289,
          "sha512": "12b65df670dbfab49d27ab191c52082236d01c4ee8f8da10fe935f2a057072e0df8bb01cf1e4ad69eb386bb05d0c21b5b6e994a969d98f881cd62465470b3a69",
          "sha256": "7626ae5d8df97c19e58f388d33f918da86602332cb9095240e37f5d355257570",
          "sha1": "5afbacb833803561b01002450e363e051d7b0d92",
          "md5": "d7e3ff243db30e276099b0f4916f206e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.38.aar",
          "url": "fluttertoast_release-1.38.aar",
          "size": 10289,
          "sha512": "12b65df670dbfab49d27ab191c52082236d01c4ee8f8da10fe935f2a057072e0df8bb01cf1e4ad69eb386bb05d0c21b5b6e994a969d98f881cd62465470b3a69",
          "sha256": "7626ae5d8df97c19e58f388d33f918da86602332cb9095240e37f5d355257570",
          "sha1": "5afbacb833803561b01002450e363e051d7b0d92",
          "md5": "d7e3ff243db30e276099b0f4916f206e"
        }
      ]
    }
  ]
}
