{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.49.aar",
          "url": "url_launcher_android_debug-1.49.aar",
          "size": 21986,
          "sha512": "741d13479e0f56eed4731e6c5c0a81ed16836ee2cafa18886c0e188ffc742401a2e844887a40867e4b8d401531ece42590e26c7b440606f574e8530c1d42f0a2",
          "sha256": "c232a42165c0cc40c53d5223c0ee1fd650c444bbd6895b96d8682d138dce7238",
          "sha1": "268becb91778203d2a53021c17023f0a85b5255a",
          "md5": "0f9f8cd15a4585c3cd90126c07e294c4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.49.aar",
          "url": "url_launcher_android_debug-1.49.aar",
          "size": 21986,
          "sha512": "741d13479e0f56eed4731e6c5c0a81ed16836ee2cafa18886c0e188ffc742401a2e844887a40867e4b8d401531ece42590e26c7b440606f574e8530c1d42f0a2",
          "sha256": "c232a42165c0cc40c53d5223c0ee1fd650c444bbd6895b96d8682d138dce7238",
          "sha1": "268becb91778203d2a53021c17023f0a85b5255a",
          "md5": "0f9f8cd15a4585c3cd90126c07e294c4"
        }
      ]
    }
  ]
}
