{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_release",
    "version": "1.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.52.aar",
          "url": "native_exif_release-1.52.aar",
          "size": 7869,
          "sha512": "7f0611b4e50cbb4dba5952e2dc2f5bc45fe44a181970392ef7faf2d1856d6a5b44214e18d6df4a73032cc8369543d1d169f26777e0d6e3f494e9f5fc83f9e9b3",
          "sha256": "19ce78e890c3a6b0d944f1a2224d83a49574e37d633154a9e297c71c73c67443",
          "sha1": "b5cd86a3982068adeaadeb39eb28450302ebae02",
          "md5": "d39d94c0a4c40b7aaa035691b0b0d200"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.52.aar",
          "url": "native_exif_release-1.52.aar",
          "size": 7869,
          "sha512": "7f0611b4e50cbb4dba5952e2dc2f5bc45fe44a181970392ef7faf2d1856d6a5b44214e18d6df4a73032cc8369543d1d169f26777e0d6e3f494e9f5fc83f9e9b3",
          "sha256": "19ce78e890c3a6b0d944f1a2224d83a49574e37d633154a9e297c71c73c67443",
          "sha1": "b5cd86a3982068adeaadeb39eb28450302ebae02",
          "md5": "d39d94c0a4c40b7aaa035691b0b0d200"
        }
      ]
    }
  ]
}
