{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_debug",
    "version": "1.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.52.aar",
          "url": "receive_intent_debug-1.52.aar",
          "size": 13517,
          "sha512": "277e61cca61a99b38bad15980a540a4fb3d62a15b7edb0e93a8951f828279d6d8252ffae333c312e5c5079a2cff300c5b3232e434d7bf908211cda6db91d7133",
          "sha256": "64d9ce8945da6a07928cb77e1db94916d044ddc79c01e6bf403da57c63b53c45",
          "sha1": "5a65b6619a66ad1d9873741af03516ec3f7e522c",
          "md5": "3c2e99c6a8744eb0d1186051a38dd817"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.52.aar",
          "url": "receive_intent_debug-1.52.aar",
          "size": 13517,
          "sha512": "277e61cca61a99b38bad15980a540a4fb3d62a15b7edb0e93a8951f828279d6d8252ffae333c312e5c5079a2cff300c5b3232e434d7bf908211cda6db91d7133",
          "sha256": "64d9ce8945da6a07928cb77e1db94916d044ddc79c01e6bf403da57c63b53c45",
          "sha1": "5a65b6619a66ad1d9873741af03516ec3f7e522c",
          "md5": "3c2e99c6a8744eb0d1186051a38dd817"
        }
      ]
    }
  ]
}
