{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.48.aar",
          "url": "fluttertoast_profile-1.48.aar",
          "size": 10082,
          "sha512": "447fddd27aad1a3e662423cd0c76b73d6ab4daf682825801b85d6e602cec677707a4845279e06c7a39f4519b2f8ebcf3baa2363216d6328884afdffb1d04ba76",
          "sha256": "bf02045036a0323c1e87465940d21e0d38a88d6a5e31136ae60955731b7c7e8f",
          "sha1": "ca5e612688c2467aa8822db23c47d33a4d2c0081",
          "md5": "e6826cee32d9fc4672749189f2e7039c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.48.aar",
          "url": "fluttertoast_profile-1.48.aar",
          "size": 10082,
          "sha512": "447fddd27aad1a3e662423cd0c76b73d6ab4daf682825801b85d6e602cec677707a4845279e06c7a39f4519b2f8ebcf3baa2363216d6328884afdffb1d04ba76",
          "sha256": "bf02045036a0323c1e87465940d21e0d38a88d6a5e31136ae60955731b7c7e8f",
          "sha1": "ca5e612688c2467aa8822db23c47d33a4d2c0081",
          "md5": "e6826cee32d9fc4672749189f2e7039c"
        }
      ]
    }
  ]
}
