{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.justsoft.video_thumbnail",
    "module": "video_thumbnail_debug",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_thumbnail_debug-1.47.aar",
          "url": "video_thumbnail_debug-1.47.aar",
          "size": 10468,
          "sha512": "8b3dbbd0d11251dceddbbfb1de986e24b9fb03704218c8b4860344f8ec27be427a2d4529de8ca26b8c656d3b6553742d6db5eededd7ba6950518504668a2fb37",
          "sha256": "f27bcfa0717dcda586950e76c982d3deb31abe9b5c080c2a481aa4902a0b9907",
          "sha1": "746424feafb619ddda59e229e3385ba7de8cce18",
          "md5": "16191227f6b36b0b3719067964668bb4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_thumbnail_debug-1.47.aar",
          "url": "video_thumbnail_debug-1.47.aar",
          "size": 10468,
          "sha512": "8b3dbbd0d11251dceddbbfb1de986e24b9fb03704218c8b4860344f8ec27be427a2d4529de8ca26b8c656d3b6553742d6db5eededd7ba6950518504668a2fb37",
          "sha256": "f27bcfa0717dcda586950e76c982d3deb31abe9b5c080c2a481aa4902a0b9907",
          "sha1": "746424feafb619ddda59e229e3385ba7de8cce18",
          "md5": "16191227f6b36b0b3719067964668bb4"
        }
      ]
    }
  ]
}
