{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sidlatau.flutteremailsender",
    "module": "flutter_email_sender_release",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_release-1.46.aar",
          "url": "flutter_email_sender_release-1.46.aar",
          "size": 21605,
          "sha512": "a0f1cd79dc635aeb3c466a9eff2a8b7f4d119b5462207e4dbea842d2bc17294bba8c1dfc22e8df9592ba7e026abdd768ae8c8ef1acfb7884de536599626eb0c2",
          "sha256": "a50fc30b76cb45e4f4ed1d3a6fcea72522f079d2ca1522fd11d23297d518176a",
          "sha1": "efc00a114e698bafa5357fdb12aa2d8b9da91252",
          "md5": "836a32a1a2b695fb801364d679a257a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_release-1.46.aar",
          "url": "flutter_email_sender_release-1.46.aar",
          "size": 21605,
          "sha512": "a0f1cd79dc635aeb3c466a9eff2a8b7f4d119b5462207e4dbea842d2bc17294bba8c1dfc22e8df9592ba7e026abdd768ae8c8ef1acfb7884de536599626eb0c2",
          "sha256": "a50fc30b76cb45e4f4ed1d3a6fcea72522f079d2ca1522fd11d23297d518176a",
          "sha1": "efc00a114e698bafa5357fdb12aa2d8b9da91252",
          "md5": "836a32a1a2b695fb801364d679a257a8"
        }
      ]
    }
  ]
}
