{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_profile",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.46.aar",
          "url": "image_picker_android_profile-1.46.aar",
          "size": 57911,
          "sha512": "d6ba012e8490ae245bd12e5cc96ac3eeaa4287f47583b1e3de7122b200e9f9a7d912a739b7dd79c096a3c6b927f09d6a5fc629a2d7d65a6edaa1a64ecb3cda89",
          "sha256": "ce86c805207c61f0e2fa435f42ae3af6acee343b74bbdb9c55f0746b84e8ba68",
          "sha1": "4bbce1aabe366ca42ad32b2e40d86e34e72bf800",
          "md5": "d732304017f763362a339cf3a7b198a7"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.46.aar",
          "url": "image_picker_android_profile-1.46.aar",
          "size": 57911,
          "sha512": "d6ba012e8490ae245bd12e5cc96ac3eeaa4287f47583b1e3de7122b200e9f9a7d912a739b7dd79c096a3c6b927f09d6a5fc629a2d7d65a6edaa1a64ecb3cda89",
          "sha256": "ce86c805207c61f0e2fa435f42ae3af6acee343b74bbdb9c55f0746b84e8ba68",
          "sha1": "4bbce1aabe366ca42ad32b2e40d86e34e72bf800",
          "md5": "d732304017f763362a339cf3a7b198a7"
        }
      ]
    }
  ]
}
