{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtplugin.plugincheck",
    "module": "flutter_profile",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_profile",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.46.aar",
          "url": "flutter_profile-1.46.aar",
          "size": 15897410,
          "sha512": "35fa0f5f543da4b69d209764ddb6047a3885c2e91cd9282974c840116191db2d225b8014cad5c59c692ebb15b3a7795f572f84756e18e0cbd287d9a08ef5ac28",
          "sha256": "2341680ae9fa72dfbff1f8ec304746532e91b3a28d9296ef2c92713454154f5f",
          "sha1": "af3015ffb248560203a82a3492269531330b82f7",
          "md5": "ada562430edee0831bf6b2d66ce37451"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_profile",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_profile",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.46.aar",
          "url": "flutter_profile-1.46.aar",
          "size": 15897410,
          "sha512": "35fa0f5f543da4b69d209764ddb6047a3885c2e91cd9282974c840116191db2d225b8014cad5c59c692ebb15b3a7795f572f84756e18e0cbd287d9a08ef5ac28",
          "sha256": "2341680ae9fa72dfbff1f8ec304746532e91b3a28d9296ef2c92713454154f5f",
          "sha1": "af3015ffb248560203a82a3492269531330b82f7",
          "md5": "ada562430edee0831bf6b2d66ce37451"
        }
      ]
    }
  ]
}
