{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.fluttershare",
    "module": "flutter_share_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share_profile-1.0.aar",
          "url": "flutter_share_profile-1.0.aar",
          "size": 5943,
          "sha512": "d7e1f0e8d25fa36d21e006c33d341e901dd7553d2ea6419bf1aac4c56af55ebd4ce4a122866869289717456bb7607cfbe4c3f0969c6e8bb0ad975e64a4f902ad",
          "sha256": "902589ca3eac20d5fd4bfe95ec69df8b54c6be9091c053a61894247fda92ca4a",
          "sha1": "cfe634b6acbe2018dff088f29da0dceeb79cd13f",
          "md5": "6d2187cb0ca9427d69d2adb7f9424243"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share_profile-1.0.aar",
          "url": "flutter_share_profile-1.0.aar",
          "size": 5943,
          "sha512": "d7e1f0e8d25fa36d21e006c33d341e901dd7553d2ea6419bf1aac4c56af55ebd4ce4a122866869289717456bb7607cfbe4c3f0969c6e8bb0ad975e64a4f902ad",
          "sha256": "902589ca3eac20d5fd4bfe95ec69df8b54c6be9091c053a61894247fda92ca4a",
          "sha1": "cfe634b6acbe2018dff088f29da0dceeb79cd13f",
          "md5": "6d2187cb0ca9427d69d2adb7f9424243"
        }
      ]
    }
  ]
}
