{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.database",
    "module": "firebase_database_debug",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_debug-1.46.aar",
          "url": "firebase_database_debug-1.46.aar",
          "size": 30814,
          "sha512": "56453ce9f7233025b8726c1cfc82dfeeaef67767b1b1a9dec9bcba12d54e865a069b07e5b12eced52a9cdb5e6173035f2156271f555e238f9dbff50cd09acd10",
          "sha256": "6de82228b3a107f966ccf2788153fe279c4673b2ccf503cc0985a0f1b6ea64f7",
          "sha1": "a5ac9d9e5f66715aba8bd5158d72642407091f7f",
          "md5": "34404587560c33fa5cececc2efdacd6e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_debug-1.46.aar",
          "url": "firebase_database_debug-1.46.aar",
          "size": 30814,
          "sha512": "56453ce9f7233025b8726c1cfc82dfeeaef67767b1b1a9dec9bcba12d54e865a069b07e5b12eced52a9cdb5e6173035f2156271f555e238f9dbff50cd09acd10",
          "sha256": "6de82228b3a107f966ccf2788153fe279c4673b2ccf503cc0985a0f1b6ea64f7",
          "sha1": "a5ac9d9e5f66715aba8bd5158d72642407091f7f",
          "md5": "34404587560c33fa5cececc2efdacd6e"
        }
      ]
    }
  ]
}
