{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sidlatau.flutteremailsender",
    "module": "flutter_email_sender_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_profile-1.48.aar",
          "url": "flutter_email_sender_profile-1.48.aar",
          "size": 21611,
          "sha512": "ebb9c20b18342a66cd672e756363a87c007e707602039378cb909c3263a02f3d8cc5e2d7290edc4f4554ea3627940d07129d2fcefda901429d8d42777f49c1cf",
          "sha256": "56d6c1ab0b242bd36fdb6d3c77234c5be54313404c851d71f88c13a42c22fb8e",
          "sha1": "89a0118033cd4c05b932caeb6ac58190c7e53fa7",
          "md5": "f380a6d0e1babdc5c3fb11740a4da36c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_profile-1.48.aar",
          "url": "flutter_email_sender_profile-1.48.aar",
          "size": 21611,
          "sha512": "ebb9c20b18342a66cd672e756363a87c007e707602039378cb909c3263a02f3d8cc5e2d7290edc4f4554ea3627940d07129d2fcefda901429d8d42777f49c1cf",
          "sha256": "56d6c1ab0b242bd36fdb6d3c77234c5be54313404c851d71f88c13a42c22fb8e",
          "sha1": "89a0118033cd4c05b932caeb6ac58190c7e53fa7",
          "md5": "f380a6d0e1babdc5c3fb11740a4da36c"
        }
      ]
    }
  ]
}
