{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jhomlala.better_player.better_player",
    "module": "better_player_debug",
    "version": "1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "better_player_debug-1.17.aar",
          "url": "better_player_debug-1.17.aar",
          "size": 70668,
          "sha512": "86442af1d452f0966aec7866009e52fe2d82cba3ef90fd28749289892277e0793082e72914bc13a11699bee7a256f1dbd31180440f24f6274cad6068f4b2f2f1",
          "sha256": "686dd32a34a6c4cb5809cdaf6b4dd85ac8cab87c0a5c1abb343feed0161c2c71",
          "sha1": "86f636e670a9b3665f10c69f647e767f5e09b46f",
          "md5": "03ed78131e6250307f959939d97d52c6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-mediasession",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.17"
          }
        }
      ],
      "files": [
        {
          "name": "better_player_debug-1.17.aar",
          "url": "better_player_debug-1.17.aar",
          "size": 70668,
          "sha512": "86442af1d452f0966aec7866009e52fe2d82cba3ef90fd28749289892277e0793082e72914bc13a11699bee7a256f1dbd31180440f24f6274cad6068f4b2f2f1",
          "sha256": "686dd32a34a6c4cb5809cdaf6b4dd85ac8cab87c0a5c1abb343feed0161c2c71",
          "sha1": "86f636e670a9b3665f10c69f647e767f5e09b46f",
          "md5": "03ed78131e6250307f959939d97d52c6"
        }
      ]
    }
  ]
}
