{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.38-debug.aar",
          "url": "receive_intent-1.38-debug.aar",
          "size": 13485,
          "sha512": "b4ccc8a85b27494a6525dbfc16e092a28f1683afc7a05719d78ac960621c61c7c81dd790443f342abf5f51c790166fdf67c4d454c937d62c94121deba86eba4e",
          "sha256": "15774bc66cfaec57ed9ae1a097ae1f074772c27c720411703062978e5e29c87c",
          "sha1": "f4fd3f0c9712cc5b6870832762a4a4f89f34d89b",
          "md5": "a4fd4123e5849ddce46a236332ba909b"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.38-debug.aar",
          "url": "receive_intent-1.38-debug.aar",
          "size": 13485,
          "sha512": "b4ccc8a85b27494a6525dbfc16e092a28f1683afc7a05719d78ac960621c61c7c81dd790443f342abf5f51c790166fdf67c4d454c937d62c94121deba86eba4e",
          "sha256": "15774bc66cfaec57ed9ae1a097ae1f074772c27c720411703062978e5e29c87c",
          "sha1": "f4fd3f0c9712cc5b6870832762a4a4f89f34d89b",
          "md5": "a4fd4123e5849ddce46a236332ba909b"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.38-release.aar",
          "url": "receive_intent-1.38-release.aar",
          "size": 12864,
          "sha512": "15efe97241112a8790dddc58c312fd10f08a1524769407131cf30041b7413a8b41d9e1a174eb9b771ddc02bea0123405763c91755456e4a7b85d041b6ebca001",
          "sha256": "c220567eee72aedb927c1f9740f5ed2518661edc52258dac35ec280b3e2e61b4",
          "sha1": "41483f019178f0eb2d032b4b5d747872fd0d1545",
          "md5": "4acc8fd866daf00518988f7077f1b1d5"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.38-release.aar",
          "url": "receive_intent-1.38-release.aar",
          "size": 12864,
          "sha512": "15efe97241112a8790dddc58c312fd10f08a1524769407131cf30041b7413a8b41d9e1a174eb9b771ddc02bea0123405763c91755456e4a7b85d041b6ebca001",
          "sha256": "c220567eee72aedb927c1f9740f5ed2518661edc52258dac35ec280b3e2e61b4",
          "sha1": "41483f019178f0eb2d032b4b5d747872fd0d1545",
          "md5": "4acc8fd866daf00518988f7077f1b1d5"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.38-profile.aar",
          "url": "receive_intent-1.38-profile.aar",
          "size": 12866,
          "sha512": "511b86cf6a2c4a99798b785434c869175e72fba59e5dbe0856f37f96158fa3d2f828889aae7b9a444ac2610dd8a355f71d344a771469eb05acc71e9724362f19",
          "sha256": "8fefb1017ef352e48a533720d372bd575ccd771145ded18a94d6ae1a88126589",
          "sha1": "de0a2f087812c1aec1b40cf21f46650b6bfe1d29",
          "md5": "964e3f03c912536547b1341b4f8ec22a"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.38-profile.aar",
          "url": "receive_intent-1.38-profile.aar",
          "size": 12866,
          "sha512": "511b86cf6a2c4a99798b785434c869175e72fba59e5dbe0856f37f96158fa3d2f828889aae7b9a444ac2610dd8a355f71d344a771469eb05acc71e9724362f19",
          "sha256": "8fefb1017ef352e48a533720d372bd575ccd771145ded18a94d6ae1a88126589",
          "sha1": "de0a2f087812c1aec1b40cf21f46650b6bfe1d29",
          "md5": "964e3f03c912536547b1341b4f8ec22a"
        }
      ]
    }
  ]
}
