{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_debug",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.48.aar",
          "url": "native_exif_debug-1.48.aar",
          "size": 8151,
          "sha512": "d92eae63f185a618b9b580d42b5b1dd4c7e8a8a91e4c1124b3f9de43cdd909d9ef7e75c32a0f3775c0f5c81263a6e7d186dc5ea4400ca6193a65372a2b601872",
          "sha256": "89649e421e23c53eedb7c123e07162059d84629311dbbaef06851fb3cc416fcd",
          "sha1": "931f0d086652ec3d5f8fca6a21ced115fcc2a9c6",
          "md5": "97b97e232aae8230abd2e24a1da55411"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.48.aar",
          "url": "native_exif_debug-1.48.aar",
          "size": 8151,
          "sha512": "d92eae63f185a618b9b580d42b5b1dd4c7e8a8a91e4c1124b3f9de43cdd909d9ef7e75c32a0f3775c0f5c81263a6e7d186dc5ea4400ca6193a65372a2b601872",
          "sha256": "89649e421e23c53eedb7c123e07162059d84629311dbbaef06851fb3cc416fcd",
          "sha1": "931f0d086652ec3d5f8fca6a21ced115fcc2a9c6",
          "md5": "97b97e232aae8230abd2e24a1da55411"
        }
      ]
    }
  ]
}
