{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus-1.0-debug.aar",
          "url": "share_plus-1.0-debug.aar",
          "size": 24288,
          "sha512": "678e9e6482b597de0ca66296a8a95567897f22b46541e9403e283eba59532e975b9532fb58bdabd87de6b69e14598b292d50a2b584aefe90c457926b2630fb54",
          "sha256": "78e35cb1b23bb877af8712b1d7b34908edb8899416f67ab8bad714e89198910e",
          "sha1": "1caa1055432970ba238b67c387639274a347fa98",
          "md5": "b80bfa832a07d10aa9732adcbac8bb3d"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus-1.0-debug.aar",
          "url": "share_plus-1.0-debug.aar",
          "size": 24288,
          "sha512": "678e9e6482b597de0ca66296a8a95567897f22b46541e9403e283eba59532e975b9532fb58bdabd87de6b69e14598b292d50a2b584aefe90c457926b2630fb54",
          "sha256": "78e35cb1b23bb877af8712b1d7b34908edb8899416f67ab8bad714e89198910e",
          "sha1": "1caa1055432970ba238b67c387639274a347fa98",
          "md5": "b80bfa832a07d10aa9732adcbac8bb3d"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus-1.0-release.aar",
          "url": "share_plus-1.0-release.aar",
          "size": 23474,
          "sha512": "a6d3827835fabdcadad330bd8d4c04b373f188b9de6afd12f524937c350af2508a6b20c0313d95f05bbc578377baa46102605803f426b75233a159eef09d3549",
          "sha256": "18e06f900a0ffd479bd646f410de041c74ae5b239e1705091ee121d904967a22",
          "sha1": "6f829a381ae67786ea2112d799331d26bf0f10e3",
          "md5": "05db5fc441f1ab16c20341ada1725e4f"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus-1.0-release.aar",
          "url": "share_plus-1.0-release.aar",
          "size": 23474,
          "sha512": "a6d3827835fabdcadad330bd8d4c04b373f188b9de6afd12f524937c350af2508a6b20c0313d95f05bbc578377baa46102605803f426b75233a159eef09d3549",
          "sha256": "18e06f900a0ffd479bd646f410de041c74ae5b239e1705091ee121d904967a22",
          "sha1": "6f829a381ae67786ea2112d799331d26bf0f10e3",
          "md5": "05db5fc441f1ab16c20341ada1725e4f"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus-1.0-profile.aar",
          "url": "share_plus-1.0-profile.aar",
          "size": 23488,
          "sha512": "a38b288c46ecf076196f7f269f01c8b3a00dbef60ef2e0ad05c5778a9610a63fa9ac978c9c801e4635daa1d902cf018dfd3c9d630f41dfdcb26479438cd7a42c",
          "sha256": "5b1531adb69074413c278e69cc22362e7fee560f31847d8658b491f8ffeb2125",
          "sha1": "2e2bd6cf78ed1029a9da1b29d3ae8aa22127037c",
          "md5": "033c5ee4490a9ecc069b5cd903a8cc36"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus-1.0-profile.aar",
          "url": "share_plus-1.0-profile.aar",
          "size": 23488,
          "sha512": "a38b288c46ecf076196f7f269f01c8b3a00dbef60ef2e0ad05c5778a9610a63fa9ac978c9c801e4635daa1d902cf018dfd3c9d630f41dfdcb26479438cd7a42c",
          "sha256": "5b1531adb69074413c278e69cc22362e7fee560f31847d8658b491f8ffeb2125",
          "sha1": "2e2bd6cf78ed1029a9da1b29d3ae8aa22127037c",
          "md5": "033c5ee4490a9ecc069b5cd903a8cc36"
        }
      ]
    }
  ]
}
