{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebasemessaging",
    "module": "firebase_messaging_debug",
    "version": "1.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.49"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_debug-1.49.aar",
          "url": "firebase_messaging_debug-1.49.aar",
          "size": 50557,
          "sha512": "1bf364e5f6a80e2ac3faaf90b9fff000158e39ce51fcfff2e29f033a7d57b9d4c97b6aee3f7806cf57e8e144cdaa9ebb75871b0deefdcf1abdc586aef5905d20",
          "sha256": "f9de96d2cfecd5d43facf8b44ab5186af2bbc2626f50248724e3fc348e8e6eb5",
          "sha1": "11a6abacd13b742f3f42b34638d576a59c6d16a7",
          "md5": "d23fa98ecb51c0cbfae45d3bf41b92ce"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-iid",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.49"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_debug-1.49.aar",
          "url": "firebase_messaging_debug-1.49.aar",
          "size": 50557,
          "sha512": "1bf364e5f6a80e2ac3faaf90b9fff000158e39ce51fcfff2e29f033a7d57b9d4c97b6aee3f7806cf57e8e144cdaa9ebb75871b0deefdcf1abdc586aef5905d20",
          "sha256": "f9de96d2cfecd5d43facf8b44ab5186af2bbc2626f50248724e3fc348e8e6eb5",
          "sha1": "11a6abacd13b742f3f42b34638d576a59c6d16a7",
          "md5": "d23fa98ecb51c0cbfae45d3bf41b92ce"
        }
      ]
    }
  ]
}
