{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.core",
    "module": "firebase_core_debug",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_debug-1.47.aar",
          "url": "firebase_core_debug-1.47.aar",
          "size": 31654,
          "sha512": "c7e4ef04b7d17548db6555aadada386d6cc881313c206ec8e7694b1aa7e7ed2c798b11ef66644c0fa84087ea13897ffb91c4268d0435dce89c9ff1f04aa8ac04",
          "sha256": "60b6f84c4ba5f3e829ea8947987d6d1cbd974031c4f3d1284c42dc33d52dadbb",
          "sha1": "b2154be1cb1a378157a69ffbe90a7eaad0b1b07e",
          "md5": "ecfc297fc6253e5bc5d109d5d64bc4e5"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_debug-1.47.aar",
          "url": "firebase_core_debug-1.47.aar",
          "size": 31654,
          "sha512": "c7e4ef04b7d17548db6555aadada386d6cc881313c206ec8e7694b1aa7e7ed2c798b11ef66644c0fa84087ea13897ffb91c4268d0435dce89c9ff1f04aa8ac04",
          "sha256": "60b6f84c4ba5f3e829ea8947987d6d1cbd974031c4f3d1284c42dc33d52dadbb",
          "sha1": "b2154be1cb1a378157a69ffbe90a7eaad0b1b07e",
          "md5": "ecfc297fc6253e5bc5d109d5d64bc4e5"
        }
      ]
    }
  ]
}
