{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_profile",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.47.aar",
          "url": "shared_preferences_android_profile-1.47.aar",
          "size": 12493,
          "sha512": "fdbfd96f98a198cc43feb52cc529acb10164b266fda07ade457634c14d5a4c940adc481cf9b9b90a74649891510535fa615adbc01a5d494e3c61a72ca3b45ecc",
          "sha256": "1f292332f27fccefcab0ed2dee2c292ffb17b274b4687779926655ef81a5dca3",
          "sha1": "21c0f5abb50a86ffd99508f715c7c3a612cf9cf3",
          "md5": "c234222c19dee292e16b264763517c67"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.47.aar",
          "url": "shared_preferences_android_profile-1.47.aar",
          "size": 12493,
          "sha512": "fdbfd96f98a198cc43feb52cc529acb10164b266fda07ade457634c14d5a4c940adc481cf9b9b90a74649891510535fa615adbc01a5d494e3c61a72ca3b45ecc",
          "sha256": "1f292332f27fccefcab0ed2dee2c292ffb17b274b4687779926655ef81a5dca3",
          "sha1": "21c0f5abb50a86ffd99508f715c7c3a612cf9cf3",
          "md5": "c234222c19dee292e16b264763517c67"
        }
      ]
    }
  ]
}
