{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebasemessaging",
    "module": "firebase_messaging_release",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_release-1.46.aar",
          "url": "firebase_messaging_release-1.46.aar",
          "size": 47583,
          "sha512": "d1203ee6101da9328068cda9123223fe243f9c7c69cd29015b6a1dca2b05f4cbd2630ac6d11374a634da4c502f979018a45bbd07f740aee8efc7093f452a023e",
          "sha256": "0b1dba46e28bff21a37f2b078f4b0b9f7b31ba16b6d3a9750280633d3956b830",
          "sha1": "165b325c1b47fe630ad477d3d32d272c9ddbd506",
          "md5": "4b66967380f426cdd9f903dc450e2254"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-iid",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_release-1.46.aar",
          "url": "firebase_messaging_release-1.46.aar",
          "size": 47583,
          "sha512": "d1203ee6101da9328068cda9123223fe243f9c7c69cd29015b6a1dca2b05f4cbd2630ac6d11374a634da4c502f979018a45bbd07f740aee8efc7093f452a023e",
          "sha256": "0b1dba46e28bff21a37f2b078f4b0b9f7b31ba16b6d3a9750280633d3956b830",
          "sha1": "165b325c1b47fe630ad477d3d32d272c9ddbd506",
          "md5": "4b66967380f426cdd9f903dc450e2254"
        }
      ]
    }
  ]
}
