{
  "formatVersion": "1.1",
  "component": {
    "group": "creativemaybeno.wakelock",
    "module": "wakelock_profile",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_profile-1.46.aar",
          "url": "wakelock_profile-1.46.aar",
          "size": 11331,
          "sha512": "c93f4f488e3cb07c408f19decd36c326b6d17059d71cf468aefbb0c157ea650d10bff2baad004ac78f40d06f6133b083e2d3ae994fe89cc472a11648a536741b",
          "sha256": "cdb3ae6a2202c3a1d5513398baa5a5819673dd4ea21f08a1b6544c0023bbec91",
          "sha1": "71a9eb66b5ec015a01b19c2156204780c11d431a",
          "md5": "64d37b7461855a0e7de40cc3a46bea22"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_profile-1.46.aar",
          "url": "wakelock_profile-1.46.aar",
          "size": 11331,
          "sha512": "c93f4f488e3cb07c408f19decd36c326b6d17059d71cf468aefbb0c157ea650d10bff2baad004ac78f40d06f6133b083e2d3ae994fe89cc472a11648a536741b",
          "sha256": "cdb3ae6a2202c3a1d5513398baa5a5819673dd4ea21f08a1b6544c0023bbec91",
          "sha1": "71a9eb66b5ec015a01b19c2156204780c11d431a",
          "md5": "64d37b7461855a0e7de40cc3a46bea22"
        }
      ]
    }
  ]
}
