{
  "formatVersion": "1.1",
  "component": {
    "group": "creativemaybeno.wakelock",
    "module": "wakelock_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_release-1.0.aar",
          "url": "wakelock_release-1.0.aar",
          "size": 11327,
          "sha512": "809296263e66d86bfaa46ea6685e9bc5bd8a9a881cec2e7cdccc6f51f621d6764d299cfbb783c6662d3abf4aa83af79b7065ab15a2bf8ab123036f07a08eabd1",
          "sha256": "621275f00903743727b22ed3e40f84ea4f2749e9570e74753f36a89736e592ac",
          "sha1": "d10d3da563fac7adafb4df46ceb110889d1905f3",
          "md5": "a770b4f4141b6a00e3a56787871f5c72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_release-1.0.aar",
          "url": "wakelock_release-1.0.aar",
          "size": 11327,
          "sha512": "809296263e66d86bfaa46ea6685e9bc5bd8a9a881cec2e7cdccc6f51f621d6764d299cfbb783c6662d3abf4aa83af79b7065ab15a2bf8ab123036f07a08eabd1",
          "sha256": "621275f00903743727b22ed3e40f84ea4f2749e9570e74753f36a89736e592ac",
          "sha1": "d10d3da563fac7adafb4df46ceb110889d1905f3",
          "md5": "a770b4f4141b6a00e3a56787871f5c72"
        }
      ]
    }
  ]
}
