{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.core",
    "module": "firebase_core_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_release-1.0.aar",
          "url": "firebase_core_release-1.0.aar",
          "size": 29898,
          "sha512": "7d784d81aa10fa4e7bade9fe57f1fc4a1286cb65df2506cece0ee6b5a64f80358913ff59eb4ee756e72b6178e86b774e4942e7a71a92c8ccf6cfbf54ddf6e256",
          "sha256": "5594d2710bfc0414b74b6e5373386791afde5583814138a8f8c4c211ae0c8648",
          "sha1": "5092ceabdb199f9aedff17d0ed032872a09647c9",
          "md5": "6b26cced5b204faa3c82d03a65046733"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_release-1.0.aar",
          "url": "firebase_core_release-1.0.aar",
          "size": 29898,
          "sha512": "7d784d81aa10fa4e7bade9fe57f1fc4a1286cb65df2506cece0ee6b5a64f80358913ff59eb4ee756e72b6178e86b774e4942e7a71a92c8ccf6cfbf54ddf6e256",
          "sha256": "5594d2710bfc0414b74b6e5373386791afde5583814138a8f8c4c211ae0c8648",
          "sha1": "5092ceabdb199f9aedff17d0ed032872a09647c9",
          "md5": "6b26cced5b204faa3c82d03a65046733"
        }
      ]
    }
  ]
}
