{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast-1.0-debug.aar",
          "url": "fluttertoast-1.0-debug.aar",
          "size": 10533,
          "sha512": "42c7ee3f5e0bfc2c6c8e1d040b843debbfe6c0d57f469993f001ee258e2b911ec5586d4340bb142316f7726fe7a1778cd047605f5dc06b89cea08b295990ab10",
          "sha256": "7666651f4c228f8a12d595af28bde5f5bbd2845b3798120bd41e31aef7ea743d",
          "sha1": "0008c8dd1251ddbb7a3b0d41c380e4ee4831b531",
          "md5": "4f0c65756d49f9e285d5849fc45d3f53"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast-1.0-debug.aar",
          "url": "fluttertoast-1.0-debug.aar",
          "size": 10533,
          "sha512": "42c7ee3f5e0bfc2c6c8e1d040b843debbfe6c0d57f469993f001ee258e2b911ec5586d4340bb142316f7726fe7a1778cd047605f5dc06b89cea08b295990ab10",
          "sha256": "7666651f4c228f8a12d595af28bde5f5bbd2845b3798120bd41e31aef7ea743d",
          "sha1": "0008c8dd1251ddbb7a3b0d41c380e4ee4831b531",
          "md5": "4f0c65756d49f9e285d5849fc45d3f53"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast-1.0-release.aar",
          "url": "fluttertoast-1.0-release.aar",
          "size": 10226,
          "sha512": "9cdbf65e257ae30ee1fb71256368ad6a15d862174a9c3af262e9ab648d204173b1ce9d6bbec0459bea17431eb7b34572f3d27476db80c7f63b81c7dd9f967a97",
          "sha256": "00db336a294d9c2d3b895a094c743b11b889febb09e9716555550b76ad22f2ab",
          "sha1": "b7ac911c0f13f42afd531d4e563b12d70101e9d1",
          "md5": "4fee6e906e261cef4160f18cbd4c1b97"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast-1.0-release.aar",
          "url": "fluttertoast-1.0-release.aar",
          "size": 10226,
          "sha512": "9cdbf65e257ae30ee1fb71256368ad6a15d862174a9c3af262e9ab648d204173b1ce9d6bbec0459bea17431eb7b34572f3d27476db80c7f63b81c7dd9f967a97",
          "sha256": "00db336a294d9c2d3b895a094c743b11b889febb09e9716555550b76ad22f2ab",
          "sha1": "b7ac911c0f13f42afd531d4e563b12d70101e9d1",
          "md5": "4fee6e906e261cef4160f18cbd4c1b97"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast-1.0-profile.aar",
          "url": "fluttertoast-1.0-profile.aar",
          "size": 10228,
          "sha512": "bd4c0bb815f9f42693198b871baf16966354ddd44b62550b5a21c0c51a0147fac2b89213c7ef800284c6ee87674c97b34616dcf86309d44bf9efe99afe6fbbbd",
          "sha256": "b54e5342f74a03d6e76418c3da5951cff11a96fddf31327377b852e2154b67f0",
          "sha1": "35347b4c3af5ebfc9846a3c5f855b1c3395544fe",
          "md5": "814b97c038cbc4d115a3d8abfb32dce8"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast-1.0-profile.aar",
          "url": "fluttertoast-1.0-profile.aar",
          "size": 10228,
          "sha512": "bd4c0bb815f9f42693198b871baf16966354ddd44b62550b5a21c0c51a0147fac2b89213c7ef800284c6ee87674c97b34616dcf86309d44bf9efe99afe6fbbbd",
          "sha256": "b54e5342f74a03d6e76418c3da5951cff11a96fddf31327377b852e2154b67f0",
          "sha1": "35347b4c3af5ebfc9846a3c5f855b1c3395544fe",
          "md5": "814b97c038cbc4d115a3d8abfb32dce8"
        }
      ]
    }
  ]
}
