{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_profile",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_profile-1.38.aar",
          "url": "receive_intent_profile-1.38.aar",
          "size": 12866,
          "sha512": "511b86cf6a2c4a99798b785434c869175e72fba59e5dbe0856f37f96158fa3d2f828889aae7b9a444ac2610dd8a355f71d344a771469eb05acc71e9724362f19",
          "sha256": "8fefb1017ef352e48a533720d372bd575ccd771145ded18a94d6ae1a88126589",
          "sha1": "de0a2f087812c1aec1b40cf21f46650b6bfe1d29",
          "md5": "964e3f03c912536547b1341b4f8ec22a"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_profile-1.38.aar",
          "url": "receive_intent_profile-1.38.aar",
          "size": 12866,
          "sha512": "511b86cf6a2c4a99798b785434c869175e72fba59e5dbe0856f37f96158fa3d2f828889aae7b9a444ac2610dd8a355f71d344a771469eb05acc71e9724362f19",
          "sha256": "8fefb1017ef352e48a533720d372bd575ccd771145ded18a94d6ae1a88126589",
          "sha1": "de0a2f087812c1aec1b40cf21f46650b6bfe1d29",
          "md5": "964e3f03c912536547b1341b4f8ec22a"
        }
      ]
    }
  ]
}
