{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.46.aar",
          "url": "shared_preferences_android_release-1.46.aar",
          "size": 12495,
          "sha512": "684b132eb43dde898650aa1ff5103f9b5471cf02c4fa4daa7edaa28300b5db7e41fe48a5509ccf8d8a115c428be7713eb6cd4253fa13e225bf4db952240c2765",
          "sha256": "8ee935c6d786f0a37c5294615dcc9df7c189577eb5cfde2ca22f20b5e08f6acb",
          "sha1": "fc74b484eb9c726a9113fb1b77a11891a33c1d5b",
          "md5": "f71898c6d6d9b83307afa7a0c3209a68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.46.aar",
          "url": "shared_preferences_android_release-1.46.aar",
          "size": 12495,
          "sha512": "684b132eb43dde898650aa1ff5103f9b5471cf02c4fa4daa7edaa28300b5db7e41fe48a5509ccf8d8a115c428be7713eb6cd4253fa13e225bf4db952240c2765",
          "sha256": "8ee935c6d786f0a37c5294615dcc9df7c189577eb5cfde2ca22f20b5e08f6acb",
          "sha1": "fc74b484eb9c726a9113fb1b77a11891a33c1d5b",
          "md5": "f71898c6d6d9b83307afa7a0c3209a68"
        }
      ]
    }
  ]
}
