{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtalkies.walletutilityplugin",
    "module": "walletutilityplugin_profile",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_profile-1.16.aar",
          "url": "walletutilityplugin_profile-1.16.aar",
          "size": 8803,
          "sha512": "368a07b708c600a021830a5a7b03f0d4c33883793cb257f9c20dedf7efbac422f3c86d1e0e3138950cf313eb41c53d7f224123dde4aa666024ffd0811c9e2a42",
          "sha256": "249dd8cb0c174f8ce31ed40f9b4788a4c69c1f32150fa549c581f6a9133a6a6e",
          "sha1": "f436f17f6098ddb5d9730e5e89b22e50c70ee28b",
          "md5": "cbe89c3a07c8009f588c8dc05222469e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "com.example.fluttershare",
          "module": "flutter_share",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent",
          "version": {
            "requires": "1.16"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_profile-1.16.aar",
          "url": "walletutilityplugin_profile-1.16.aar",
          "size": 8803,
          "sha512": "368a07b708c600a021830a5a7b03f0d4c33883793cb257f9c20dedf7efbac422f3c86d1e0e3138950cf313eb41c53d7f224123dde4aa666024ffd0811c9e2a42",
          "sha256": "249dd8cb0c174f8ce31ed40f9b4788a4c69c1f32150fa549c581f6a9133a6a6e",
          "sha1": "f436f17f6098ddb5d9730e5e89b22e50c70ee28b",
          "md5": "cbe89c3a07c8009f588c8dc05222469e"
        }
      ]
    }
  ]
}
