{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_debug",
    "version": "1.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.51.aar",
          "url": "native_exif_debug-1.51.aar",
          "size": 8146,
          "sha512": "48a418e756dbd40adff61d28233fa9a62abc879f77f84395be92f7df085fd19a2b907d032efa1d3fc806e38c2ec3baac20b26c23bc2cfa1a52f25da32fd8dc7a",
          "sha256": "0426ab659073d6429209e24458eeb807a191a45e14873858e7005b5f397645a8",
          "sha1": "72a37d5e9b584962c4b6589aa8b1cf258579bd80",
          "md5": "66cb7b9de848dde48e3ea84ce8a48087"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.51.aar",
          "url": "native_exif_debug-1.51.aar",
          "size": 8146,
          "sha512": "48a418e756dbd40adff61d28233fa9a62abc879f77f84395be92f7df085fd19a2b907d032efa1d3fc806e38c2ec3baac20b26c23bc2cfa1a52f25da32fd8dc7a",
          "sha256": "0426ab659073d6429209e24458eeb807a191a45e14873858e7005b5f397645a8",
          "sha1": "72a37d5e9b584962c4b6589aa8b1cf258579bd80",
          "md5": "66cb7b9de848dde48e3ea84ce8a48087"
        }
      ]
    }
  ]
}
