{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-1.0.aar",
          "url": "flutter_local_notifications_release-1.0.aar",
          "size": 64208,
          "sha512": "98794329a212ba67080c1b7c0c7acead24606636be76174c57be32f2a1674a87063f9d008f42ac326fb86f6436d30b66315326a82f11a079d820d24e56728e73",
          "sha256": "41b29a2a6566355aebb7bdd3c17a52760468fb4047de19931b697c538302b36b",
          "sha1": "2434f764665ec5ec153f367531af565eef7f01ae",
          "md5": "1c652d50345829fec457c855094831c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-1.0.aar",
          "url": "flutter_local_notifications_release-1.0.aar",
          "size": 64208,
          "sha512": "98794329a212ba67080c1b7c0c7acead24606636be76174c57be32f2a1674a87063f9d008f42ac326fb86f6436d30b66315326a82f11a079d820d24e56728e73",
          "sha256": "41b29a2a6566355aebb7bdd3c17a52760468fb4047de19931b697c538302b36b",
          "sha1": "2434f764665ec5ec153f367531af565eef7f01ae",
          "md5": "1c652d50345829fec457c855094831c7"
        }
      ]
    }
  ]
}
