{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.0.aar",
          "url": "fluttertoast_release-1.0.aar",
          "size": 10293,
          "sha512": "99967a32cc2df177bd93ae632e7880dee6e1bc86e8b7bd3928a82f85e537d70084379b1196aaffbfd9c3318644db143cdbfbdbcf771c6cc71a560c989364e61e",
          "sha256": "74aff3c9c7e09a87a2841927edb94724bffc6647af8af1be982b430170212168",
          "sha1": "a1cfea579850f07c5e3b3c6de998f9c146f4870c",
          "md5": "df6ee1890e09a081378e260b9215bced"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.0.aar",
          "url": "fluttertoast_release-1.0.aar",
          "size": 10293,
          "sha512": "99967a32cc2df177bd93ae632e7880dee6e1bc86e8b7bd3928a82f85e537d70084379b1196aaffbfd9c3318644db143cdbfbdbcf771c6cc71a560c989364e61e",
          "sha256": "74aff3c9c7e09a87a2841927edb94724bffc6647af8af1be982b430170212168",
          "sha1": "a1cfea579850f07c5e3b3c6de998f9c146f4870c",
          "md5": "df6ee1890e09a081378e260b9215bced"
        }
      ]
    }
  ]
}
