{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.database",
    "module": "firebase_database_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.48"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_profile-1.48.aar",
          "url": "firebase_database_profile-1.48.aar",
          "size": 29291,
          "sha512": "407138214f6d13fd7b65f979227ab8aa50883060a567ef76713857f63bfdaba8103c76c9693cf6cb11a85706fdc0c294b357daa54090236701c2d651015071f6",
          "sha256": "dd6b172bae3bc380747128b7ec70c66b09f9ad7e98b60a6f52f0ef2222059dad",
          "sha1": "7324f40a40bcd4b80c95a1d9f8d4a7a2fcdb1be6",
          "md5": "427efa0164c223d8605d9fd28fe10e3b"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.48"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_profile-1.48.aar",
          "url": "firebase_database_profile-1.48.aar",
          "size": 29291,
          "sha512": "407138214f6d13fd7b65f979227ab8aa50883060a567ef76713857f63bfdaba8103c76c9693cf6cb11a85706fdc0c294b357daa54090236701c2d651015071f6",
          "sha256": "dd6b172bae3bc380747128b7ec70c66b09f9ad7e98b60a6f52f0ef2222059dad",
          "sha1": "7324f40a40bcd4b80c95a1d9f8d4a7a2fcdb1be6",
          "md5": "427efa0164c223d8605d9fd28fe10e3b"
        }
      ]
    }
  ]
}
