{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_release",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.16.aar",
          "url": "receive_intent_release-1.16.aar",
          "size": 12901,
          "sha512": "f4b9768a4cc31b65afa568ae977585f9b623faa0a2c1fd813b09c3b3e143fb7b149efd9c85e5eca6b9ca75a78be5287167151aa954a9f853654e18ce9dd6b7bc",
          "sha256": "3d820acd10ea847aac3ab0d835eff3301491473c5d4c1d0aebec3bfb9f9d27e8",
          "sha1": "2499ef29805a5337e96a475fd285b3cf03b8dabf",
          "md5": "89b0069977643005dc58d8bfa4fbed8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.16.aar",
          "url": "receive_intent_release-1.16.aar",
          "size": 12901,
          "sha512": "f4b9768a4cc31b65afa568ae977585f9b623faa0a2c1fd813b09c3b3e143fb7b149efd9c85e5eca6b9ca75a78be5287167151aa954a9f853654e18ce9dd6b7bc",
          "sha256": "3d820acd10ea847aac3ab0d835eff3301491473c5d4c1d0aebec3bfb9f9d27e8",
          "sha1": "2499ef29805a5337e96a475fd285b3cf03b8dabf",
          "md5": "89b0069977643005dc58d8bfa4fbed8e"
        }
      ]
    }
  ]
}
