{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_release",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.47.aar",
          "url": "native_exif_release-1.47.aar",
          "size": 7870,
          "sha512": "e0b99eb5ede610a7ad2157f611ef88f385371890d170cc6e9021d8dcb945358f251c4860122e8479732ff04e535f1a9445114da7a192e8f88a2cbda1cc3630cb",
          "sha256": "d706177e6578d7c3056bac7b1f36f5697b9b420f278bfad8be216cb09adb8b67",
          "sha1": "c50d99336ab22a8ceffdb16d9ab1d4fe8a399c9d",
          "md5": "728344dc3146bfd380c28fb5b042c8da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.47.aar",
          "url": "native_exif_release-1.47.aar",
          "size": 7870,
          "sha512": "e0b99eb5ede610a7ad2157f611ef88f385371890d170cc6e9021d8dcb945358f251c4860122e8479732ff04e535f1a9445114da7a192e8f88a2cbda1cc3630cb",
          "sha256": "d706177e6578d7c3056bac7b1f36f5697b9b420f278bfad8be216cb09adb8b67",
          "sha1": "c50d99336ab22a8ceffdb16d9ab1d4fe8a399c9d",
          "md5": "728344dc3146bfd380c28fb5b042c8da"
        }
      ]
    }
  ]
}
