{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 20782,
          "sha512": "10e8829a0321c3b98d7d777b6c20f092a6e68ac270a9a841ba45a0862cc9d2821e4873fbd4c3e1da08cbf823a54a815c0df8e99ef1fe7d1045fff21fa91dd89f",
          "sha256": "ee1ede6c2a0d4ea63ffa17fae8b9f9d89abb232522270e67e5d1d66b82943230",
          "sha1": "1c894225cbe99d6da17f46075d95daef8c2acb13",
          "md5": "cf792cc3fc3da754699c8c89a1a23a9e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 20782,
          "sha512": "10e8829a0321c3b98d7d777b6c20f092a6e68ac270a9a841ba45a0862cc9d2821e4873fbd4c3e1da08cbf823a54a815c0df8e99ef1fe7d1045fff21fa91dd89f",
          "sha256": "ee1ede6c2a0d4ea63ffa17fae8b9f9d89abb232522270e67e5d1d66b82943230",
          "sha1": "1c894225cbe99d6da17f46075d95daef8c2acb13",
          "md5": "cf792cc3fc3da754699c8c89a1a23a9e"
        }
      ]
    }
  ]
}
