{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtalkies.walletutilityplugin",
    "module": "walletutilityplugin_release",
    "version": "1.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_release-1.49.aar",
          "url": "walletutilityplugin_release-1.49.aar",
          "size": 19263,
          "sha512": "183e88f78034cf88441647fa4aa6d009e5a5ca693285fe73a1361f7ba8ac147ad036b9c3083de0b4de00012d91ad1a1663028dedd00927d0b15d3023550e1c9a",
          "sha256": "9396c564540573902de2b0afb44f142256fed03efebc6adc2bad83415d19c929",
          "sha1": "366ef3ad3136ad4d23df8addaa45a68d1f72c547",
          "md5": "b82de6aca6b569103a030f9d46a60ef2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_release",
          "version": {
            "requires": "1.49"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_release",
          "version": {
            "requires": "1.49"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_release-1.49.aar",
          "url": "walletutilityplugin_release-1.49.aar",
          "size": 19263,
          "sha512": "183e88f78034cf88441647fa4aa6d009e5a5ca693285fe73a1361f7ba8ac147ad036b9c3083de0b4de00012d91ad1a1663028dedd00927d0b15d3023550e1c9a",
          "sha256": "9396c564540573902de2b0afb44f142256fed03efebc6adc2bad83415d19c929",
          "sha1": "366ef3ad3136ad4d23df8addaa45a68d1f72c547",
          "md5": "b82de6aca6b569103a030f9d46a60ef2"
        }
      ]
    }
  ]
}
