{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sidlatau.flutteremailsender",
    "module": "flutter_email_sender_debug",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_debug-1.50.aar",
          "url": "flutter_email_sender_debug-1.50.aar",
          "size": 22052,
          "sha512": "8889d725868499f10817451eb48dac154a01caaf168c419c6bbec22cbcbd820c96b250bc4fdc0e6cd502cd895cc0d3325bc0bd901476434f4eace4acb78ccaae",
          "sha256": "c007e9d8661516aaab09fe1c6cbcac30d9abf69be2d6d9b9f9ad0c9933bd5c21",
          "sha1": "78fb1332abea49fbd4a43b720b65a13838f3673f",
          "md5": "671c05ac9e36c9785df231ca1e6c043c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_debug-1.50.aar",
          "url": "flutter_email_sender_debug-1.50.aar",
          "size": 22052,
          "sha512": "8889d725868499f10817451eb48dac154a01caaf168c419c6bbec22cbcbd820c96b250bc4fdc0e6cd502cd895cc0d3325bc0bd901476434f4eace4acb78ccaae",
          "sha256": "c007e9d8661516aaab09fe1c6cbcac30d9abf69be2d6d9b9f9ad0c9933bd5c21",
          "sha1": "78fb1332abea49fbd4a43b720b65a13838f3673f",
          "md5": "671c05ac9e36c9785df231ca1e6c043c"
        }
      ]
    }
  ]
}
