{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_debug",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_debug-1.47.aar",
          "url": "camera_android_debug-1.47.aar",
          "size": 119127,
          "sha512": "23d2c55bdda377f50f174d54a40d9b6ee455a24efc228158007da530962bed64c2320ee97c7f85df626ca3a54c1fe42f7c2b4e5864f13670c1752f657a3fb2f7",
          "sha256": "d3cf84118a3ea5dd2f819f3d561678e61c5bcc2d6bd818134263a0cbd4d6dec5",
          "sha1": "727237ad1be0eb52807178756b0b5f9cd758b710",
          "md5": "bc4b07a7dc5c19edb147af63f8438a6c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.47"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_debug-1.47.aar",
          "url": "camera_android_debug-1.47.aar",
          "size": 119127,
          "sha512": "23d2c55bdda377f50f174d54a40d9b6ee455a24efc228158007da530962bed64c2320ee97c7f85df626ca3a54c1fe42f7c2b4e5864f13670c1752f657a3fb2f7",
          "sha256": "d3cf84118a3ea5dd2f819f3d561678e61c5bcc2d6bd818134263a0cbd4d6dec5",
          "sha1": "727237ad1be0eb52807178756b0b5f9cd758b710",
          "md5": "bc4b07a7dc5c19edb147af63f8438a6c"
        }
      ]
    }
  ]
}
