{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.droibit.plugins.flutter.customtabs",
    "module": "flutter_custom_tabs_release",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs_release-1.48.aar",
          "url": "flutter_custom_tabs_release-1.48.aar",
          "size": 8052,
          "sha512": "3058588ff3b7b595ded705a9cf02d60d28c99542337490183be99e7455460ed99ff13839185996a30d038c31af5eaf89a6554b8249be69eb52a51746b09bc925",
          "sha256": "964a96d9240ab329562253e2c1f5071aecd07860c92f49f3507d57f3da49ecf3",
          "sha1": "55ef49246d323f25f751b8bf578bc782b70961ae",
          "md5": "a914c5cfe0f5a82196a919b9e4277bbc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs_release-1.48.aar",
          "url": "flutter_custom_tabs_release-1.48.aar",
          "size": 8052,
          "sha512": "3058588ff3b7b595ded705a9cf02d60d28c99542337490183be99e7455460ed99ff13839185996a30d038c31af5eaf89a6554b8249be69eb52a51746b09bc925",
          "sha256": "964a96d9240ab329562253e2c1f5071aecd07860c92f49f3507d57f3da49ecf3",
          "sha1": "55ef49246d323f25f751b8bf578bc782b70961ae",
          "md5": "a914c5cfe0f5a82196a919b9e4277bbc"
        }
      ]
    }
  ]
}
