{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jhomlala.better_player.better_player",
    "module": "better_player_release",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "better_player_release-1.50.aar",
          "url": "better_player_release-1.50.aar",
          "size": 67815,
          "sha512": "0dde0ff9acc19f3cb8bb1aad41c6513ce3d445d1a60014b7ada0415f8eecf660bee66a02905da7363e72d2a689145fa4be9e1288c6a128252fcc5b066e183e3a",
          "sha256": "f4215b5fcb637799f035443cda7a456ddc5c79af67fa48a6307bfd9b62a9079b",
          "sha1": "a2a0cbac73ad3e018a982bcc4a81c1f0fa3d7e5c",
          "md5": "eb70572b35660ac19e8fad223517c55b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-mediasession",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_release",
          "version": {
            "requires": "1.50"
          }
        }
      ],
      "files": [
        {
          "name": "better_player_release-1.50.aar",
          "url": "better_player_release-1.50.aar",
          "size": 67815,
          "sha512": "0dde0ff9acc19f3cb8bb1aad41c6513ce3d445d1a60014b7ada0415f8eecf660bee66a02905da7363e72d2a689145fa4be9e1288c6a128252fcc5b066e183e3a",
          "sha256": "f4215b5fcb637799f035443cda7a456ddc5c79af67fa48a6307bfd9b62a9079b",
          "sha1": "a2a0cbac73ad3e018a982bcc4a81c1f0fa3d7e5c",
          "md5": "eb70572b35660ac19e8fad223517c55b"
        }
      ]
    }
  ]
}
