{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.38.aar",
          "url": "share_plus_profile-1.38.aar",
          "size": 23488,
          "sha512": "a38b288c46ecf076196f7f269f01c8b3a00dbef60ef2e0ad05c5778a9610a63fa9ac978c9c801e4635daa1d902cf018dfd3c9d630f41dfdcb26479438cd7a42c",
          "sha256": "5b1531adb69074413c278e69cc22362e7fee560f31847d8658b491f8ffeb2125",
          "sha1": "2e2bd6cf78ed1029a9da1b29d3ae8aa22127037c",
          "md5": "033c5ee4490a9ecc069b5cd903a8cc36"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.38.aar",
          "url": "share_plus_profile-1.38.aar",
          "size": 23488,
          "sha512": "a38b288c46ecf076196f7f269f01c8b3a00dbef60ef2e0ad05c5778a9610a63fa9ac978c9c801e4635daa1d902cf018dfd3c9d630f41dfdcb26479438cd7a42c",
          "sha256": "5b1531adb69074413c278e69cc22362e7fee560f31847d8658b491f8ffeb2125",
          "sha1": "2e2bd6cf78ed1029a9da1b29d3ae8aa22127037c",
          "md5": "033c5ee4490a9ecc069b5cd903a8cc36"
        }
      ]
    }
  ]
}
