{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.justsoft.video_thumbnail",
    "module": "video_thumbnail_debug",
    "version": "1.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_thumbnail_debug-1.51.aar",
          "url": "video_thumbnail_debug-1.51.aar",
          "size": 10574,
          "sha512": "113c9b176e764c5d1561fe599e629f333182cdeb10332c3ddbae89c305351e1218a6e9b76ca3a0277389ebececee6b53a98ee06b95e03922aae8cca9f21cfea1",
          "sha256": "b4221f04bc9654ced6f92b55e1b02ef38c8f2d333ebcdef7485c36d59f1e91ef",
          "sha1": "fd3df8222937b5fd27f633f9756d3271bc1d772e",
          "md5": "8b3aff4a407e732abd36a8f7bebb2a87"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_thumbnail_debug-1.51.aar",
          "url": "video_thumbnail_debug-1.51.aar",
          "size": 10574,
          "sha512": "113c9b176e764c5d1561fe599e629f333182cdeb10332c3ddbae89c305351e1218a6e9b76ca3a0277389ebececee6b53a98ee06b95e03922aae8cca9f21cfea1",
          "sha256": "b4221f04bc9654ced6f92b55e1b02ef38c8f2d333ebcdef7485c36d59f1e91ef",
          "sha1": "fd3df8222937b5fd27f633f9756d3271bc1d772e",
          "md5": "8b3aff4a407e732abd36a8f7bebb2a87"
        }
      ]
    }
  ]
}
