{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.0.aar",
          "url": "native_exif_debug-1.0.aar",
          "size": 8207,
          "sha512": "81adaa4b18de6f6ecc9917809b4cc6e9b629b5be2267f99589f2eeac79161e228e25b447dc5a6f298db77f024bf6ea29bfdc22f782374a4aa25811534a8edfdf",
          "sha256": "91062af73924f0075424c840dd814188633cecfd789ae75982d7a1e72453b415",
          "sha1": "1331c3ceaa2f175ef5ac0532228cc401f2fb8676",
          "md5": "b05dd5d7d3868d8cf217a5a330196e04"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.0.aar",
          "url": "native_exif_debug-1.0.aar",
          "size": 8207,
          "sha512": "81adaa4b18de6f6ecc9917809b4cc6e9b629b5be2267f99589f2eeac79161e228e25b447dc5a6f298db77f024bf6ea29bfdc22f782374a4aa25811534a8edfdf",
          "sha256": "91062af73924f0075424c840dd814188633cecfd789ae75982d7a1e72453b415",
          "sha1": "1331c3ceaa2f175ef5ac0532228cc401f2fb8676",
          "md5": "b05dd5d7d3868d8cf217a5a330196e04"
        }
      ]
    }
  ]
}
