{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mixpanel.mixpanel_flutter",
    "module": "mixpanel_flutter_release",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "mixpanel_flutter_release-1.46.aar",
          "url": "mixpanel_flutter_release-1.46.aar",
          "size": 12440,
          "sha512": "db93be3580f32090c69f5e560faa95821a62a50deff645d362dcb3d00ae3d0dbb6f68273fe6f42fe5aca35e8b1be27a1e312de3ab033d77a05d47eeb94a3c0ea",
          "sha256": "ac1da588dc4613fe50866036481206a78f83784b31765c3dbea865c9fa5d14b3",
          "sha1": "a1032b31019282c096417c45d2390ff1142b844a",
          "md5": "1afee10f67c377ea4ba355fa7440f5ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.mixpanel.android",
          "module": "mixpanel-android",
          "version": {
            "requires": "6.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mixpanel_flutter_release-1.46.aar",
          "url": "mixpanel_flutter_release-1.46.aar",
          "size": 12440,
          "sha512": "db93be3580f32090c69f5e560faa95821a62a50deff645d362dcb3d00ae3d0dbb6f68273fe6f42fe5aca35e8b1be27a1e312de3ab033d77a05d47eeb94a3c0ea",
          "sha256": "ac1da588dc4613fe50866036481206a78f83784b31765c3dbea865c9fa5d14b3",
          "sha1": "a1032b31019282c096417c45d2390ff1142b844a",
          "md5": "1afee10f67c377ea4ba355fa7440f5ec"
        }
      ]
    }
  ]
}
