{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.auth",
    "module": "firebase_auth_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth_profile-1.0.aar",
          "url": "firebase_auth_profile-1.0.aar",
          "size": 60394,
          "sha512": "1068d1a234e3906449babcdf666b1e284dd5894cdbcb192577928e814da77df188e60bcc036cac00d81edaca27320af8cb4a82f16fd34a19d12cbdd9de4c8651",
          "sha256": "03620ddf07a3eef1d04f99b94a043193591d74a559f4c347713ed687c6e35ebc",
          "sha1": "9f102b60befc3d6a7f3bb9449306147693280436",
          "md5": "813cefb95fd7ec2836a8657f74a68923"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth_profile-1.0.aar",
          "url": "firebase_auth_profile-1.0.aar",
          "size": 60394,
          "sha512": "1068d1a234e3906449babcdf666b1e284dd5894cdbcb192577928e814da77df188e60bcc036cac00d81edaca27320af8cb4a82f16fd34a19d12cbdd9de4c8651",
          "sha256": "03620ddf07a3eef1d04f99b94a043193591d74a559f4c347713ed687c6e35ebc",
          "sha1": "9f102b60befc3d6a7f3bb9449306147693280436",
          "md5": "813cefb95fd7ec2836a8657f74a68923"
        }
      ]
    }
  ]
}
