{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mixpanel.mixpanel_flutter",
    "module": "mixpanel_flutter_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "mixpanel_flutter_profile-1.48.aar",
          "url": "mixpanel_flutter_profile-1.48.aar",
          "size": 12443,
          "sha512": "e5239091b79efa5967fd701d8852b644263e3019f8a9d6f141d20ee893c1cec66dc0f3e0444789b02efa02baf91f0b82429f2aa1ddb9a145311dec38095d9c4d",
          "sha256": "f192abf6464a7f672ea92138823c2d6f8c859db23d50fda0bb43a3f1321efbe1",
          "sha1": "156fb972b782ca38183f3f3cc6d4265a5180fec1",
          "md5": "f54c9dee3a2a2d5be0d03699d38f9c2e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.mixpanel.android",
          "module": "mixpanel-android",
          "version": {
            "requires": "6.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mixpanel_flutter_profile-1.48.aar",
          "url": "mixpanel_flutter_profile-1.48.aar",
          "size": 12443,
          "sha512": "e5239091b79efa5967fd701d8852b644263e3019f8a9d6f141d20ee893c1cec66dc0f3e0444789b02efa02baf91f0b82429f2aa1ddb9a145311dec38095d9c4d",
          "sha256": "f192abf6464a7f672ea92138823c2d6f8c859db23d50fda0bb43a3f1321efbe1",
          "sha1": "156fb972b782ca38183f3f3cc6d4265a5180fec1",
          "md5": "f54c9dee3a2a2d5be0d03699d38f9c2e"
        }
      ]
    }
  ]
}
