{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtplugin.plugincheck",
    "module": "flutter_debug",
    "version": "1.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_debug",
          "version": {
            "requires": "1.51"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.51.aar",
          "url": "flutter_debug-1.51.aar",
          "size": 22407283,
          "sha512": "3053cc9bcaf54ccda52983a6949891685414d95763c425d8b2792b498faae052d8175e3667570a541441eaf336b17bb20dc8fdb1608b437338e457f209748e73",
          "sha256": "e12372b87d092e2cdc624a36e2aa8765a77f9b413369a4a126bcee4362b85205",
          "sha1": "bbe0752d9d964572ddb2783f819ff3c3e745a719",
          "md5": "ff54ae90afbfa5408cc4ac2e68db0bd3"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_debug",
          "version": {
            "requires": "1.51"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_debug",
          "version": {
            "requires": "1.51"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.51.aar",
          "url": "flutter_debug-1.51.aar",
          "size": 22407283,
          "sha512": "3053cc9bcaf54ccda52983a6949891685414d95763c425d8b2792b498faae052d8175e3667570a541441eaf336b17bb20dc8fdb1608b437338e457f209748e73",
          "sha256": "e12372b87d092e2cdc624a36e2aa8765a77f9b413369a4a126bcee4362b85205",
          "sha1": "bbe0752d9d964572ddb2783f819ff3c3e745a719",
          "md5": "ff54ae90afbfa5408cc4ac2e68db0bd3"
        }
      ]
    }
  ]
}
