{
  "formatVersion": "1.1",
  "component": {
    "group": "io.adaptant.labs.flutter_windowmanager",
    "module": "flutter_windowmanager_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_profile-1.0.aar",
          "url": "flutter_windowmanager_profile-1.0.aar",
          "size": 5548,
          "sha512": "8211edbc0aa2bbfef3d95d3225d0ed47c6a63f017d7de3f37a9affb6c3236600d82c59d57fccec397fdcc822bddf6e3011cfb5dd5f2ade1ca5a2b30c604f50f3",
          "sha256": "f03185021d6090fba451ecf922d0f43bd4910ba138246ecb3de78f6e72ddeeda",
          "sha1": "93972556b13afede7134f1a76a760afcdee81c49",
          "md5": "c0f173e7f5e31093a7a44bbd2f60f195"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_profile-1.0.aar",
          "url": "flutter_windowmanager_profile-1.0.aar",
          "size": 5548,
          "sha512": "8211edbc0aa2bbfef3d95d3225d0ed47c6a63f017d7de3f37a9affb6c3236600d82c59d57fccec397fdcc822bddf6e3011cfb5dd5f2ade1ca5a2b30c604f50f3",
          "sha256": "f03185021d6090fba451ecf922d0f43bd4910ba138246ecb3de78f6e72ddeeda",
          "sha1": "93972556b13afede7134f1a76a760afcdee81c49",
          "md5": "c0f173e7f5e31093a7a44bbd2f60f195"
        }
      ]
    }
  ]
}
