{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtplugin.plugincheck",
    "module": "flutter_release",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_release",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.46.aar",
          "url": "flutter_release-1.46.aar",
          "size": 12047321,
          "sha512": "b97119c859f90aca7869683f7c56b7150ce58cd4e5034ae1105e89272c94427f3d34065dd8f35e92c4dad89f3fa9c8c252e8fb3122bccc9fcbf8f83559adcd08",
          "sha256": "5e9dbc4d548f468e821c051ecec210f83b4094b4214282daa0a87cec1874e53d",
          "sha1": "2676f18e874f9a11e7c8c136e623d43a67148aad",
          "md5": "0701fcf217301eefaddf65135f09217e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_release",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_release",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.46.aar",
          "url": "flutter_release-1.46.aar",
          "size": 12047321,
          "sha512": "b97119c859f90aca7869683f7c56b7150ce58cd4e5034ae1105e89272c94427f3d34065dd8f35e92c4dad89f3fa9c8c252e8fb3122bccc9fcbf8f83559adcd08",
          "sha256": "5e9dbc4d548f468e821c051ecec210f83b4094b4214282daa0a87cec1874e53d",
          "sha1": "2676f18e874f9a11e7c8c136e623d43a67148aad",
          "md5": "0701fcf217301eefaddf65135f09217e"
        }
      ]
    }
  ]
}
