{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.46.aar",
          "url": "fluttertoast_release-1.46.aar",
          "size": 10230,
          "sha512": "874688b48f20c94ef4fc409d5651080596584ac19e91584b7c4d7eef757709f2cb9024ed0f92d3656e2793284c7ccc270a13d338b15595361b66534fee2ce559",
          "sha256": "cf2547c1d8bd33bf5981a5f6a08019af7ca382e448ff56408dbd05f2cbba46af",
          "sha1": "9dc6cbd502edf2f17ddbde7f83980d115f02a264",
          "md5": "f0b8f8733c4d96a05f65b6f0222ec4e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.46.aar",
          "url": "fluttertoast_release-1.46.aar",
          "size": 10230,
          "sha512": "874688b48f20c94ef4fc409d5651080596584ac19e91584b7c4d7eef757709f2cb9024ed0f92d3656e2793284c7ccc270a13d338b15595361b66534fee2ce559",
          "sha256": "cf2547c1d8bd33bf5981a5f6a08019af7ca382e448ff56408dbd05f2cbba46af",
          "sha1": "9dc6cbd502edf2f17ddbde7f83980d115f02a264",
          "md5": "f0b8f8733c4d96a05f65b6f0222ec4e5"
        }
      ]
    }
  ]
}
