{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.fluttershare",
    "module": "flutter_share",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.0-debug.aar",
          "url": "flutter_share-1.0-debug.aar",
          "size": 6197,
          "sha512": "0c5a4e2ef7359738e2efb413723c9c7ee9a85baa30d10c558a6b0473fc3f939846f40df4b5e1169648db31f029bfa34ac45f70eb4c4d37fdd1c0a7da0eee42b8",
          "sha256": "d12465ab18c8d7951791767cdae3c691c25b047d660662c9b2e08780e1b88c17",
          "sha1": "a62fd358465dcc5d1ac2be429ef8c81e47a5fca4",
          "md5": "a96cca2802a392687f00abd43c7694cf"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.0-debug.aar",
          "url": "flutter_share-1.0-debug.aar",
          "size": 6197,
          "sha512": "0c5a4e2ef7359738e2efb413723c9c7ee9a85baa30d10c558a6b0473fc3f939846f40df4b5e1169648db31f029bfa34ac45f70eb4c4d37fdd1c0a7da0eee42b8",
          "sha256": "d12465ab18c8d7951791767cdae3c691c25b047d660662c9b2e08780e1b88c17",
          "sha1": "a62fd358465dcc5d1ac2be429ef8c81e47a5fca4",
          "md5": "a96cca2802a392687f00abd43c7694cf"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.0-release.aar",
          "url": "flutter_share-1.0-release.aar",
          "size": 5942,
          "sha512": "d11be19c95c356ced202bfaacdddb14c3e540d62e4c03611b229b7802139aad1ee5569e92531c42c951ea1f3241d8d51dd375bb10651c11000170a097b76f4d5",
          "sha256": "671fa506e0c7390dd54b55680425acfff090bfd5b37fb2c8dc78b3c4b0048004",
          "sha1": "2a85400d79e66e715e71774218e55ed0f7e44a13",
          "md5": "1ebe6057996b53f82298e1b3555aacb6"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.0-release.aar",
          "url": "flutter_share-1.0-release.aar",
          "size": 5942,
          "sha512": "d11be19c95c356ced202bfaacdddb14c3e540d62e4c03611b229b7802139aad1ee5569e92531c42c951ea1f3241d8d51dd375bb10651c11000170a097b76f4d5",
          "sha256": "671fa506e0c7390dd54b55680425acfff090bfd5b37fb2c8dc78b3c4b0048004",
          "sha1": "2a85400d79e66e715e71774218e55ed0f7e44a13",
          "md5": "1ebe6057996b53f82298e1b3555aacb6"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.0-profile.aar",
          "url": "flutter_share-1.0-profile.aar",
          "size": 5943,
          "sha512": "d7e1f0e8d25fa36d21e006c33d341e901dd7553d2ea6419bf1aac4c56af55ebd4ce4a122866869289717456bb7607cfbe4c3f0969c6e8bb0ad975e64a4f902ad",
          "sha256": "902589ca3eac20d5fd4bfe95ec69df8b54c6be9091c053a61894247fda92ca4a",
          "sha1": "cfe634b6acbe2018dff088f29da0dceeb79cd13f",
          "md5": "6d2187cb0ca9427d69d2adb7f9424243"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share-1.0-profile.aar",
          "url": "flutter_share-1.0-profile.aar",
          "size": 5943,
          "sha512": "d7e1f0e8d25fa36d21e006c33d341e901dd7553d2ea6419bf1aac4c56af55ebd4ce4a122866869289717456bb7607cfbe4c3f0969c6e8bb0ad975e64a4f902ad",
          "sha256": "902589ca3eac20d5fd4bfe95ec69df8b54c6be9091c053a61894247fda92ca4a",
          "sha1": "cfe634b6acbe2018dff088f29da0dceeb79cd13f",
          "md5": "6d2187cb0ca9427d69d2adb7f9424243"
        }
      ]
    }
  ]
}
