{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.16-debug.aar",
          "url": "receive_intent-1.16-debug.aar",
          "size": 13512,
          "sha512": "c8fb119a3ba895c84a7f05803089aa24c3436a17f3ae848cd0b0e3d7f7ff718a977bb1aa6b8769891cfedb1b10071977f6093eff7ee7f44c1f3e9ede21825a3d",
          "sha256": "64b278d9f3f91442e520f2816ff5af3e25ea994860384f20fee0c9545d2cd3f3",
          "sha1": "ed600a1a141101b06aa6254e1e02dbc7cce99087",
          "md5": "0457abf83ba637e5efe80237565c7d93"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.16-debug.aar",
          "url": "receive_intent-1.16-debug.aar",
          "size": 13512,
          "sha512": "c8fb119a3ba895c84a7f05803089aa24c3436a17f3ae848cd0b0e3d7f7ff718a977bb1aa6b8769891cfedb1b10071977f6093eff7ee7f44c1f3e9ede21825a3d",
          "sha256": "64b278d9f3f91442e520f2816ff5af3e25ea994860384f20fee0c9545d2cd3f3",
          "sha1": "ed600a1a141101b06aa6254e1e02dbc7cce99087",
          "md5": "0457abf83ba637e5efe80237565c7d93"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.16-release.aar",
          "url": "receive_intent-1.16-release.aar",
          "size": 12901,
          "sha512": "f4b9768a4cc31b65afa568ae977585f9b623faa0a2c1fd813b09c3b3e143fb7b149efd9c85e5eca6b9ca75a78be5287167151aa954a9f853654e18ce9dd6b7bc",
          "sha256": "3d820acd10ea847aac3ab0d835eff3301491473c5d4c1d0aebec3bfb9f9d27e8",
          "sha1": "2499ef29805a5337e96a475fd285b3cf03b8dabf",
          "md5": "89b0069977643005dc58d8bfa4fbed8e"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.16-release.aar",
          "url": "receive_intent-1.16-release.aar",
          "size": 12901,
          "sha512": "f4b9768a4cc31b65afa568ae977585f9b623faa0a2c1fd813b09c3b3e143fb7b149efd9c85e5eca6b9ca75a78be5287167151aa954a9f853654e18ce9dd6b7bc",
          "sha256": "3d820acd10ea847aac3ab0d835eff3301491473c5d4c1d0aebec3bfb9f9d27e8",
          "sha1": "2499ef29805a5337e96a475fd285b3cf03b8dabf",
          "md5": "89b0069977643005dc58d8bfa4fbed8e"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.16-profile.aar",
          "url": "receive_intent-1.16-profile.aar",
          "size": 12901,
          "sha512": "6bcbcafb37075a907e012e3a3fd0e059f2acb698eff444165ed21cdf3a38aef09afeddfe94e66492e89b0b068dadd7044c0ba99199054fba6fab0369b2f17cf1",
          "sha256": "98e373ce5baa13f18bea6590ce1688df23c16b220ed030b17e1a9e909e27a3c2",
          "sha1": "43b3caf1fe4fa11ed00ff41eefd154411cd28cdd",
          "md5": "53ab992f322930ea7e513907e7a835ee"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent-1.16-profile.aar",
          "url": "receive_intent-1.16-profile.aar",
          "size": 12901,
          "sha512": "6bcbcafb37075a907e012e3a3fd0e059f2acb698eff444165ed21cdf3a38aef09afeddfe94e66492e89b0b068dadd7044c0ba99199054fba6fab0369b2f17cf1",
          "sha256": "98e373ce5baa13f18bea6590ce1688df23c16b220ed030b17e1a9e909e27a3c2",
          "sha1": "43b3caf1fe4fa11ed00ff41eefd154411cd28cdd",
          "md5": "53ab992f322930ea7e513907e7a835ee"
        }
      ]
    }
  ]
}
