{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.48.aar",
          "url": "flutter_secure_storage_release-1.48.aar",
          "size": 26164,
          "sha512": "5546c2060948996f271bdd2a1db76757de0cfbd655b89f9ae71ffc1a1c36e298b42a2d57e18fc6efb4878993fdf545ad0a8bd8885290b2dbe30e066c2ea611ab",
          "sha256": "f92e42bf6309b7f757d49ebc891ccd362cb39fdd011c2d9fb73aea296c35885c",
          "sha1": "a348b2db614b2edb7822dbe5a706730d417d7000",
          "md5": "a3c711061a351b8b1d25c6baffcd1a14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.48.aar",
          "url": "flutter_secure_storage_release-1.48.aar",
          "size": 26164,
          "sha512": "5546c2060948996f271bdd2a1db76757de0cfbd655b89f9ae71ffc1a1c36e298b42a2d57e18fc6efb4878993fdf545ad0a8bd8885290b2dbe30e066c2ea611ab",
          "sha256": "f92e42bf6309b7f757d49ebc891ccd362cb39fdd011c2d9fb73aea296c35885c",
          "sha1": "a348b2db614b2edb7822dbe5a706730d417d7000",
          "md5": "a3c711061a351b8b1d25c6baffcd1a14"
        }
      ]
    }
  ]
}
