{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_debug",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.47.aar",
          "url": "receive_intent_debug-1.47.aar",
          "size": 13518,
          "sha512": "a0e5e05daf130a9e0e48e15ddfac670d51d907bae9f3fb7f8ddeb947df3fa6974766b5477ce5f503f0c06a7f0e71baee038d1c689e20180722cd4db01fb968f1",
          "sha256": "7434532ed7f54d71284115aa28f466997c8e21713beddc23129b44f3c449aed6",
          "sha1": "32b98f414cdb63ba7a8a859a29d650eaed5aaf6a",
          "md5": "ad38b12722ef6a643a24b7a781945225"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.47.aar",
          "url": "receive_intent_debug-1.47.aar",
          "size": 13518,
          "sha512": "a0e5e05daf130a9e0e48e15ddfac670d51d907bae9f3fb7f8ddeb947df3fa6974766b5477ce5f503f0c06a7f0e71baee038d1c689e20180722cd4db01fb968f1",
          "sha256": "7434532ed7f54d71284115aa28f466997c8e21713beddc23129b44f3c449aed6",
          "sha1": "32b98f414cdb63ba7a8a859a29d650eaed5aaf6a",
          "md5": "ad38b12722ef6a643a24b7a781945225"
        }
      ]
    }
  ]
}
