{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebasemessaging",
    "module": "firebase_messaging_release",
    "version": "1.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.49"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_release-1.49.aar",
          "url": "firebase_messaging_release-1.49.aar",
          "size": 47977,
          "sha512": "3da83a67a6084b4640e8bf974da06f2cc077d7d5316d46fc5af79b37e2c065a83a9ceb4a661084dc756d29cd2e60ecb7dbff850743df96394c4421539b09f4cf",
          "sha256": "3c421ece4f5d3f00e7dbe0c9116c9335afa60fb4c711b162eb16c517291e57d2",
          "sha1": "8e62a58f4937324106073ea14e33875a5c4ebc03",
          "md5": "e05c187b2a64a5135dff02cbb381f6c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-iid",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.49"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_release-1.49.aar",
          "url": "firebase_messaging_release-1.49.aar",
          "size": 47977,
          "sha512": "3da83a67a6084b4640e8bf974da06f2cc077d7d5316d46fc5af79b37e2c065a83a9ceb4a661084dc756d29cd2e60ecb7dbff850743df96394c4421539b09f4cf",
          "sha256": "3c421ece4f5d3f00e7dbe0c9116c9335afa60fb4c711b162eb16c517291e57d2",
          "sha1": "8e62a58f4937324106073ea14e33875a5c4ebc03",
          "md5": "e05c187b2a64a5135dff02cbb381f6c4"
        }
      ]
    }
  ]
}
