{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android-1.38-debug.aar",
          "url": "shared_preferences_android-1.38-debug.aar",
          "size": 10425,
          "sha512": "1ee68cdd31524feb79d68fa7a917340173ed511bc551c34b7a077de7ff6ee5d01bbb41059f632c29ede0d9814118e7b40678d1a7de577fabb9c4681c7953f167",
          "sha256": "364bb5e22143fdb12ca8abe6d4df96957dfe4db8ee176ba118271d563ddfca46",
          "sha1": "cd2a75818d8904c487c730b902ade7f6e8d2fa11",
          "md5": "aa8916c881a4b33431d80ef94b3db580"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android-1.38-debug.aar",
          "url": "shared_preferences_android-1.38-debug.aar",
          "size": 10425,
          "sha512": "1ee68cdd31524feb79d68fa7a917340173ed511bc551c34b7a077de7ff6ee5d01bbb41059f632c29ede0d9814118e7b40678d1a7de577fabb9c4681c7953f167",
          "sha256": "364bb5e22143fdb12ca8abe6d4df96957dfe4db8ee176ba118271d563ddfca46",
          "sha1": "cd2a75818d8904c487c730b902ade7f6e8d2fa11",
          "md5": "aa8916c881a4b33431d80ef94b3db580"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android-1.38-release.aar",
          "url": "shared_preferences_android-1.38-release.aar",
          "size": 9983,
          "sha512": "411c410e7f90ed0da1eb69dbfb71efed98237239e1f8969bd09f1949ff03db3c0b89241b467e07aec3614764675d12b3ba427c74d43cc664a5f2597c9fbfcbea",
          "sha256": "bbf4898ddc2452029f20a9a4b80f2b830686fe60caf3cae0f490300e8313c06a",
          "sha1": "16807cdacd8182cbd2b29426126dd7c586391602",
          "md5": "ac8552efdecec77320161ed0389bab30"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android-1.38-release.aar",
          "url": "shared_preferences_android-1.38-release.aar",
          "size": 9983,
          "sha512": "411c410e7f90ed0da1eb69dbfb71efed98237239e1f8969bd09f1949ff03db3c0b89241b467e07aec3614764675d12b3ba427c74d43cc664a5f2597c9fbfcbea",
          "sha256": "bbf4898ddc2452029f20a9a4b80f2b830686fe60caf3cae0f490300e8313c06a",
          "sha1": "16807cdacd8182cbd2b29426126dd7c586391602",
          "md5": "ac8552efdecec77320161ed0389bab30"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android-1.38-profile.aar",
          "url": "shared_preferences_android-1.38-profile.aar",
          "size": 9987,
          "sha512": "92f9c6e0783e7830670f060b5f141c6daad100ccb8a8ca1887f8f4dd14a048a1eaa7f63180bcccbb13d81ef05aea7a42f88e30801815f3f77af99d10b71206e0",
          "sha256": "79d59763e9326b4f6e0afe281a05a151e42fba0832c1bb1a1d0cd0235dfe9d9a",
          "sha1": "cb8437857c3cb32b39bdfb8dc388ef0b14465eac",
          "md5": "a326b6f124db0bf94953eed045b025c9"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android-1.38-profile.aar",
          "url": "shared_preferences_android-1.38-profile.aar",
          "size": 9987,
          "sha512": "92f9c6e0783e7830670f060b5f141c6daad100ccb8a8ca1887f8f4dd14a048a1eaa7f63180bcccbb13d81ef05aea7a42f88e30801815f3f77af99d10b71206e0",
          "sha256": "79d59763e9326b4f6e0afe281a05a151e42fba0832c1bb1a1d0cd0235dfe9d9a",
          "sha1": "cb8437857c3cb32b39bdfb8dc388ef0b14465eac",
          "md5": "a326b6f124db0bf94953eed045b025c9"
        }
      ]
    }
  ]
}
