{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.48.aar",
          "url": "local_auth_android_profile-1.48.aar",
          "size": 41776,
          "sha512": "27564ca60787c7a10a085597fe4d6f197ef64a35930becb4d8d993bdb0977d2ec1dd6dd5d6309db086a4d384861b1beae4fc9cf46939ec8ba5c6bd3d7b9f238c",
          "sha256": "75c1f799e0747796dae7af09f428275c08c3fd38c24f05a1e7f9d01da952147a",
          "sha1": "e45b148a9ff09fe5831e4414640d1d88ff639ae3",
          "md5": "c1e702aa4dba88404a74e77bab725083"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.48"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.48.aar",
          "url": "local_auth_android_profile-1.48.aar",
          "size": 41776,
          "sha512": "27564ca60787c7a10a085597fe4d6f197ef64a35930becb4d8d993bdb0977d2ec1dd6dd5d6309db086a4d384861b1beae4fc9cf46939ec8ba5c6bd3d7b9f238c",
          "sha256": "75c1f799e0747796dae7af09f428275c08c3fd38c24f05a1e7f9d01da952147a",
          "sha1": "e45b148a9ff09fe5831e4414640d1d88ff639ae3",
          "md5": "c1e702aa4dba88404a74e77bab725083"
        }
      ]
    }
  ]
}
