{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_debug",
    "version": "1.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.51.aar",
          "url": "flutter_local_notifications_debug-1.51.aar",
          "size": 69155,
          "sha512": "ecec837cddb7c747295d084012d978b518107960fdee2da800d5c7aeff8fa951b8dbad11e0d55337c6d6a150223360c53bb30f50b24323c71364c085ac4df777",
          "sha256": "5c3cf840425cb47a7f2b755a308b6c4d36b33fa99bc2531cb2214800ead0b99d",
          "sha1": "1a2a73cc37ff8f70a273b16320c0f4e18a18aa81",
          "md5": "cc003b0fe41fc3771d2042b448f1fad0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.51.aar",
          "url": "flutter_local_notifications_debug-1.51.aar",
          "size": 69155,
          "sha512": "ecec837cddb7c747295d084012d978b518107960fdee2da800d5c7aeff8fa951b8dbad11e0d55337c6d6a150223360c53bb30f50b24323c71364c085ac4df777",
          "sha256": "5c3cf840425cb47a7f2b755a308b6c4d36b33fa99bc2531cb2214800ead0b99d",
          "sha1": "1a2a73cc37ff8f70a273b16320c0f4e18a18aa81",
          "md5": "cc003b0fe41fc3771d2042b448f1fad0"
        }
      ]
    }
  ]
}
