{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_debug",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-1.47.aar",
          "url": "sqflite_debug-1.47.aar",
          "size": 44012,
          "sha512": "720108a6e4a0ec91c6a4eff1d77ffff9112a9a91114e8ef98d331c192fb04c050b4136ef268a8d0775833bc9a87b182af70b53732234d50d5d1b7626e27a5508",
          "sha256": "cb52a76ea247256ed1844177c7d118bdf095034a57fa573fed6b55b90b60ceea",
          "sha1": "e794d2fdf030d0d437d1864b43e9c8b423a54171",
          "md5": "39ed48b6690df97c6b6148c2dc8b9898"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-1.47.aar",
          "url": "sqflite_debug-1.47.aar",
          "size": 44012,
          "sha512": "720108a6e4a0ec91c6a4eff1d77ffff9112a9a91114e8ef98d331c192fb04c050b4136ef268a8d0775833bc9a87b182af70b53732234d50d5d1b7626e27a5508",
          "sha256": "cb52a76ea247256ed1844177c7d118bdf095034a57fa573fed6b55b90b60ceea",
          "sha1": "e794d2fdf030d0d437d1864b43e9c8b423a54171",
          "md5": "39ed48b6690df97c6b6148c2dc8b9898"
        }
      ]
    }
  ]
}
