{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_release",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.50.aar",
          "url": "receive_intent_release-1.50.aar",
          "size": 12871,
          "sha512": "fae06e494e08ddb84a3e5d2442f2beb16d44b86deb370da3c12089521d3bef42d7849876901cba105a26ef71382e1d5c04b0389b8858a0892394489494d30522",
          "sha256": "af9a7a61e8f903ab9eeb1dc1e6e4062971ea83d913077f890c11e0d15c1214db",
          "sha1": "b78b7cd0d1f45f2a4494fb1786edab813345355f",
          "md5": "555e46f9971b4298356d673ef748fc28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_release-1.50.aar",
          "url": "receive_intent_release-1.50.aar",
          "size": 12871,
          "sha512": "fae06e494e08ddb84a3e5d2442f2beb16d44b86deb370da3c12089521d3bef42d7849876901cba105a26ef71382e1d5c04b0389b8858a0892394489494d30522",
          "sha256": "af9a7a61e8f903ab9eeb1dc1e6e4062971ea83d913077f890c11e0d15c1214db",
          "sha1": "b78b7cd0d1f45f2a4494fb1786edab813345355f",
          "md5": "555e46f9971b4298356d673ef748fc28"
        }
      ]
    }
  ]
}
