{
  "formatVersion": "1.1",
  "component": {
    "group": "io.adaptant.labs.flutter_windowmanager",
    "module": "flutter_windowmanager_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_debug-1.0.aar",
          "url": "flutter_windowmanager_debug-1.0.aar",
          "size": 5804,
          "sha512": "2ae1a919b501f6f2d968523cf4567711b689b6ea1dc927e8ab4478514a18b6b41440f2c449f095d79cb38f02c012e016af25021886504aeda82f675c1fb2f9cc",
          "sha256": "9db93e8db611884c9cbf73ca5b0707d6d69bfc5a54bc057ee7b84757b8064d40",
          "sha1": "2cf0ec5a1db6282aa4b72de7c2ac2864728de6fa",
          "md5": "4067e69af462dcc3befb30f87019f0bf"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_debug-1.0.aar",
          "url": "flutter_windowmanager_debug-1.0.aar",
          "size": 5804,
          "sha512": "2ae1a919b501f6f2d968523cf4567711b689b6ea1dc927e8ab4478514a18b6b41440f2c449f095d79cb38f02c012e016af25021886504aeda82f675c1fb2f9cc",
          "sha256": "9db93e8db611884c9cbf73ca5b0707d6d69bfc5a54bc057ee7b84757b8064d40",
          "sha1": "2cf0ec5a1db6282aa4b72de7c2ac2864728de6fa",
          "md5": "4067e69af462dcc3befb30f87019f0bf"
        }
      ]
    }
  ]
}
