{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.38-debug.aar",
          "url": "path_provider_android-1.38-debug.aar",
          "size": 12982,
          "sha512": "8a20d025fa8bac6549e4f193c3d8eabf66d02a40ae16e7aec31e09a5227c75ff443a685ac101bac8638aba33b3fe74ed3371888148d58b370d21a15a60be5f13",
          "sha256": "5acf418f0fba4bdf397ee73efb653e66eca0cacdacf86c36fa131b96e6bbce99",
          "sha1": "94c40bfb31f0dbfae67d972128e639f9c8d127f3",
          "md5": "8c45fe5c2d886d5978254238eef8ea22"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.38-debug.aar",
          "url": "path_provider_android-1.38-debug.aar",
          "size": 12982,
          "sha512": "8a20d025fa8bac6549e4f193c3d8eabf66d02a40ae16e7aec31e09a5227c75ff443a685ac101bac8638aba33b3fe74ed3371888148d58b370d21a15a60be5f13",
          "sha256": "5acf418f0fba4bdf397ee73efb653e66eca0cacdacf86c36fa131b96e6bbce99",
          "sha1": "94c40bfb31f0dbfae67d972128e639f9c8d127f3",
          "md5": "8c45fe5c2d886d5978254238eef8ea22"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.38-release.aar",
          "url": "path_provider_android-1.38-release.aar",
          "size": 12398,
          "sha512": "3e5edcfed68032f5d9516a1685015e517e3f7d10c8157b54f6065e26bb69cfb24942e73f9fbd010200202f9e35e64832c1183c4804a477653d1823d8eb7f0152",
          "sha256": "b5b9faac1039ed7ef23748428b2c66790dbf455179f586c7e7f687470002e365",
          "sha1": "a33f4416ff015a210d29a52906c0c264fb26a308",
          "md5": "b96f0c8914cf2cc449c09df31527614e"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.38-release.aar",
          "url": "path_provider_android-1.38-release.aar",
          "size": 12398,
          "sha512": "3e5edcfed68032f5d9516a1685015e517e3f7d10c8157b54f6065e26bb69cfb24942e73f9fbd010200202f9e35e64832c1183c4804a477653d1823d8eb7f0152",
          "sha256": "b5b9faac1039ed7ef23748428b2c66790dbf455179f586c7e7f687470002e365",
          "sha1": "a33f4416ff015a210d29a52906c0c264fb26a308",
          "md5": "b96f0c8914cf2cc449c09df31527614e"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.38-profile.aar",
          "url": "path_provider_android-1.38-profile.aar",
          "size": 12401,
          "sha512": "f1e1a054af039e9e38cbc84603ab1de52dfe20efc307a5dd47812897bdde7abef894b6a4371873c2fd453c997f184f77ab5128d8ec477594fe1f23313ba22d78",
          "sha256": "ef1fce8ae3d814c225aa7ffe15dcd6fe1c2493d76f593ac696049988774fcdc7",
          "sha1": "ead7027efaf5278306d58b8151c3e68c49b7fdf5",
          "md5": "1c2c2825d010913a41cb195f4fcf9653"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android-1.38-profile.aar",
          "url": "path_provider_android-1.38-profile.aar",
          "size": 12401,
          "sha512": "f1e1a054af039e9e38cbc84603ab1de52dfe20efc307a5dd47812897bdde7abef894b6a4371873c2fd453c997f184f77ab5128d8ec477594fe1f23313ba22d78",
          "sha256": "ef1fce8ae3d814c225aa7ffe15dcd6fe1c2493d76f593ac696049988774fcdc7",
          "sha1": "ead7027efaf5278306d58b8151c3e68c49b7fdf5",
          "md5": "1c2c2825d010913a41cb195f4fcf9653"
        }
      ]
    }
  ]
}
