{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtalkies.walletutilityplugin",
    "module": "walletutilityplugin_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_debug-1.0.aar",
          "url": "walletutilityplugin_debug-1.0.aar",
          "size": 19410,
          "sha512": "e4155f394ce372fc79d00445177697845eed6552a5ca2a11ff97ea3ec0a5fac5c0cca0e0b0eba380a164d01656fd4275dc2ff57f56c4dbd98a44dad8304c8433",
          "sha256": "75f379b924c15f93c99c2596b6cd1de16cb467133f9881e6c7625ad367ef542f",
          "sha1": "8a4e0d5b71776abcbdebeb541be8499523568eb9",
          "md5": "1ee70c44b13ce5846f2636cb65dc01e2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_debug-1.0.aar",
          "url": "walletutilityplugin_debug-1.0.aar",
          "size": 19410,
          "sha512": "e4155f394ce372fc79d00445177697845eed6552a5ca2a11ff97ea3ec0a5fac5c0cca0e0b0eba380a164d01656fd4275dc2ff57f56c4dbd98a44dad8304c8433",
          "sha256": "75f379b924c15f93c99c2596b6cd1de16cb467133f9881e6c7625ad367ef542f",
          "sha1": "8a4e0d5b71776abcbdebeb541be8499523568eb9",
          "md5": "1ee70c44b13ce5846f2636cb65dc01e2"
        }
      ]
    }
  ]
}
