{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtalkies.walletutilityplugin",
    "module": "walletutilityplugin_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_debug-1.0.aar",
          "url": "walletutilityplugin_debug-1.0.aar",
          "size": 5570,
          "sha512": "199770d99925f68ac015aae408f6c8c0dafc08025bba2e12ff499e21f9e756b18db6981c965b72921ed56949597fc754cc9796e0c1e96cbf233a0ff7c99727e1",
          "sha256": "f8d06154ee4b497e27b9dc55029751bd44f8bbd6089d0fbb66462985b7d2f85f",
          "sha1": "414e958a3e62498fe85590efb2d58a5faa327bff",
          "md5": "879c0ed520025e7b7432acfbbbeb6c06"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_debug-1.0.aar",
          "url": "walletutilityplugin_debug-1.0.aar",
          "size": 5570,
          "sha512": "199770d99925f68ac015aae408f6c8c0dafc08025bba2e12ff499e21f9e756b18db6981c965b72921ed56949597fc754cc9796e0c1e96cbf233a0ff7c99727e1",
          "sha256": "f8d06154ee4b497e27b9dc55029751bd44f8bbd6089d0fbb66462985b7d2f85f",
          "sha1": "414e958a3e62498fe85590efb2d58a5faa327bff",
          "md5": "879c0ed520025e7b7432acfbbbeb6c06"
        }
      ]
    }
  ]
}
