{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.auth",
    "module": "firebase_auth_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth_release-1.0.aar",
          "url": "firebase_auth_release-1.0.aar",
          "size": 60391,
          "sha512": "59b1640c66dc7825cb659dfd4d3e7578660298249e8b729103442e3cf0203b4091c41f90e92df23f4cd6b166d41f53eaefe177c4a4d1d2af164d4ab03cd91e4d",
          "sha256": "1a1462a6323795f968fd834b60c34e4748ab3263759cbae2dff1851b3ea05142",
          "sha1": "dfa8f3e937effb53af3d695a0fe34b2804a70cea",
          "md5": "87c0bdb34413e808990e4c8dc583d831"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth_release-1.0.aar",
          "url": "firebase_auth_release-1.0.aar",
          "size": 60391,
          "sha512": "59b1640c66dc7825cb659dfd4d3e7578660298249e8b729103442e3cf0203b4091c41f90e92df23f4cd6b166d41f53eaefe177c4a4d1d2af164d4ab03cd91e4d",
          "sha256": "1a1462a6323795f968fd834b60c34e4748ab3263759cbae2dff1851b3ea05142",
          "sha1": "dfa8f3e937effb53af3d695a0fe34b2804a70cea",
          "md5": "87c0bdb34413e808990e4c8dc583d831"
        }
      ]
    }
  ]
}
