{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_profile",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_profile-1.46.aar",
          "url": "sqflite_profile-1.46.aar",
          "size": 42023,
          "sha512": "9b1e629d929bfb3ed96fce4741e64ab0ca1791751f26b70ba4283265b2e584d2321ad63a4a2030723173513b1320b157600428c06317fd25d1b2c58ea3b770c4",
          "sha256": "77b12ccac695a80bfc81ff739f24228d8da5a7cb3e85112392cd3b645bbeb40b",
          "sha1": "2fc34ba98c96401d564a173bf57e462ec0218d1d",
          "md5": "1d798fffaea8fcf7d5f9804879bdbef9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_profile-1.46.aar",
          "url": "sqflite_profile-1.46.aar",
          "size": 42023,
          "sha512": "9b1e629d929bfb3ed96fce4741e64ab0ca1791751f26b70ba4283265b2e584d2321ad63a4a2030723173513b1320b157600428c06317fd25d1b2c58ea3b770c4",
          "sha256": "77b12ccac695a80bfc81ff739f24228d8da5a7cb3e85112392cd3b645bbeb40b",
          "sha1": "2fc34ba98c96401d564a173bf57e462ec0218d1d",
          "md5": "1d798fffaea8fcf7d5f9804879bdbef9"
        }
      ]
    }
  ]
}
