{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtalkies.walletutilityplugin",
    "module": "walletutilityplugin",
    "version": "1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin-1.17-debug.aar",
          "url": "walletutilityplugin-1.17-debug.aar",
          "size": 8952,
          "sha512": "3cb7b736b8f1906f8fa10bd15578437e61c5b9d85bbdd05e1e04305e2f4582edd08248324613db25ba320f5f9c90a09bce7a421e25eb3b92105b7089ca91c87c",
          "sha256": "6014cdade67d7c1f735514924841c43afd11916fddcfd29442c6b82f862ffdbf",
          "sha1": "b5e7298fd0d87a70e5b0cee72a944bc271e37642",
          "md5": "2e10b9c8d4f939f08e73d6e2ecdcbbc9"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.example.fluttershare",
          "module": "flutter_share",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent",
          "version": {
            "requires": "1.17"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin-1.17-debug.aar",
          "url": "walletutilityplugin-1.17-debug.aar",
          "size": 8952,
          "sha512": "3cb7b736b8f1906f8fa10bd15578437e61c5b9d85bbdd05e1e04305e2f4582edd08248324613db25ba320f5f9c90a09bce7a421e25eb3b92105b7089ca91c87c",
          "sha256": "6014cdade67d7c1f735514924841c43afd11916fddcfd29442c6b82f862ffdbf",
          "sha1": "b5e7298fd0d87a70e5b0cee72a944bc271e37642",
          "md5": "2e10b9c8d4f939f08e73d6e2ecdcbbc9"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin-1.17-release.aar",
          "url": "walletutilityplugin-1.17-release.aar",
          "size": 8804,
          "sha512": "604a5f161199c0e76292ee430e70c91f0aebd164c25ca7063a751d4948dae9cd02c30bc41cbce71550f571f311b9ebbcb9edd9b383a6bc8b0c71d781ad88b714",
          "sha256": "e49e15c8d62219184a1618f0aa7fc53167408cb05637ada02c6dbd495f06d105",
          "sha1": "49a275c764446973b697d7e28541a27464ce86cb",
          "md5": "711172bc2a28ca901702cbf1cf3175e9"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.example.fluttershare",
          "module": "flutter_share",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent",
          "version": {
            "requires": "1.17"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin-1.17-release.aar",
          "url": "walletutilityplugin-1.17-release.aar",
          "size": 8804,
          "sha512": "604a5f161199c0e76292ee430e70c91f0aebd164c25ca7063a751d4948dae9cd02c30bc41cbce71550f571f311b9ebbcb9edd9b383a6bc8b0c71d781ad88b714",
          "sha256": "e49e15c8d62219184a1618f0aa7fc53167408cb05637ada02c6dbd495f06d105",
          "sha1": "49a275c764446973b697d7e28541a27464ce86cb",
          "md5": "711172bc2a28ca901702cbf1cf3175e9"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin-1.17-profile.aar",
          "url": "walletutilityplugin-1.17-profile.aar",
          "size": 8803,
          "sha512": "368a07b708c600a021830a5a7b03f0d4c33883793cb257f9c20dedf7efbac422f3c86d1e0e3138950cf313eb41c53d7f224123dde4aa666024ffd0811c9e2a42",
          "sha256": "249dd8cb0c174f8ce31ed40f9b4788a4c69c1f32150fa549c581f6a9133a6a6e",
          "sha1": "f436f17f6098ddb5d9730e5e89b22e50c70ee28b",
          "md5": "cbe89c3a07c8009f588c8dc05222469e"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.example.fluttershare",
          "module": "flutter_share",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent",
          "version": {
            "requires": "1.17"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin-1.17-profile.aar",
          "url": "walletutilityplugin-1.17-profile.aar",
          "size": 8803,
          "sha512": "368a07b708c600a021830a5a7b03f0d4c33883793cb257f9c20dedf7efbac422f3c86d1e0e3138950cf313eb41c53d7f224123dde4aa666024ffd0811c9e2a42",
          "sha256": "249dd8cb0c174f8ce31ed40f9b4788a4c69c1f32150fa549c581f6a9133a6a6e",
          "sha1": "f436f17f6098ddb5d9730e5e89b22e50c70ee28b",
          "md5": "cbe89c3a07c8009f588c8dc05222469e"
        }
      ]
    }
  ]
}
