{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_profile-1.0.aar",
          "url": "native_exif_profile-1.0.aar",
          "size": 7923,
          "sha512": "f1a6532bed777a2cfdaaaf7e2680579822d586d74b413f74050b23862019c4fcdff2ba633377dd3316fd321a04fef7789c058ee00f7a2d8e7e739def08664bd4",
          "sha256": "f43a48734c368f71cf3f6cd0d1fafe05f5f483e31c63c77fac72674320d56575",
          "sha1": "dbf93b584625f98d175d9b37503f7c931055fe6c",
          "md5": "5c61fb7fa5a48949b118c7ec4a9cc321"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_profile-1.0.aar",
          "url": "native_exif_profile-1.0.aar",
          "size": 7923,
          "sha512": "f1a6532bed777a2cfdaaaf7e2680579822d586d74b413f74050b23862019c4fcdff2ba633377dd3316fd321a04fef7789c058ee00f7a2d8e7e739def08664bd4",
          "sha256": "f43a48734c368f71cf3f6cd0d1fafe05f5f483e31c63c77fac72674320d56575",
          "sha1": "dbf93b584625f98d175d9b37503f7c931055fe6c",
          "md5": "5c61fb7fa5a48949b118c7ec4a9cc321"
        }
      ]
    }
  ]
}
