{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_profile-1.0.aar",
          "url": "native_exif_profile-1.0.aar",
          "size": 7920,
          "sha512": "91a5e00944109913a4708c777455901b9f2ac44df47ba467fdc42d4d2f1e8e7fa61b03c95cf6ff4a5eee19880a80e04b0824aada0a1dfd3cb24610c1097d4d97",
          "sha256": "51ebac8e0fff9acdd93d2d46c81e495583db95981d53dfd830be5feac6775724",
          "sha1": "bf457701e8b4a0b8b1ba53896875d6d04436a9a4",
          "md5": "d0a1a3dd7964d959c02ec4204d2c8e85"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_profile-1.0.aar",
          "url": "native_exif_profile-1.0.aar",
          "size": 7920,
          "sha512": "91a5e00944109913a4708c777455901b9f2ac44df47ba467fdc42d4d2f1e8e7fa61b03c95cf6ff4a5eee19880a80e04b0824aada0a1dfd3cb24610c1097d4d97",
          "sha256": "51ebac8e0fff9acdd93d2d46c81e495583db95981d53dfd830be5feac6775724",
          "sha1": "bf457701e8b4a0b8b1ba53896875d6d04436a9a4",
          "md5": "d0a1a3dd7964d959c02ec4204d2c8e85"
        }
      ]
    }
  ]
}
