{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_profile-1.0.aar",
          "url": "native_exif_profile-1.0.aar",
          "size": 7873,
          "sha512": "5258ee4b946e872dc813b4273d0c045b9e05dbb391505a4d2400cb6595ea166125484b91a9a2b914746c8ecce448f910662fd35c5743181c3f96ffa05cf907b8",
          "sha256": "6ef2e0f19311a97f03202bf488a6ddaed2fc918e392a1c68bd845b610953c64d",
          "sha1": "67a3437b95182420d4bb129441d51144602c5c80",
          "md5": "e60b4b63e41b75941514ad3c2f0fd30d"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_profile-1.0.aar",
          "url": "native_exif_profile-1.0.aar",
          "size": 7873,
          "sha512": "5258ee4b946e872dc813b4273d0c045b9e05dbb391505a4d2400cb6595ea166125484b91a9a2b914746c8ecce448f910662fd35c5743181c3f96ffa05cf907b8",
          "sha256": "6ef2e0f19311a97f03202bf488a6ddaed2fc918e392a1c68bd845b610953c64d",
          "sha1": "67a3437b95182420d4bb129441d51144602c5c80",
          "md5": "e60b4b63e41b75941514ad3c2f0fd30d"
        }
      ]
    }
  ]
}
