{
  "formatVersion": "1.1",
  "component": {
    "group": "creativemaybeno.wakelock",
    "module": "wakelock",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock-1.16-debug.aar",
          "url": "wakelock-1.16-debug.aar",
          "size": 11742,
          "sha512": "65c559e729433f61ec38a789e7065895fcbc322db4029c7893b799e5cb74e10fa5da899ae76f96f4cdfb971a1b804114160c8a69f0545f84b898fab23934a849",
          "sha256": "b625cdd71253cea2dd519d7ad73080e97048870f2e7f05f62ddd49fa7d8ae06c",
          "sha1": "572abe46e5c38bb44db29820861ee041e424bc1a",
          "md5": "59975d4c4a986aeeb7e6ee6dc9678c0d"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock-1.16-debug.aar",
          "url": "wakelock-1.16-debug.aar",
          "size": 11742,
          "sha512": "65c559e729433f61ec38a789e7065895fcbc322db4029c7893b799e5cb74e10fa5da899ae76f96f4cdfb971a1b804114160c8a69f0545f84b898fab23934a849",
          "sha256": "b625cdd71253cea2dd519d7ad73080e97048870f2e7f05f62ddd49fa7d8ae06c",
          "sha1": "572abe46e5c38bb44db29820861ee041e424bc1a",
          "md5": "59975d4c4a986aeeb7e6ee6dc9678c0d"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock-1.16-release.aar",
          "url": "wakelock-1.16-release.aar",
          "size": 11327,
          "sha512": "809296263e66d86bfaa46ea6685e9bc5bd8a9a881cec2e7cdccc6f51f621d6764d299cfbb783c6662d3abf4aa83af79b7065ab15a2bf8ab123036f07a08eabd1",
          "sha256": "621275f00903743727b22ed3e40f84ea4f2749e9570e74753f36a89736e592ac",
          "sha1": "d10d3da563fac7adafb4df46ceb110889d1905f3",
          "md5": "a770b4f4141b6a00e3a56787871f5c72"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock-1.16-release.aar",
          "url": "wakelock-1.16-release.aar",
          "size": 11327,
          "sha512": "809296263e66d86bfaa46ea6685e9bc5bd8a9a881cec2e7cdccc6f51f621d6764d299cfbb783c6662d3abf4aa83af79b7065ab15a2bf8ab123036f07a08eabd1",
          "sha256": "621275f00903743727b22ed3e40f84ea4f2749e9570e74753f36a89736e592ac",
          "sha1": "d10d3da563fac7adafb4df46ceb110889d1905f3",
          "md5": "a770b4f4141b6a00e3a56787871f5c72"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock-1.16-profile.aar",
          "url": "wakelock-1.16-profile.aar",
          "size": 11327,
          "sha512": "781f1aa443b95e4a587d2bca158f526acbf80188f312179498e2d317d47f1eba485d67352f1a04d96b1aa9764235c7713512110233e48bf31533e3e8cc0b573e",
          "sha256": "13d0d553d32e1914cfe07058b50dec1dca85a972e3b60147b3ad6bb8a7c10e03",
          "sha1": "8a0b73d9c72ffef549da25ce54609e8870aeeffb",
          "md5": "e08a7802f5af78c7d929bd3779e022ca"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock-1.16-profile.aar",
          "url": "wakelock-1.16-profile.aar",
          "size": 11327,
          "sha512": "781f1aa443b95e4a587d2bca158f526acbf80188f312179498e2d317d47f1eba485d67352f1a04d96b1aa9764235c7713512110233e48bf31533e3e8cc0b573e",
          "sha256": "13d0d553d32e1914cfe07058b50dec1dca85a972e3b60147b3ad6bb8a7c10e03",
          "sha1": "8a0b73d9c72ffef549da25ce54609e8870aeeffb",
          "md5": "e08a7802f5af78c7d929bd3779e022ca"
        }
      ]
    }
  ]
}
