{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-debug.aar",
          "url": "native_exif-1.0-debug.aar",
          "size": 8204,
          "sha512": "60b855c96a7f4cf0fcc1008042fb4c74d5ac1e0e520686b06de44baff6a911c89ae0474684dba98c83cbe9cba9a99fdc3e2dc61f2d79c5153925db4f06b8d383",
          "sha256": "3c168b7e67ea4f33e9edcef408af137bbbc76b90f98b59435b263099a64871e9",
          "sha1": "b47ce55ab269c925328e6b7ef8d1d801c4363b46",
          "md5": "6ed498b328e00cf20dc93630c6cf5c10"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-debug.aar",
          "url": "native_exif-1.0-debug.aar",
          "size": 8204,
          "sha512": "60b855c96a7f4cf0fcc1008042fb4c74d5ac1e0e520686b06de44baff6a911c89ae0474684dba98c83cbe9cba9a99fdc3e2dc61f2d79c5153925db4f06b8d383",
          "sha256": "3c168b7e67ea4f33e9edcef408af137bbbc76b90f98b59435b263099a64871e9",
          "sha1": "b47ce55ab269c925328e6b7ef8d1d801c4363b46",
          "md5": "6ed498b328e00cf20dc93630c6cf5c10"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-release.aar",
          "url": "native_exif-1.0-release.aar",
          "size": 7918,
          "sha512": "460c608bc65fcacd606369834253888a9383b80d5def11319c0be0ccbb35ec606ec43a3a23eaf083eceaf648b309ae29c0d8000febd013ab3835da0cd672e2a7",
          "sha256": "459fff2158bda2917052a45277084a138d616a9af1c9fffb566750424f5f250f",
          "sha1": "7abd7e602fd96059cf7e2b91d3dc6d27edba890e",
          "md5": "14d92198c6e0abd6a3a7f4e6c8bb52e5"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-release.aar",
          "url": "native_exif-1.0-release.aar",
          "size": 7918,
          "sha512": "460c608bc65fcacd606369834253888a9383b80d5def11319c0be0ccbb35ec606ec43a3a23eaf083eceaf648b309ae29c0d8000febd013ab3835da0cd672e2a7",
          "sha256": "459fff2158bda2917052a45277084a138d616a9af1c9fffb566750424f5f250f",
          "sha1": "7abd7e602fd96059cf7e2b91d3dc6d27edba890e",
          "md5": "14d92198c6e0abd6a3a7f4e6c8bb52e5"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-profile.aar",
          "url": "native_exif-1.0-profile.aar",
          "size": 7920,
          "sha512": "91a5e00944109913a4708c777455901b9f2ac44df47ba467fdc42d4d2f1e8e7fa61b03c95cf6ff4a5eee19880a80e04b0824aada0a1dfd3cb24610c1097d4d97",
          "sha256": "51ebac8e0fff9acdd93d2d46c81e495583db95981d53dfd830be5feac6775724",
          "sha1": "bf457701e8b4a0b8b1ba53896875d6d04436a9a4",
          "md5": "d0a1a3dd7964d959c02ec4204d2c8e85"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-profile.aar",
          "url": "native_exif-1.0-profile.aar",
          "size": 7920,
          "sha512": "91a5e00944109913a4708c777455901b9f2ac44df47ba467fdc42d4d2f1e8e7fa61b03c95cf6ff4a5eee19880a80e04b0824aada0a1dfd3cb24610c1097d4d97",
          "sha256": "51ebac8e0fff9acdd93d2d46c81e495583db95981d53dfd830be5feac6775724",
          "sha1": "bf457701e8b4a0b8b1ba53896875d6d04436a9a4",
          "md5": "d0a1a3dd7964d959c02ec4204d2c8e85"
        }
      ]
    }
  ]
}
