{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-debug.aar",
          "url": "native_exif-1.0-debug.aar",
          "size": 8148,
          "sha512": "1cec7271dbc28af631217e6698f77b7ed236b71b22f322e49b328ee2f88b99e6c0fdb0b2abbb87c3939293bfa10555c5fe87e6f64c9e4bfc48e551e6e2c35a7c",
          "sha256": "e730124757028d830eaacb057ebda3da62e7fe7c083e714a22808d5308c0f687",
          "sha1": "f9fa3a9a5f0c0393d77bc259ae233433ec910b0e",
          "md5": "96e242dbe22429b69cb17317419809f7"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-debug.aar",
          "url": "native_exif-1.0-debug.aar",
          "size": 8148,
          "sha512": "1cec7271dbc28af631217e6698f77b7ed236b71b22f322e49b328ee2f88b99e6c0fdb0b2abbb87c3939293bfa10555c5fe87e6f64c9e4bfc48e551e6e2c35a7c",
          "sha256": "e730124757028d830eaacb057ebda3da62e7fe7c083e714a22808d5308c0f687",
          "sha1": "f9fa3a9a5f0c0393d77bc259ae233433ec910b0e",
          "md5": "96e242dbe22429b69cb17317419809f7"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-release.aar",
          "url": "native_exif-1.0-release.aar",
          "size": 7867,
          "sha512": "4737754b3c0d6b196067d3b8428142fe026ebc95ab4ca8900f5de970ce715abff496a2805bf3d75133e7021de9b034d9ae10e8aa6e0f2f1b3649cfc14c280d8a",
          "sha256": "81069ec291b0478363a08a4d1a82ec91f70437f151a50c9052ab81bb2158ac32",
          "sha1": "4e08078f9f9875a173491d0132b08e27592a23c4",
          "md5": "10c495bd6f7f18ca1a3f68a97723e107"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-release.aar",
          "url": "native_exif-1.0-release.aar",
          "size": 7867,
          "sha512": "4737754b3c0d6b196067d3b8428142fe026ebc95ab4ca8900f5de970ce715abff496a2805bf3d75133e7021de9b034d9ae10e8aa6e0f2f1b3649cfc14c280d8a",
          "sha256": "81069ec291b0478363a08a4d1a82ec91f70437f151a50c9052ab81bb2158ac32",
          "sha1": "4e08078f9f9875a173491d0132b08e27592a23c4",
          "md5": "10c495bd6f7f18ca1a3f68a97723e107"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-profile.aar",
          "url": "native_exif-1.0-profile.aar",
          "size": 7873,
          "sha512": "5258ee4b946e872dc813b4273d0c045b9e05dbb391505a4d2400cb6595ea166125484b91a9a2b914746c8ecce448f910662fd35c5743181c3f96ffa05cf907b8",
          "sha256": "6ef2e0f19311a97f03202bf488a6ddaed2fc918e392a1c68bd845b610953c64d",
          "sha1": "67a3437b95182420d4bb129441d51144602c5c80",
          "md5": "e60b4b63e41b75941514ad3c2f0fd30d"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif-1.0-profile.aar",
          "url": "native_exif-1.0-profile.aar",
          "size": 7873,
          "sha512": "5258ee4b946e872dc813b4273d0c045b9e05dbb391505a4d2400cb6595ea166125484b91a9a2b914746c8ecce448f910662fd35c5743181c3f96ffa05cf907b8",
          "sha256": "6ef2e0f19311a97f03202bf488a6ddaed2fc918e392a1c68bd845b610953c64d",
          "sha1": "67a3437b95182420d4bb129441d51144602c5c80",
          "md5": "e60b4b63e41b75941514ad3c2f0fd30d"
        }
      ]
    }
  ]
}
