{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.50.aar",
          "url": "share_plus_release-1.50.aar",
          "size": 21431,
          "sha512": "a8b31224e90dafd046fa28a064f6e12fe769e11df685f6242943eb7f710805bc9ed85fb58aa2a2e19ecccec90fc7d89a5a45ed92767a247a0128d552b2994e22",
          "sha256": "c1dadf2ac7cbe1814c68f4e8bf55c2bea0c7e8f165d3d078a557680348a45d07",
          "sha1": "48cfc36ead3457346754a9f8550e0314861a943e",
          "md5": "dba94ac6056f367608c790f9dd817442"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.50.aar",
          "url": "share_plus_release-1.50.aar",
          "size": 21431,
          "sha512": "a8b31224e90dafd046fa28a064f6e12fe769e11df685f6242943eb7f710805bc9ed85fb58aa2a2e19ecccec90fc7d89a5a45ed92767a247a0128d552b2994e22",
          "sha256": "c1dadf2ac7cbe1814c68f4e8bf55c2bea0c7e8f165d3d078a557680348a45d07",
          "sha1": "48cfc36ead3457346754a9f8550e0314861a943e",
          "md5": "dba94ac6056f367608c790f9dd817442"
        }
      ]
    }
  ]
}
