{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-1.0.aar",
          "url": "fluttertoast_debug-1.0.aar",
          "size": 10591,
          "sha512": "6ef8f7b06ab01c526f59f3407b44eefd10f1dfbdfe2bde4d2a6ec30307c5119977a52d83e04fcc156308649f5f9e7c49b2753b46f412a5caa5268ecbac54d9c8",
          "sha256": "cad990be327b15a57c39b056b576d2bc76e2c8ce1ab3d00ab0688ddd6e12edc8",
          "sha1": "f9d60351b15b7d894a7867453be5ae645ccaf2db",
          "md5": "f83b3790d1c946509324e69e69394bb5"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-1.0.aar",
          "url": "fluttertoast_debug-1.0.aar",
          "size": 10591,
          "sha512": "6ef8f7b06ab01c526f59f3407b44eefd10f1dfbdfe2bde4d2a6ec30307c5119977a52d83e04fcc156308649f5f9e7c49b2753b46f412a5caa5268ecbac54d9c8",
          "sha256": "cad990be327b15a57c39b056b576d2bc76e2c8ce1ab3d00ab0688ddd6e12edc8",
          "sha1": "f9d60351b15b7d894a7867453be5ae645ccaf2db",
          "md5": "f83b3790d1c946509324e69e69394bb5"
        }
      ]
    }
  ]
}
