{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-1.0.aar",
          "url": "fluttertoast_debug-1.0.aar",
          "size": 10587,
          "sha512": "8a2df47b69c2aaebaebb5f31943d296bfe51759840b176a0025103225278b2b2306ddf988843fa909c4ace27819fae1f1e481dde40da3f7c0c1cd443b9d4dc6a",
          "sha256": "2e617e837ababd107b428643fe00a315dcd2860c47158a5594aa0687ed05a3de",
          "sha1": "ee24ebef0a80a2f1b68d076cd70f087b798f710a",
          "md5": "103253d5d6b704f5084d4ab3b05eac12"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-1.0.aar",
          "url": "fluttertoast_debug-1.0.aar",
          "size": 10587,
          "sha512": "8a2df47b69c2aaebaebb5f31943d296bfe51759840b176a0025103225278b2b2306ddf988843fa909c4ace27819fae1f1e481dde40da3f7c0c1cd443b9d4dc6a",
          "sha256": "2e617e837ababd107b428643fe00a315dcd2860c47158a5594aa0687ed05a3de",
          "sha1": "ee24ebef0a80a2f1b68d076cd70f087b798f710a",
          "md5": "103253d5d6b704f5084d4ab3b05eac12"
        }
      ]
    }
  ]
}
