{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.16.aar",
          "url": "share_plus_profile-1.16.aar",
          "size": 23389,
          "sha512": "c38149bf5bfac824b14d64ce6311e6ba6967e74de597122f3637da81deff17c32f00832338e518fc4017974f6e113148f757853c6afd8350a9ab47abef4f557c",
          "sha256": "02ac2642c3b955d92999fcfc4cf8e540834a816cb0b614a23978be7028fb93b8",
          "sha1": "68fa11da5cc7596dabcbc717dcf42c409abf5651",
          "md5": "c7d445d52db9866b8327bf83a7e78953"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.16.aar",
          "url": "share_plus_profile-1.16.aar",
          "size": 23389,
          "sha512": "c38149bf5bfac824b14d64ce6311e6ba6967e74de597122f3637da81deff17c32f00832338e518fc4017974f6e113148f757853c6afd8350a9ab47abef4f557c",
          "sha256": "02ac2642c3b955d92999fcfc4cf8e540834a816cb0b614a23978be7028fb93b8",
          "sha1": "68fa11da5cc7596dabcbc717dcf42c409abf5651",
          "md5": "c7d445d52db9866b8327bf83a7e78953"
        }
      ]
    }
  ]
}
