{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 57735,
          "sha512": "36a552c492f4f8339c3719615d3bbe0d216d314c039157026991b1e8e8ee34af151b699f5d95ac749d66248116b12f0088da081a4ce7cd21368ed9c14d23fe84",
          "sha256": "3db803b81aa8771cf5471e16c3d10395c36db290193d0741dabf3ce07a3ff012",
          "sha1": "0d3494bb9477541e0048b5ae6a9596d3a370e75c",
          "md5": "03f0f188ffa387d256f4a49e322bb662"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 57735,
          "sha512": "36a552c492f4f8339c3719615d3bbe0d216d314c039157026991b1e8e8ee34af151b699f5d95ac749d66248116b12f0088da081a4ce7cd21368ed9c14d23fe84",
          "sha256": "3db803b81aa8771cf5471e16c3d10395c36db290193d0741dabf3ce07a3ff012",
          "sha1": "0d3494bb9477541e0048b5ae6a9596d3a370e75c",
          "md5": "03f0f188ffa387d256f4a49e322bb662"
        }
      ]
    }
  ]
}
