{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.database",
    "module": "firebase_database_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_profile-1.0.aar",
          "url": "firebase_database_profile-1.0.aar",
          "size": 29287,
          "sha512": "db63eda957a18e7eecc7e5f29e09c74e20a01730db01827cc1ee837ff290c67c9d86e200a73b5dd4c8a24fe3fbcb434ae640591b0180248a58fe275bf434633c",
          "sha256": "8d5efa9c55f9ace82df306457cf0dcc895cff13235a5b485ca76d0f5558e9611",
          "sha1": "5af13526cf403ff36ff0ae29908405b7c6137c19",
          "md5": "e7ac0bc7d24321ba5227a5b06d69a140"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_database_profile-1.0.aar",
          "url": "firebase_database_profile-1.0.aar",
          "size": 29287,
          "sha512": "db63eda957a18e7eecc7e5f29e09c74e20a01730db01827cc1ee837ff290c67c9d86e200a73b5dd4c8a24fe3fbcb434ae640591b0180248a58fe275bf434633c",
          "sha256": "8d5efa9c55f9ace82df306457cf0dcc895cff13235a5b485ca76d0f5558e9611",
          "sha1": "5af13526cf403ff36ff0ae29908405b7c6137c19",
          "md5": "e7ac0bc7d24321ba5227a5b06d69a140"
        }
      ]
    }
  ]
}
