{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.46.aar",
          "url": "path_provider_android_profile-1.46.aar",
          "size": 12433,
          "sha512": "ba5bf8938a88e6cffc49fd204aecd88376cc60ad297851830650353851b71360f687edb3c2e5c1bffeb30030cd12345545f7f4e0aedb0d1878196c1bbb92509e",
          "sha256": "f42182e69da29340405adfb50cfa283e929f5b575c883eec10b53d6106fec7ed",
          "sha1": "3b61c577316505d7cac032f95a15b8ba7119319d",
          "md5": "e3ecd6a594d25cfb3b86e9ea998361a6"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.46.aar",
          "url": "path_provider_android_profile-1.46.aar",
          "size": 12433,
          "sha512": "ba5bf8938a88e6cffc49fd204aecd88376cc60ad297851830650353851b71360f687edb3c2e5c1bffeb30030cd12345545f7f4e0aedb0d1878196c1bbb92509e",
          "sha256": "f42182e69da29340405adfb50cfa283e929f5b575c883eec10b53d6106fec7ed",
          "sha1": "3b61c577316505d7cac032f95a15b8ba7119319d",
          "md5": "e3ecd6a594d25cfb3b86e9ea998361a6"
        }
      ]
    }
  ]
}
