{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_profile-1.48.aar",
          "url": "flutter_local_notifications_profile-1.48.aar",
          "size": 64206,
          "sha512": "656739220bb75ddd98830356f1bb95e3bffbb3d9fd8f88f216274fdb29e58540ff2af7168f8b9710ebbf18ee3d8efde632e782e291c02ff37f0f43592e9c8992",
          "sha256": "a9e1284186fa754bd9bf4717cb6e025ba3c83b84549bccf2e4910d5cfa5b3cea",
          "sha1": "f5abf9325138d2910e4491ccc6096dc0449d162a",
          "md5": "8a59a27a67c75e0f0ae76555039db3ae"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_profile-1.48.aar",
          "url": "flutter_local_notifications_profile-1.48.aar",
          "size": 64206,
          "sha512": "656739220bb75ddd98830356f1bb95e3bffbb3d9fd8f88f216274fdb29e58540ff2af7168f8b9710ebbf18ee3d8efde632e782e291c02ff37f0f43592e9c8992",
          "sha256": "a9e1284186fa754bd9bf4717cb6e025ba3c83b84549bccf2e4910d5cfa5b3cea",
          "sha1": "f5abf9325138d2910e4491ccc6096dc0449d162a",
          "md5": "8a59a27a67c75e0f0ae76555039db3ae"
        }
      ]
    }
  ]
}
