{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_release",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-1.50.aar",
          "url": "flutter_local_notifications_release-1.50.aar",
          "size": 65322,
          "sha512": "346353e2fac7cb0026abd50c5811d77c3e0c49402b74ac3056c48228d98edd3640d5fc97666c7db224d9ffe6e1bcabab690f6b0e53e8df6e41116c4fe8939083",
          "sha256": "39d14a1213bef49f0b2be72e0fd1d6c0dc096fa511b1b860e58898972e4eb9b8",
          "sha1": "680ad204deb0958e2a2faf15a6295e2c1ef96d8c",
          "md5": "d357402294a9170bc4aa036502c1bc94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-1.50.aar",
          "url": "flutter_local_notifications_release-1.50.aar",
          "size": 65322,
          "sha512": "346353e2fac7cb0026abd50c5811d77c3e0c49402b74ac3056c48228d98edd3640d5fc97666c7db224d9ffe6e1bcabab690f6b0e53e8df6e41116c4fe8939083",
          "sha256": "39d14a1213bef49f0b2be72e0fd1d6c0dc096fa511b1b860e58898972e4eb9b8",
          "sha1": "680ad204deb0958e2a2faf15a6295e2c1ef96d8c",
          "md5": "d357402294a9170bc4aa036502c1bc94"
        }
      ]
    }
  ]
}
