{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jhomlala.better_player.better_player",
    "module": "better_player",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.0-debug.aar",
          "url": "better_player-1.0-debug.aar",
          "size": 71016,
          "sha512": "25993f028b8e3b104b74372d954e76f2ff76add039d6b744be08ded2f498667d90e3847d670b17e800cbd996f5ebc843c3c403ad8f6d654d3c1ae5698405fc6c",
          "sha256": "bcdd15b6eab97729959fe0e59e52e02247337431dcd4133c991e06d8b8cdef20",
          "sha1": "779c732368a574c949d0a41b1f7e7eb9da0d0aaf",
          "md5": "28c92ff97327f217b8ed5e304d129a92"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-mediasession",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.0-debug.aar",
          "url": "better_player-1.0-debug.aar",
          "size": 71016,
          "sha512": "25993f028b8e3b104b74372d954e76f2ff76add039d6b744be08ded2f498667d90e3847d670b17e800cbd996f5ebc843c3c403ad8f6d654d3c1ae5698405fc6c",
          "sha256": "bcdd15b6eab97729959fe0e59e52e02247337431dcd4133c991e06d8b8cdef20",
          "sha1": "779c732368a574c949d0a41b1f7e7eb9da0d0aaf",
          "md5": "28c92ff97327f217b8ed5e304d129a92"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.0-release.aar",
          "url": "better_player-1.0-release.aar",
          "size": 67699,
          "sha512": "c096d47d9f572661f994d702788f4b61c55827efc74771cd9452ad15fe16bc187ef82d12f2e286ea96a25cb6eef6c9375d04657653999369eb961ffa72751ee0",
          "sha256": "8d167ca511990cb16d51458199120f38fa57972994c3474bb562f2fc696e704a",
          "sha1": "f7edc36c2faadeb2ad170bbcce871a400f68d656",
          "md5": "b004fedf0ce3baf8485a7b1ac635b669"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-mediasession",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.0-release.aar",
          "url": "better_player-1.0-release.aar",
          "size": 67699,
          "sha512": "c096d47d9f572661f994d702788f4b61c55827efc74771cd9452ad15fe16bc187ef82d12f2e286ea96a25cb6eef6c9375d04657653999369eb961ffa72751ee0",
          "sha256": "8d167ca511990cb16d51458199120f38fa57972994c3474bb562f2fc696e704a",
          "sha1": "f7edc36c2faadeb2ad170bbcce871a400f68d656",
          "md5": "b004fedf0ce3baf8485a7b1ac635b669"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.0-profile.aar",
          "url": "better_player-1.0-profile.aar",
          "size": 67707,
          "sha512": "456e496035eab334d6e0a39cb18dcdb94e21c35de6afc72df67305ab42ab5c832eab4b0535a2a9270df4ef3c9c5d043e934699ca912af921019c4d24e7337f88",
          "sha256": "a66c14ee8ed1f0ed2926b40cc22f93cfbc27860ebe328b954e4efd2644e5900d",
          "sha1": "1e47a358cbb223ff2d011c75242078b41b5f990e",
          "md5": "12dca695af7c688b05f355d38bb9ea6c"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-mediasession",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.0-profile.aar",
          "url": "better_player-1.0-profile.aar",
          "size": 67707,
          "sha512": "456e496035eab334d6e0a39cb18dcdb94e21c35de6afc72df67305ab42ab5c832eab4b0535a2a9270df4ef3c9c5d043e934699ca912af921019c4d24e7337f88",
          "sha256": "a66c14ee8ed1f0ed2926b40cc22f93cfbc27860ebe328b954e4efd2644e5900d",
          "sha1": "1e47a358cbb223ff2d011c75242078b41b5f990e",
          "md5": "12dca695af7c688b05f355d38bb9ea6c"
        }
      ]
    }
  ]
}
