{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtplugin.plugincheck",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 23115372,
          "sha512": "b8ad41b40f7e84f1b9b25eaa103fa6127ab096cca7230709a70ae7c6c521403adc07d417dc080228e25452860825f00c03313f221301142259be3a520b998554",
          "sha256": "591d873f95d603167331811a8e8d06abfbdb44ddc6956202bea4511d2217e0c0",
          "sha1": "c2decb1b55974dd6f7c06d00048be93cd10d2853",
          "md5": "8c69ddcfbcbd59cf8d67f966f27c8e4d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.database",
          "module": "firebase_database_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mixpanel.mixpanel_flutter",
          "module": "mixpanel_flutter_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.adaptant.labs.flutter_windowmanager",
          "module": "flutter_windowmanager_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.wowtalkies.walletutilityplugin",
          "module": "walletutilityplugin_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.cloudacy.native_exif",
          "module": "native_exif_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.sidlatau.flutteremailsender",
          "module": "flutter_email_sender_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "xyz.justsoft.video_thumbnail",
          "module": "video_thumbnail_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.auth",
          "module": "firebase_auth_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.bhikadia.receive_intent",
          "module": "receive_intent_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 23115372,
          "sha512": "b8ad41b40f7e84f1b9b25eaa103fa6127ab096cca7230709a70ae7c6c521403adc07d417dc080228e25452860825f00c03313f221301142259be3a520b998554",
          "sha256": "591d873f95d603167331811a8e8d06abfbdb44ddc6956202bea4511d2217e0c0",
          "sha1": "c2decb1b55974dd6f7c06d00048be93cd10d2853",
          "md5": "8c69ddcfbcbd59cf8d67f966f27c8e4d"
        }
      ]
    }
  ]
}
