{
  "formatVersion": "1.1",
  "component": {
    "group": "io.adaptant.labs.flutter_windowmanager",
    "module": "flutter_windowmanager_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_release-1.0.aar",
          "url": "flutter_windowmanager_release-1.0.aar",
          "size": 5548,
          "sha512": "8155d3b4ae4d7ccc2099e5fcae2b6b4821db1b6144cb551f1fab5c40a8906918f6ecf8a1f899a0ddfc1a64db9cda38dd3140253916191f47efd69227c45b2d02",
          "sha256": "678f54f58c25732d74bbc179b013b3dd5eb0bfe9efdda0f72777614de292cb5a",
          "sha1": "6dbcebdf092e15d869f3241b4f63344a9fd0f8c2",
          "md5": "61b365de6c30b71e655cc7a6636146ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_windowmanager_release-1.0.aar",
          "url": "flutter_windowmanager_release-1.0.aar",
          "size": 5548,
          "sha512": "8155d3b4ae4d7ccc2099e5fcae2b6b4821db1b6144cb551f1fab5c40a8906918f6ecf8a1f899a0ddfc1a64db9cda38dd3140253916191f47efd69227c45b2d02",
          "sha256": "678f54f58c25732d74bbc179b013b3dd5eb0bfe9efdda0f72777614de292cb5a",
          "sha1": "6dbcebdf092e15d869f3241b4f63344a9fd0f8c2",
          "md5": "61b365de6c30b71e655cc7a6636146ed"
        }
      ]
    }
  ]
}
