{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_debug",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.38.aar",
          "url": "native_exif_debug-1.38.aar",
          "size": 8204,
          "sha512": "60b855c96a7f4cf0fcc1008042fb4c74d5ac1e0e520686b06de44baff6a911c89ae0474684dba98c83cbe9cba9a99fdc3e2dc61f2d79c5153925db4f06b8d383",
          "sha256": "3c168b7e67ea4f33e9edcef408af137bbbc76b90f98b59435b263099a64871e9",
          "sha1": "b47ce55ab269c925328e6b7ef8d1d801c4363b46",
          "md5": "6ed498b328e00cf20dc93630c6cf5c10"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.38.aar",
          "url": "native_exif_debug-1.38.aar",
          "size": 8204,
          "sha512": "60b855c96a7f4cf0fcc1008042fb4c74d5ac1e0e520686b06de44baff6a911c89ae0474684dba98c83cbe9cba9a99fdc3e2dc61f2d79c5153925db4f06b8d383",
          "sha256": "3c168b7e67ea4f33e9edcef408af137bbbc76b90f98b59435b263099a64871e9",
          "sha1": "b47ce55ab269c925328e6b7ef8d1d801c4363b46",
          "md5": "6ed498b328e00cf20dc93630c6cf5c10"
        }
      ]
    }
  ]
}
