{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.droibit.plugins.flutter.customtabs",
    "module": "flutter_custom_tabs",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs-1.0-debug.aar",
          "url": "flutter_custom_tabs-1.0-debug.aar",
          "size": 8388,
          "sha512": "07ebe5755360853f0a23e58afb584c01b081061cd3753babeed78d9d1440f71d48d55a06838a9c5ab09629e1f339fa10036bce4ea49c27d467055eee34edc8f6",
          "sha256": "f50f8bf0d2b8fbdb42b6144557a890fa63953121f8be3d906771bd61a63ea6f8",
          "sha1": "86c55fd0d3ef7e2bcb80ff5679361ca0031e274b",
          "md5": "efbfe77cd9bafb925fbbdd8df0e95c08"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs-1.0-debug.aar",
          "url": "flutter_custom_tabs-1.0-debug.aar",
          "size": 8388,
          "sha512": "07ebe5755360853f0a23e58afb584c01b081061cd3753babeed78d9d1440f71d48d55a06838a9c5ab09629e1f339fa10036bce4ea49c27d467055eee34edc8f6",
          "sha256": "f50f8bf0d2b8fbdb42b6144557a890fa63953121f8be3d906771bd61a63ea6f8",
          "sha1": "86c55fd0d3ef7e2bcb80ff5679361ca0031e274b",
          "md5": "efbfe77cd9bafb925fbbdd8df0e95c08"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs-1.0-release.aar",
          "url": "flutter_custom_tabs-1.0-release.aar",
          "size": 8052,
          "sha512": "3058588ff3b7b595ded705a9cf02d60d28c99542337490183be99e7455460ed99ff13839185996a30d038c31af5eaf89a6554b8249be69eb52a51746b09bc925",
          "sha256": "964a96d9240ab329562253e2c1f5071aecd07860c92f49f3507d57f3da49ecf3",
          "sha1": "55ef49246d323f25f751b8bf578bc782b70961ae",
          "md5": "a914c5cfe0f5a82196a919b9e4277bbc"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs-1.0-release.aar",
          "url": "flutter_custom_tabs-1.0-release.aar",
          "size": 8052,
          "sha512": "3058588ff3b7b595ded705a9cf02d60d28c99542337490183be99e7455460ed99ff13839185996a30d038c31af5eaf89a6554b8249be69eb52a51746b09bc925",
          "sha256": "964a96d9240ab329562253e2c1f5071aecd07860c92f49f3507d57f3da49ecf3",
          "sha1": "55ef49246d323f25f751b8bf578bc782b70961ae",
          "md5": "a914c5cfe0f5a82196a919b9e4277bbc"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs-1.0-profile.aar",
          "url": "flutter_custom_tabs-1.0-profile.aar",
          "size": 8052,
          "sha512": "3058588ff3b7b595ded705a9cf02d60d28c99542337490183be99e7455460ed99ff13839185996a30d038c31af5eaf89a6554b8249be69eb52a51746b09bc925",
          "sha256": "964a96d9240ab329562253e2c1f5071aecd07860c92f49f3507d57f3da49ecf3",
          "sha1": "55ef49246d323f25f751b8bf578bc782b70961ae",
          "md5": "a914c5cfe0f5a82196a919b9e4277bbc"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs-1.0-profile.aar",
          "url": "flutter_custom_tabs-1.0-profile.aar",
          "size": 8052,
          "sha512": "3058588ff3b7b595ded705a9cf02d60d28c99542337490183be99e7455460ed99ff13839185996a30d038c31af5eaf89a6554b8249be69eb52a51746b09bc925",
          "sha256": "964a96d9240ab329562253e2c1f5071aecd07860c92f49f3507d57f3da49ecf3",
          "sha1": "55ef49246d323f25f751b8bf578bc782b70961ae",
          "md5": "a914c5cfe0f5a82196a919b9e4277bbc"
        }
      ]
    }
  ]
}
