{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 39038,
          "sha512": "249021de4844dbbf9c8d7e0d9a180e1b73522fdfef9ebe2cde8260fbb7230d2284df094275a1add6c250426819607d19244d1662e7f70271e0ece693dada2cca",
          "sha256": "66032fe2233ebafaff6d63328af30f074d2016fefa52a18de68ad24d5da486c6",
          "sha1": "cc4d9aa3cf03cb0b6631591ea3a5bffa2934d046",
          "md5": "8b1544edf98f577c33f7c7a9a6097734"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.6"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.6"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.6"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.6"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 39038,
          "sha512": "249021de4844dbbf9c8d7e0d9a180e1b73522fdfef9ebe2cde8260fbb7230d2284df094275a1add6c250426819607d19244d1662e7f70271e0ece693dada2cca",
          "sha256": "66032fe2233ebafaff6d63328af30f074d2016fefa52a18de68ad24d5da486c6",
          "sha1": "cc4d9aa3cf03cb0b6631591ea3a5bffa2934d046",
          "md5": "8b1544edf98f577c33f7c7a9a6097734"
        }
      ]
    }
  ]
}
