{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.0.aar",
          "url": "receive_intent_debug-1.0.aar",
          "size": 13485,
          "sha512": "b4ccc8a85b27494a6525dbfc16e092a28f1683afc7a05719d78ac960621c61c7c81dd790443f342abf5f51c790166fdf67c4d454c937d62c94121deba86eba4e",
          "sha256": "15774bc66cfaec57ed9ae1a097ae1f074772c27c720411703062978e5e29c87c",
          "sha1": "f4fd3f0c9712cc5b6870832762a4a4f89f34d89b",
          "md5": "a4fd4123e5849ddce46a236332ba909b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.0.aar",
          "url": "receive_intent_debug-1.0.aar",
          "size": 13485,
          "sha512": "b4ccc8a85b27494a6525dbfc16e092a28f1683afc7a05719d78ac960621c61c7c81dd790443f342abf5f51c790166fdf67c4d454c937d62c94121deba86eba4e",
          "sha256": "15774bc66cfaec57ed9ae1a097ae1f074772c27c720411703062978e5e29c87c",
          "sha1": "f4fd3f0c9712cc5b6870832762a4a4f89f34d89b",
          "md5": "a4fd4123e5849ddce46a236332ba909b"
        }
      ]
    }
  ]
}
