{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.0.aar",
          "url": "receive_intent_debug-1.0.aar",
          "size": 13491,
          "sha512": "38d9763c2ef30447de35f658686263ec33241a7866a98e0f82dba7443021f757519fd65cd09f2f048eda9ca18013a64708562e47af2c60d17b870aa07b5cc0b6",
          "sha256": "a28f641cf54c304e9cd285ba435357b0122cd3cc60d3d32118edceea9dfdb755",
          "sha1": "1eedb11ab7768c267e942076467435da5b0d541b",
          "md5": "79582aea355fbd382cfd7bf01bc0ff4d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_debug-1.0.aar",
          "url": "receive_intent_debug-1.0.aar",
          "size": 13491,
          "sha512": "38d9763c2ef30447de35f658686263ec33241a7866a98e0f82dba7443021f757519fd65cd09f2f048eda9ca18013a64708562e47af2c60d17b870aa07b5cc0b6",
          "sha256": "a28f641cf54c304e9cd285ba435357b0122cd3cc60d3d32118edceea9dfdb755",
          "sha1": "1eedb11ab7768c267e942076467435da5b0d541b",
          "md5": "79582aea355fbd382cfd7bf01bc0ff4d"
        }
      ]
    }
  ]
}
