{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.auth",
    "module": "firebase_auth",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth-1.0-debug.aar",
          "url": "firebase_auth-1.0-debug.aar",
          "size": 64626,
          "sha512": "d2cd9a644b8253c3db9881dd1fc5e8dd4b197679f3802cc0675fa2b69047f5ec8cc3a936e9d77fd592930b29db126a09324a6400c920dd39deb55eab57441b74",
          "sha256": "bad088b37e12eb9f51d3a5711626f740850382f54141fb6b92f6bca55bfcb09e",
          "sha1": "ab24fcbfdbb3db14da51f9dfd5b9675deca769dd",
          "md5": "39039c8022f3707d187b83262ce51087"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth-1.0-debug.aar",
          "url": "firebase_auth-1.0-debug.aar",
          "size": 64626,
          "sha512": "d2cd9a644b8253c3db9881dd1fc5e8dd4b197679f3802cc0675fa2b69047f5ec8cc3a936e9d77fd592930b29db126a09324a6400c920dd39deb55eab57441b74",
          "sha256": "bad088b37e12eb9f51d3a5711626f740850382f54141fb6b92f6bca55bfcb09e",
          "sha1": "ab24fcbfdbb3db14da51f9dfd5b9675deca769dd",
          "md5": "39039c8022f3707d187b83262ce51087"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth-1.0-release.aar",
          "url": "firebase_auth-1.0-release.aar",
          "size": 60395,
          "sha512": "acbad5b11549d4cfb4ab9af25398e164fb58f4c7f6b22efe60a43a1a343e34b45ed143cc4bbe172a0b0d542243c20e949df050285a4778c2d7eedf9ff3d4a9a6",
          "sha256": "27c735cc82db05138169df7f84822af22ef65030055e9118845a0a0be62528a4",
          "sha1": "f4162f36e2d774a08dc18d19a41b29b6035c4920",
          "md5": "8ce7a960cd79dad603c032e146ff361c"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth-1.0-release.aar",
          "url": "firebase_auth-1.0-release.aar",
          "size": 60395,
          "sha512": "acbad5b11549d4cfb4ab9af25398e164fb58f4c7f6b22efe60a43a1a343e34b45ed143cc4bbe172a0b0d542243c20e949df050285a4778c2d7eedf9ff3d4a9a6",
          "sha256": "27c735cc82db05138169df7f84822af22ef65030055e9118845a0a0be62528a4",
          "sha1": "f4162f36e2d774a08dc18d19a41b29b6035c4920",
          "md5": "8ce7a960cd79dad603c032e146ff361c"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth-1.0-profile.aar",
          "url": "firebase_auth-1.0-profile.aar",
          "size": 60403,
          "sha512": "71b782bafaea1fac640277a8070656dacf752cefcaa5402a08c07b9a325f6a42a1aa100f3396f4c3051b39bc490ac2d8d8934aa5dcb96c29e389ef84b9f67a0c",
          "sha256": "0b9081c537331b092211262f6ff7a284d92a73767ecd4bc3095231dc42e8d7ca",
          "sha1": "4d8369f4f4fdc14b4ed65ddfe73b6f3b4b18b98c",
          "md5": "7b787fc858ad550f105a0fa6445370e7"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_auth-1.0-profile.aar",
          "url": "firebase_auth-1.0-profile.aar",
          "size": 60403,
          "sha512": "71b782bafaea1fac640277a8070656dacf752cefcaa5402a08c07b9a325f6a42a1aa100f3396f4c3051b39bc490ac2d8d8934aa5dcb96c29e389ef84b9f67a0c",
          "sha256": "0b9081c537331b092211262f6ff7a284d92a73767ecd4bc3095231dc42e8d7ca",
          "sha1": "4d8369f4f4fdc14b4ed65ddfe73b6f3b4b18b98c",
          "md5": "7b787fc858ad550f105a0fa6445370e7"
        }
      ]
    }
  ]
}
