{
  "formatVersion": "1.1",
  "component": {
    "group": "creativemaybeno.wakelock",
    "module": "wakelock_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_debug-1.0.aar",
          "url": "wakelock_debug-1.0.aar",
          "size": 11761,
          "sha512": "696b50158c426b50af2870cf50c1e83241370edd093191711a5a85f4b111aa58aae986afa898990908b9256ec617066df192db2c36bf21a13a9683fbdda81a31",
          "sha256": "52e2ecc1bb842f71a93c6a3250ceffc609bb26a5b4ff147a45f35d53695e6d8d",
          "sha1": "f103ec93b46b0fa86d436a18cf26b7595ee86973",
          "md5": "424f980bd39b6336499aca39e8c20b4c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_debug-1.0.aar",
          "url": "wakelock_debug-1.0.aar",
          "size": 11761,
          "sha512": "696b50158c426b50af2870cf50c1e83241370edd093191711a5a85f4b111aa58aae986afa898990908b9256ec617066df192db2c36bf21a13a9683fbdda81a31",
          "sha256": "52e2ecc1bb842f71a93c6a3250ceffc609bb26a5b4ff147a45f35d53695e6d8d",
          "sha1": "f103ec93b46b0fa86d436a18cf26b7595ee86973",
          "md5": "424f980bd39b6336499aca39e8c20b4c"
        }
      ]
    }
  ]
}
