{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.analytics",
    "module": "firebase_analytics_debug",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.47"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_analytics_debug-1.47.aar",
          "url": "firebase_analytics_debug-1.47.aar",
          "size": 12061,
          "sha512": "7f48a41a86eb7c39d58b13027db2bce643a408944fdb5f93a2b7de70e54249bd635c31cf2d401360256ca2db03c07f739b2125160374035619f5e0126c21a4f8",
          "sha256": "129285834be5c2ab0124f3a54947bfc101f590ef997783f5e0f177d375bd7283",
          "sha1": "b0d81ba0a3b15a2bd0f019981bd560bf8cecf735",
          "md5": "0c0ecad200dff6f04a871788ff7a58ce"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.47"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_analytics_debug-1.47.aar",
          "url": "firebase_analytics_debug-1.47.aar",
          "size": 12061,
          "sha512": "7f48a41a86eb7c39d58b13027db2bce643a408944fdb5f93a2b7de70e54249bd635c31cf2d401360256ca2db03c07f739b2125160374035619f5e0126c21a4f8",
          "sha256": "129285834be5c2ab0124f3a54947bfc101f590ef997783f5e0f177d375bd7283",
          "sha1": "b0d81ba0a3b15a2bd0f019981bd560bf8cecf735",
          "md5": "0c0ecad200dff6f04a871788ff7a58ce"
        }
      ]
    }
  ]
}
