{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sidlatau.flutteremailsender",
    "module": "flutter_email_sender_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_debug-1.0.aar",
          "url": "flutter_email_sender_debug-1.0.aar",
          "size": 22068,
          "sha512": "d79f9a326a878257dadf0c2ae0cbfa5252f05be162fa29575e78d7a90ead289382e35eb6779d269a1e2282f676eab6a07248cb7648e6c34815552bc2f8ce11e4",
          "sha256": "bc17201e57629612c13e7c126f28cd13fb565f5803dad339e26924e5f64a6ed5",
          "sha1": "3d5ec9192250e621dbede608d723f53f5f641b3e",
          "md5": "811bde3a6f6b8fc69475bb5b44031990"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_debug-1.0.aar",
          "url": "flutter_email_sender_debug-1.0.aar",
          "size": 22068,
          "sha512": "d79f9a326a878257dadf0c2ae0cbfa5252f05be162fa29575e78d7a90ead289382e35eb6779d269a1e2282f676eab6a07248cb7648e6c34815552bc2f8ce11e4",
          "sha256": "bc17201e57629612c13e7c126f28cd13fb565f5803dad339e26924e5f64a6ed5",
          "sha1": "3d5ec9192250e621dbede608d723f53f5f641b3e",
          "md5": "811bde3a6f6b8fc69475bb5b44031990"
        }
      ]
    }
  ]
}
