{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wowtalkies.walletutilityplugin",
    "module": "walletutilityplugin_release",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_release-1.2.aar",
          "url": "walletutilityplugin_release-1.2.aar",
          "size": 12758086,
          "sha512": "6ea4ba08cc31d2879fa0c757a20dfa75478225d1dab4a44b00317433585500031176e83fc9b3d68ab466e4cc324324f004e5b8dd24ed4b8101aa51bcf670941e",
          "sha256": "1f9f99e2a0cadbb231288749bda69278423361fb992d14d1531f67723fb00506",
          "sha1": "e0985ea05087146d17d2ec2cf5da06e8ee8d62fe",
          "md5": "9559c1b29b0313379951cc0d995ef31a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "walletutilityplugin_release-1.2.aar",
          "url": "walletutilityplugin_release-1.2.aar",
          "size": 12758086,
          "sha512": "6ea4ba08cc31d2879fa0c757a20dfa75478225d1dab4a44b00317433585500031176e83fc9b3d68ab466e4cc324324f004e5b8dd24ed4b8101aa51bcf670941e",
          "sha256": "1f9f99e2a0cadbb231288749bda69278423361fb992d14d1531f67723fb00506",
          "sha1": "e0985ea05087146d17d2ec2cf5da06e8ee8d62fe",
          "md5": "9559c1b29b0313379951cc0d995ef31a"
        }
      ]
    }
  ]
}
