{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.core",
    "module": "firebase_core_debug",
    "version": "1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_debug-1.38.aar",
          "url": "firebase_core_debug-1.38.aar",
          "size": 31641,
          "sha512": "1cf57a7fb77332b4edd154c0f82fbbbac79459f1149d2186a8ca8ad4d2266435396deec5a9c2dbe568376dad28d7b562aff4ff94580c6c0b4758057443d4f7f9",
          "sha256": "76fc1ef00c76a26e80ac5998ce7201fc277013567baa2f1ecdd2f00827b19f68",
          "sha1": "8e494d2d1dcdcc174d6cf297ccccb70203bac904",
          "md5": "2dc691b1acab7555c0331d716ec528f2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_core_debug-1.38.aar",
          "url": "firebase_core_debug-1.38.aar",
          "size": 31641,
          "sha512": "1cf57a7fb77332b4edd154c0f82fbbbac79459f1149d2186a8ca8ad4d2266435396deec5a9c2dbe568376dad28d7b562aff4ff94580c6c0b4758057443d4f7f9",
          "sha256": "76fc1ef00c76a26e80ac5998ce7201fc277013567baa2f1ecdd2f00827b19f68",
          "sha1": "8e494d2d1dcdcc174d6cf297ccccb70203bac904",
          "md5": "2dc691b1acab7555c0331d716ec528f2"
        }
      ]
    }
  ]
}
