{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sidlatau.flutteremailsender",
    "module": "flutter_email_sender_release",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_release-1.50.aar",
          "url": "flutter_email_sender_release-1.50.aar",
          "size": 21576,
          "sha512": "b78b51962b22c84f78d01038645fdc0b1eefe189654b1d625eaa1f4bdc062e263a3cfd71b4dbad33db3d32da5394c1bc39371da6d599dc27a974aa7cdeb339ab",
          "sha256": "9e7bded9aff150100351e28398e6a8c78f9c94f93d051bff40112ccf33afeb9d",
          "sha1": "9ad5dba2431233880c8c7fc1f36d656ba1ba56c8",
          "md5": "e3ee0a035844e1df7b71e7c66f84481e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_email_sender_release-1.50.aar",
          "url": "flutter_email_sender_release-1.50.aar",
          "size": 21576,
          "sha512": "b78b51962b22c84f78d01038645fdc0b1eefe189654b1d625eaa1f4bdc062e263a3cfd71b4dbad33db3d32da5394c1bc39371da6d599dc27a974aa7cdeb339ab",
          "sha256": "9e7bded9aff150100351e28398e6a8c78f9c94f93d051bff40112ccf33afeb9d",
          "sha1": "9ad5dba2431233880c8c7fc1f36d656ba1ba56c8",
          "md5": "e3ee0a035844e1df7b71e7c66f84481e"
        }
      ]
    }
  ]
}
