{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.48.aar",
          "url": "url_launcher_android_profile-1.48.aar",
          "size": 19698,
          "sha512": "5bfdbc46aca4812184b8e168ec4fce943098906f2d2530add423bd362719023215f8f6db68d6f7ce313a38df4bd21306a5d6358640c5a9fc1d2a3f18b89e0cc0",
          "sha256": "8e5012a1d7c6dbdafd2e0920950a005b5ec24424dd1063ef4c1c93b991d1bcb6",
          "sha1": "0399dfa3b67afe3e8ccaaa5a050d6a40cf8287d3",
          "md5": "194aa8719953721198fb6712d04339ae"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.48.aar",
          "url": "url_launcher_android_profile-1.48.aar",
          "size": 19698,
          "sha512": "5bfdbc46aca4812184b8e168ec4fce943098906f2d2530add423bd362719023215f8f6db68d6f7ce313a38df4bd21306a5d6358640c5a9fc1d2a3f18b89e0cc0",
          "sha256": "8e5012a1d7c6dbdafd2e0920950a005b5ec24424dd1063ef4c1c93b991d1bcb6",
          "sha1": "0399dfa3b67afe3e8ccaaa5a050d6a40cf8287d3",
          "md5": "194aa8719953721198fb6712d04339ae"
        }
      ]
    }
  ]
}
