{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_debug",
    "version": "1.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_debug-1.46.aar",
          "url": "local_auth_android_debug-1.46.aar",
          "size": 65145,
          "sha512": "fe66527adfdd91216a940d8bd9b407e852d5d5fa773b9ceffb4b4e946d448982ce839c57d935f0d10d9471ec65ac81260af7988a83c0851a0845393f4e17ae46",
          "sha256": "0b1e9f20e62a3f7d8a339a4789c9ac5fb8ccac641a26a24006e31423a8f6461f",
          "sha1": "ed4a37dd1584322ce6133d2baeaaf715ea6ae662",
          "md5": "95d6c2be7d798baec2c97f95351863e2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_debug-1.46.aar",
          "url": "local_auth_android_debug-1.46.aar",
          "size": 65145,
          "sha512": "fe66527adfdd91216a940d8bd9b407e852d5d5fa773b9ceffb4b4e946d448982ce839c57d935f0d10d9471ec65ac81260af7988a83c0851a0845393f4e17ae46",
          "sha256": "0b1e9f20e62a3f7d8a339a4789c9ac5fb8ccac641a26a24006e31423a8f6461f",
          "sha1": "ed4a37dd1584322ce6133d2baeaaf715ea6ae662",
          "md5": "95d6c2be7d798baec2c97f95351863e2"
        }
      ]
    }
  ]
}
