{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jhomlala.better_player.better_player",
    "module": "better_player",
    "version": "1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.17-debug.aar",
          "url": "better_player-1.17-debug.aar",
          "size": 70668,
          "sha512": "86442af1d452f0966aec7866009e52fe2d82cba3ef90fd28749289892277e0793082e72914bc13a11699bee7a256f1dbd31180440f24f6274cad6068f4b2f2f1",
          "sha256": "686dd32a34a6c4cb5809cdaf6b4dd85ac8cab87c0a5c1abb343feed0161c2c71",
          "sha1": "86f636e670a9b3665f10c69f647e767f5e09b46f",
          "md5": "03ed78131e6250307f959939d97d52c6"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-mediasession",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.17"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.17-debug.aar",
          "url": "better_player-1.17-debug.aar",
          "size": 70668,
          "sha512": "86442af1d452f0966aec7866009e52fe2d82cba3ef90fd28749289892277e0793082e72914bc13a11699bee7a256f1dbd31180440f24f6274cad6068f4b2f2f1",
          "sha256": "686dd32a34a6c4cb5809cdaf6b4dd85ac8cab87c0a5c1abb343feed0161c2c71",
          "sha1": "86f636e670a9b3665f10c69f647e767f5e09b46f",
          "md5": "03ed78131e6250307f959939d97d52c6"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.17-release.aar",
          "url": "better_player-1.17-release.aar",
          "size": 67339,
          "sha512": "4ea259f46102df37db0340ea19cb5bf1b63230aef4c35c6e2b862bbbd44414902511b506ad036fd98078effe4037580734c6e0877c4b6e81e50d0bfa675036e5",
          "sha256": "c7f811f14bd5a787af9c6479f55dd56388518719529e7736c3a0c79251dc5d16",
          "sha1": "b1e5b619fc2b8c88b47674abad249adba3f30f05",
          "md5": "9007e8507584ed0bfc9f8bcc1c17f362"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-mediasession",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.17"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.17-release.aar",
          "url": "better_player-1.17-release.aar",
          "size": 67339,
          "sha512": "4ea259f46102df37db0340ea19cb5bf1b63230aef4c35c6e2b862bbbd44414902511b506ad036fd98078effe4037580734c6e0877c4b6e81e50d0bfa675036e5",
          "sha256": "c7f811f14bd5a787af9c6479f55dd56388518719529e7736c3a0c79251dc5d16",
          "sha1": "b1e5b619fc2b8c88b47674abad249adba3f30f05",
          "md5": "9007e8507584ed0bfc9f8bcc1c17f362"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.17-profile.aar",
          "url": "better_player-1.17-profile.aar",
          "size": 67334,
          "sha512": "395b72ed69afd772776604e05032490dbd52ba5e74b84f61e8bc733bde8a563e5e068247a4df83477606333247d378cee0ee6316fa549e8d5085abef5e35e837",
          "sha256": "d2cd3f49f37f16b2ade0a4248cfd173a0294c66a01b228cd1a190e9be30f1298",
          "sha1": "8d4c55c42b3f9e1ad8b822d92b32ba57e9c5ee43",
          "md5": "b93e3d42a54ba3dcc25a6b4e43a77d72"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-mediasession",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.17"
          }
        }
      ],
      "files": [
        {
          "name": "better_player-1.17-profile.aar",
          "url": "better_player-1.17-profile.aar",
          "size": 67334,
          "sha512": "395b72ed69afd772776604e05032490dbd52ba5e74b84f61e8bc733bde8a563e5e068247a4df83477606333247d378cee0ee6316fa549e8d5085abef5e35e837",
          "sha256": "d2cd3f49f37f16b2ade0a4248cfd173a0294c66a01b228cd1a190e9be30f1298",
          "sha1": "8d4c55c42b3f9e1ad8b822d92b32ba57e9c5ee43",
          "md5": "b93e3d42a54ba3dcc25a6b4e43a77d72"
        }
      ]
    }
  ]
}
