{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_profile-1.0.aar",
          "url": "receive_intent_profile-1.0.aar",
          "size": 12872,
          "sha512": "427024414d2e3b1e92057633e51bc86fc3adcf5b17bac4e2b4475170f9cc5577ee8b564d1ed1c7b7b95fb79d8208b2e8a0d2a7fe439f42a313369a6649df61c8",
          "sha256": "f5c03c6a0c40ed0bc76e4c11bc8cdb680344b1b311f08b0e07c2c3ec0c33a657",
          "sha1": "e833af42219f4b973dd812275b6385747a1c2a26",
          "md5": "df15cface1a1f5806ef5036efd86d975"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_profile-1.0.aar",
          "url": "receive_intent_profile-1.0.aar",
          "size": 12872,
          "sha512": "427024414d2e3b1e92057633e51bc86fc3adcf5b17bac4e2b4475170f9cc5577ee8b564d1ed1c7b7b95fb79d8208b2e8a0d2a7fe439f42a313369a6649df61c8",
          "sha256": "f5c03c6a0c40ed0bc76e4c11bc8cdb680344b1b311f08b0e07c2c3ec0c33a657",
          "sha1": "e833af42219f4b973dd812275b6385747a1c2a26",
          "md5": "df15cface1a1f5806ef5036efd86d975"
        }
      ]
    }
  ]
}
