{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_debug",
    "version": "1.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.50.aar",
          "url": "native_exif_debug-1.50.aar",
          "size": 8201,
          "sha512": "af8021cb3e036cdff7f3faa048e1860282f1ef47f11068eaa8932957728c25d9d5c3679033b9daf2c20452c7efe16d01f7418dfd745913431f26fbaf728a0b4d",
          "sha256": "18f23221ed12020a2a3b91fca9d470dce682d12d6f0c855113aa2988f84dc085",
          "sha1": "9b5eebc514dacfe4ac906d6fbfc504bf16bb2adb",
          "md5": "c9266b5ad10b0027ed110e91968f3744"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_debug-1.50.aar",
          "url": "native_exif_debug-1.50.aar",
          "size": 8201,
          "sha512": "af8021cb3e036cdff7f3faa048e1860282f1ef47f11068eaa8932957728c25d9d5c3679033b9daf2c20452c7efe16d01f7418dfd745913431f26fbaf728a0b4d",
          "sha256": "18f23221ed12020a2a3b91fca9d470dce682d12d6f0c855113aa2988f84dc085",
          "sha1": "9b5eebc514dacfe4ac906d6fbfc504bf16bb2adb",
          "md5": "c9266b5ad10b0027ed110e91968f3744"
        }
      ]
    }
  ]
}
