{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.0.aar",
          "url": "native_exif_release-1.0.aar",
          "size": 7867,
          "sha512": "4737754b3c0d6b196067d3b8428142fe026ebc95ab4ca8900f5de970ce715abff496a2805bf3d75133e7021de9b034d9ae10e8aa6e0f2f1b3649cfc14c280d8a",
          "sha256": "81069ec291b0478363a08a4d1a82ec91f70437f151a50c9052ab81bb2158ac32",
          "sha1": "4e08078f9f9875a173491d0132b08e27592a23c4",
          "md5": "10c495bd6f7f18ca1a3f68a97723e107"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3950c6140a3f1cb295364b0446627bd3a1736915"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.0.aar",
          "url": "native_exif_release-1.0.aar",
          "size": 7867,
          "sha512": "4737754b3c0d6b196067d3b8428142fe026ebc95ab4ca8900f5de970ce715abff496a2805bf3d75133e7021de9b034d9ae10e8aa6e0f2f1b3649cfc14c280d8a",
          "sha256": "81069ec291b0478363a08a4d1a82ec91f70437f151a50c9052ab81bb2158ac32",
          "sha1": "4e08078f9f9875a173491d0132b08e27592a23c4",
          "md5": "10c495bd6f7f18ca1a3f68a97723e107"
        }
      ]
    }
  ]
}
