{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.0.aar",
          "url": "native_exif_release-1.0.aar",
          "size": 7918,
          "sha512": "460c608bc65fcacd606369834253888a9383b80d5def11319c0be0ccbb35ec606ec43a3a23eaf083eceaf648b309ae29c0d8000febd013ab3835da0cd672e2a7",
          "sha256": "459fff2158bda2917052a45277084a138d616a9af1c9fffb566750424f5f250f",
          "sha1": "7abd7e602fd96059cf7e2b91d3dc6d27edba890e",
          "md5": "14d92198c6e0abd6a3a7f4e6c8bb52e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.0.aar",
          "url": "native_exif_release-1.0.aar",
          "size": 7918,
          "sha512": "460c608bc65fcacd606369834253888a9383b80d5def11319c0be0ccbb35ec606ec43a3a23eaf083eceaf648b309ae29c0d8000febd013ab3835da0cd672e2a7",
          "sha256": "459fff2158bda2917052a45277084a138d616a9af1c9fffb566750424f5f250f",
          "sha1": "7abd7e602fd96059cf7e2b91d3dc6d27edba890e",
          "md5": "14d92198c6e0abd6a3a7f4e6c8bb52e5"
        }
      ]
    }
  ]
}
