{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudacy.native_exif",
    "module": "native_exif_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.0.aar",
          "url": "native_exif_release-1.0.aar",
          "size": 7921,
          "sha512": "837abc05d0549ddc5695907d91f7f0ad1476dec0e0f312cc89ff272d28f1b08483c9518039e805d34f06f3fcf1f4d5028250fab91c5c54ffb6a41264b2109871",
          "sha256": "85f53c8343eccbc05e0307ba50aba55379b03a05ae8a056ab3c0e291a50416d8",
          "sha1": "b39f0a0bbd52151202028c8e9d3342b9e0b6af3e",
          "md5": "275bfba75c91365f3c3d9f2788f9c31b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "native_exif_release-1.0.aar",
          "url": "native_exif_release-1.0.aar",
          "size": 7921,
          "sha512": "837abc05d0549ddc5695907d91f7f0ad1476dec0e0f312cc89ff272d28f1b08483c9518039e805d34f06f3fcf1f4d5028250fab91c5c54ffb6a41264b2109871",
          "sha256": "85f53c8343eccbc05e0307ba50aba55379b03a05ae8a056ab3c0e291a50416d8",
          "sha1": "b39f0a0bbd52151202028c8e9d3342b9e0b6af3e",
          "md5": "275bfba75c91365f3c3d9f2788f9c31b"
        }
      ]
    }
  ]
}
