{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 57733,
          "sha512": "cdfd9596869df7f80c4cbe6725067a3f405b95b9ffb8b5cb7c0dc80cefd71e13de4e9251628ba2a87ba2337ba88a5b19da342db8e926bd7477d38edf078e4b4f",
          "sha256": "bf478bfec4618015ecf63bc1f0ad2313e900437c4d835c84e58840dd955179dc",
          "sha1": "008a810c5d9ebd21dc36dfb1d33831a8e66b2ba5",
          "md5": "8f4adc514c235920e5d6b76ff37005a8"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 57733,
          "sha512": "cdfd9596869df7f80c4cbe6725067a3f405b95b9ffb8b5cb7c0dc80cefd71e13de4e9251628ba2a87ba2337ba88a5b19da342db8e926bd7477d38edf078e4b4f",
          "sha256": "bf478bfec4618015ecf63bc1f0ad2313e900437c4d835c84e58840dd955179dc",
          "sha1": "008a810c5d9ebd21dc36dfb1d33831a8e66b2ba5",
          "md5": "8f4adc514c235920e5d6b76ff37005a8"
        }
      ]
    }
  ]
}
