{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_release-1.0.aar",
          "url": "local_auth_android_release-1.0.aar",
          "size": 41776,
          "sha512": "4061b51511d5b4945aeb0c4bcf5de7178b15c63f9f4a605dae5859dc25aa8de0c582de20da45610a42d424434d4e947b5a1e30b08893c26f647972be4e4c7e6a",
          "sha256": "1bdb848420808a8bb2d3dd9943cc9f78d5640a09faa221894075e55b0b5217d9",
          "sha1": "1179e30828184e32efa8df65eb1ebcd241d9a0f6",
          "md5": "8f40e950bc8082c1f58ebc1718559eb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_release-1.0.aar",
          "url": "local_auth_android_release-1.0.aar",
          "size": 41776,
          "sha512": "4061b51511d5b4945aeb0c4bcf5de7178b15c63f9f4a605dae5859dc25aa8de0c582de20da45610a42d424434d4e947b5a1e30b08893c26f647972be4e4c7e6a",
          "sha256": "1bdb848420808a8bb2d3dd9943cc9f78d5640a09faa221894075e55b0b5217d9",
          "sha1": "1179e30828184e32efa8df65eb1ebcd241d9a0f6",
          "md5": "8f40e950bc8082c1f58ebc1718559eb0"
        }
      ]
    }
  ]
}
