{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 21343,
          "sha512": "12b5fe656e9c47e18ff25f566232a82c93dfadfd991d246a7419123a72d3b0e3c196c886f8b5d07be43aad34aa5edf0e809dd65d08f09134f28670a79eda8c89",
          "sha256": "007ca63a24dc7c884827e7874ac74eb4ef77d7aba65d0874b4dfbd25f14e8d2a",
          "sha1": "564de3fdbb7aeeda1d68ba530ca125fb94b68420",
          "md5": "fb95079855cac63319511e9a48b22311"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 21343,
          "sha512": "12b5fe656e9c47e18ff25f566232a82c93dfadfd991d246a7419123a72d3b0e3c196c886f8b5d07be43aad34aa5edf0e809dd65d08f09134f28670a79eda8c89",
          "sha256": "007ca63a24dc7c884827e7874ac74eb4ef77d7aba65d0874b4dfbd25f14e8d2a",
          "sha1": "564de3fdbb7aeeda1d68ba530ca125fb94b68420",
          "md5": "fb95079855cac63319511e9a48b22311"
        }
      ]
    }
  ]
}
