{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 23494,
          "sha512": "1338a8e0f3ebc9c05de0e32d1bba1b51f9ee60fd564d0ffc73aa3a2dd53ad0022e4eb09cc7ea2a365fe1b8f6e90470b31375ac6b5fd4b73417a61409b346dd0b",
          "sha256": "32bc2ab63bdc2d5abc2d96d1aa44d537d104378d1c64d7fb2092aa16c04f8f99",
          "sha1": "0bea3563cd855b614a7357c19c7b790756703f6f",
          "md5": "a2fff2957cba8cd8598cf53772928e55"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 23494,
          "sha512": "1338a8e0f3ebc9c05de0e32d1bba1b51f9ee60fd564d0ffc73aa3a2dd53ad0022e4eb09cc7ea2a365fe1b8f6e90470b31375ac6b5fd4b73417a61409b346dd0b",
          "sha256": "32bc2ab63bdc2d5abc2d96d1aa44d537d104378d1c64d7fb2092aa16c04f8f99",
          "sha1": "0bea3563cd855b614a7357c19c7b790756703f6f",
          "md5": "a2fff2957cba8cd8598cf53772928e55"
        }
      ]
    }
  ]
}
