{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bhikadia.receive_intent",
    "module": "receive_intent_profile",
    "version": "1.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_profile-1.47.aar",
          "url": "receive_intent_profile-1.47.aar",
          "size": 12907,
          "sha512": "6e45d8cac3fd71e5d9cf200bc3184a5375f94c2b4573c27d83e69ef4081e5fda8cd3b814a7f032a63007cb678f738429a291ca9b9dc90ecfca64056f097068bc",
          "sha256": "e32680060d6b85215d266f40184f001ebde7f06939f3e6b9e2a06a575608d1f5",
          "sha1": "5229fa05ee02be73644e9204d9f59ad3e4779704",
          "md5": "e8d7e231f9e0b85cf31b3d5184fa6af1"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "receive_intent_profile-1.47.aar",
          "url": "receive_intent_profile-1.47.aar",
          "size": 12907,
          "sha512": "6e45d8cac3fd71e5d9cf200bc3184a5375f94c2b4573c27d83e69ef4081e5fda8cd3b814a7f032a63007cb678f738429a291ca9b9dc90ecfca64056f097068bc",
          "sha256": "e32680060d6b85215d266f40184f001ebde7f06939f3e6b9e2a06a575608d1f5",
          "sha1": "5229fa05ee02be73644e9204d9f59ad3e4779704",
          "md5": "e8d7e231f9e0b85cf31b3d5184fa6af1"
        }
      ]
    }
  ]
}
